3scale-gateway-openshift-template.yml
entrypoint.sh

- Detect if we are in openshift, use default route
- If we are not in openshift, use /etc/resolv.conf
- Let user set the resolver

fixing DNS issues in openshift

---

Makefile
docker-compose.yml
entrypoint.sh

nslookup call was crashing the entrypoint,
so shell out to prevent the crash and test it works with invalid dns

entrypoint was failing on nslookup failure, this fixes the issue by shelling out the var

---

Makefile
conf/nginx.conf
libexec/boot
src/configuration.lua

that should make readiness probe to mark instance as live
without requiring to make any request to it

load configuration at boot time

---

src/configuration.lua
src/provider.lua

```
2016/09/09 15:57:50 [error] 1#1: init_by_lua error: /opt/app/src/configuration.lua:282: no request object found
[C]: in function 'match'
/opt/app/src/configuration.lua:282: in function 'url'
/opt/app/src/configuration.lua:89: in function 'func'
/opt/app/src/configuration.lua:14: in function 'map'
/opt/app/src/configuration.lua:196: in function 'parse'
/opt/app/src/provider.lua:20: in function 'configure'
/opt/app/src/provider.lua:29: in function 'init'
init_by_lua:7: in main chunk
```
introduced in #57
/cc @jmprusi

fix crash when using ngx.re in init_by_lua

---

http.d/lua_ssl.conf

there is no way to write working cross platform configuration
so every platform will be responsible for bootstraping it

disable ssl validation

---

src/provider.lua
t/003-apicast.t

before it would try to call to backend even without any metrics

do not report to backend on no match

---

conf/nginx.conf
src/provider.lua
t/004-apicast-path-routing.t

implements #22
* try to match the service host and mapping rules to determine which service to use
@tnscorcoran after merging this you'll be able to start the gateway with `APICAST_PATH_ROUTING_ENABLED` environment variable set to whatever to enable this feature.
It will allow you to have two services with the same host, but still route to the one that matches the rules.
So if you have services A and B both with host 'api.example.com' where
A matches GET /a
and B matches GET /b
you'll be able to make requests:
```
GET /a
Host: api.example.com
```
```
GET /b
Host: api.example.com
```
just fine and they'll be routed to the appropriate service.
/cc @vramosp correct me if I'm not explaining it clearly

experimental path based routing

---

src/management.lua
src/util.lua
t/001-management.t

* DELETE /config
* run each test twice
* measure how long boot takes
* return null in json instead of a missing key

[management] allow deleting config

---

Dockerfile
entrypoint.sh

This is only for master branch not v2.
related to #69

Added fallback in case /dev/stdout is not writable, due old docker version

---

apicast/src/configuration.lua
spec/configuration_spec.lua

fixes:
init_by_lua error: /opt/app/src/configuration.lua:231: table index is nil

do not crash on ampty APICAST_SERVICES env variable

---

apicast/src/configuration.lua
apicast/src/management.lua
apicast/src/provider.lua
spec/configuration_spec.lua
t/001-management.t

Closes #94 
- `provider.contents` is already JSON-encoded, so no need to encode it again.
- adding `application/json` content type instead of the default `text/plain`

Remove double encoding for config and set content-type

---

apicast/bin/apicast

use `readlink -f` when available to follow nested symlinks

[bin] follow symlinks

---

Makefile
apicast/bin/apicast

apicast should not depend on luarocks
luarocks should be configured properly
to install into correct paths
depends on https://github.com/3scale/s2i-openresty/pull/12

[bin] drop luarocks

---

.env
apicast/bin/apicast
apicast/conf/nginx.conf
apicast/src/apicast.lua
apicast/src/configuration.lua
openshift/apicast-template.yml

exit when gateway can't find its configuration
propagate any error message
OpenShift template defaults to exiting on missing configuration.

ability to crash on missing configuration

---

openshift/apicast-template.yml

Resolves the error:
error: unable to load template file "openshift-template.yml": unable to decode "openshift-template.yml": [pos 3503]: json: expect char '"' but got char 'f'

Fix OpenShift template PATH_ROUTING value

---

apicast/src/apicast.lua
apicast/src/balancer.lua

The logic inside the balancer() method is probably not going to be used only from the Apicast module. Let's extract it and make it reusable.

Put balancer() logic of the apicast module in a separate & reusable module

---

apicast/conf.d/apicast.conf
apicast/src/apicast.lua
apicast/src/provider.lua
spec/provider_spec.lua

The content phase is executed before the log one, but in the config `log_by_lua` appeared before `content_by_lua`. There are some operations performed to calculate run times and to understand them it's necessary to know the order of execution of the phases. I think that sorting them in the config helps.

Sort directives by execution order in apicast.conf

---

apicast/src/apicast.lua
apicast/src/configuration.lua
apicast/src/provider.lua

This moves some of the logic that runs in the access phase to the rewrite one. Only 2 things have been moved, saving the service and the data needed to resolve upstream to ngx.ctx. This greatly simplifies writing a new module that shares a lot of functionality with the Apicast one and inherits from it.

Execute functionality that can be used in other modules in the rewrite phase

---

.mailmap

Add entries for people with multiple or wrong addresses.
This avoids running something like 'filter-branch' which would have
the side effect of rewriting the repository's history.
Edit: unable to push to this repository, so forking.

.mailmap: map authors to their names/addresses

---

apicast/conf.d/apicast.conf
apicast/src/provider.lua
apicast/src/resty/resolver.lua
apicast/src/resty/resolver/dns.lua
spec/resty/resolver_spec.lua

`/etc/resolv.conf` can specify `search` section that is used for domains without TLD.
For example on openshift, there is service `foobar`. If you try `dig foobar` you won't get an answer.
The proper host is `foobar.something.svc.cluster.local`. That domain is defined in the `search` section of `/etc/resolv.conf`.

DNS domain search

---

LICENSE
NOTICE

Closes #149 by changing license text to be Apache2.0 after confirming all contributors to date were 3scale employees at the time of contributing.

Change license file to have contents of Apache2.0 license

---

apicast/src/configuration.lua

`regexpify()` is being called in every request for each of the rules defined.
The rules do not change, so we can just call `regexpify()` when parsing the config file to construct a service.
I have profiled APIcast using stapxx and it was clear that this was a problem. With around 100 rules and 3k rps, `regexpify()` was consuming like 50% of the CPU time.

Perf improvement: Avoid unnecessary calls to regexpify() in configuration.lua

---

apicast/conf.d/apicast.conf
apicast/src/provider.lua

The `ngx.var.access_token` is not used anywhere else, so it can be safely removed too.

Remove unused OAuth location

---

.travis.yml
Makefile
README.md

Explain that you can find other test targets (docker etc) by using make help

Explain to use make help

---

doc/openshift-guide.md

Replaced vagrant instructions with `oc cluster up`.

update readme to use oc cluster up

---

apicast/src/configuration.lua
apicast/src/provider.lua
apicast/src/resty/url.lua
spec/configuration_spec.lua
spec/provider_spec.lua
spec/resty/url_spec.lua
t/003-apicast.t

fixes https://github.com/3scale/apicast/issues/183
unfortunately I could not figure out an easy way to write the integration test as it would have to run as a root and listen on port 80 or 443
but at least we have a test with https on explicit port, should be easy to add more special cases (like http2)

try to guess port from scheme when not provided

---

apicast/src/resty/http_authorization.lua
spec/resty/http_authorization_spec.lua

This is a base for future HTTP Authorization header support.
Right now it supports: 
* Basic
* Bearer

[resty-http_authorization] library to parse HTTP Authorization

---

apicast/src/provider.lua
spec/provider_spec.lua

using `#table > 0` won't work on tables with non numeric indexes

[configuration] fix reloading on every request

---

Makefile
apicast/src/configuration_store.lua

the missing configuration handler would be executed even when configuration 
was loaded successfuly
fixes https://github.com/3scale/apicast/issues/203

fix handling missing configuration

---

apicast/src/configuration_loader/file.lua
spec/configuration_loader/file_spec.lua

uses current working directory to create absolute path
I'm not sure if this is going to fix the inconsisecies. 
Definitely needs more testing.
@mayorova would be great if you could try if it fits your expectations. With some increased debug level it should always print the full path being loaded.

[configuration] read config with absolute path

---

.gitignore
.travis.yml
Makefile
apicast/src/configuration.lua
apicast/src/configuration/service.lua
apicast/src/provider.lua
doc/config.ld
rockspec
spec/configuration/service_spec.lua
t/003-apicast.t

* into new object: Service
* in the future can be extracted further in to Credentials
* uses new resty-http_authorization library
* now is a metamethod on new Service object
* remove old get_credentials
* overall unify credentials retrieval and handling
extracted from #162
This is a breaking change as it totally removes `:get_credentials` and changes `:extract_credentials` method. Imo it should be easier for modules to work with this, but would be good to get some feedback from @davidor.
the next steps would be to unify parameter extraction to fix https://github.com/3scale/apicast/issues/163
it should be prepared to parse json too and be lazy, as the payloads can be huge

[config] extract credentials handling

---

doc/parameters.md

Meant to be a verbose document (in addition to `.env` and `apicast-template.yml`) listing all parameters that can be used to modify the APIcast v2 behavior.
There are two links to documents that do not exist yet, but are planned to be added: `/doc/custom-config.md` and `/doc/path-routing.md`

Add a document listing all APIcast parameters

---

.gitignore
Makefile
README.md

depends on https://github.com/tcort/link-check/pull/3 plus other fixes before it can be totally usable
here is current output (with some local monkeypatch to pass the base url):
```
====================
Checking: ./.github/CONTRIBUTING.md
[✖] ../t
[✖] ../schema.json
[✖] ../examples/configuration
[✖] ../examples/configuration/multiservice.json
[✓] https://github.com/kubernetes/kubernetes/blob/master/docs/devel/faster_reviews.md
ERROR: dead links found!
====================
Checking: ./.github/ISSUE_TEMPLATE.md
====================
Checking: ./doc/build.md
[✓] https://openresty.org/en/
[✓] https://docs.docker.com/engine/tutorials/dockerimages/
[✓] https://github.com/3scale/apicast/blob/50daf279b3cf2da80b20ad473ec820d7a364b688/apicast-0.1-0.rockspec
[✓] …
```

[doc] integrate tool to check broken links in the documentation

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.travis.yml
README.md
doc/build.md
doc/openshift-guide.md
doc/parameters.md
examples/add-ssl/README.md
examples/custom-config/README.md
examples/custom-module/README.md
examples/oauth2/docker-compose.yml
examples/s2i/README.md
openshift/apicast-template.yml

now everything lives in master branch
as mentioned in https://github.com/3scale/apicast/pull/192#pullrequestreview-15720959

[doc] fix documentation after v2 branch removal

---

CHANGELOG.md
Makefile
apicast/conf.d/apicast.conf
apicast/src/apicast.lua
apicast/src/configuration_loader/remote_v1.lua
apicast/src/module.lua
apicast/src/user_agent.lua
bin/busted
bin/busted.lua
spec/module_spec.lua
spec/user_agent_spec.lua

closes #182
the header looks like:
```
APIcast/2.0 (OSX; x64; env:production) APIcast/2.0
```
and includes:
* APIcast core version
* APIcast module version (or any other loaded module, like XC)
* platform
* architecture
* deployment environment

send User-Agent with platform and system information

---

CHANGELOG.md
apicast/src/configuration.lua
apicast/src/provider.lua
t/003-apicast.t

* fixes #180
* fixes #216
The Service Token is unique per service, so there is no global configuration needed.
@3scale/documentation @3scale/support I guess this might need some documentation update?

fix X-3scale-Debug header by using Service Token

---

.luacheckrc
CHANGELOG.md
apicast/src/configuration_loader.lua
apicast/src/configuration_loader/remote_v2.lua
apicast/src/configuration_store.lua
apicast/src/resty/http_ng.lua
apicast/src/resty/http_ng/backend/async_resty.lua
apicast/src/resty/http_ng/backend/ngx.lua
apicast/src/resty/http_ng/backend/resty.lua
apicast/src/resty/http_ng/backend/test.lua
apicast/src/resty/http_ng/headers.lua
apicast/src/resty/http_ng/request.lua
apicast/src/resty/http_ng/response.lua
apicast/src/resty/resolver.lua
apicast/src/resty/url.lua
bin/busted
spec/configuration_loader/remote_v2_spec.lua
spec/fake_backend_helper.lua
spec/fixtures/echo.conf
spec/resty/http_ng/backend/async_resty_spec.lua
spec/resty/http_ng/backend/ngx_spec.lua
spec/resty/http_ng/backend/resty_spec.lua
spec/resty/http_ng/backend/test_spec.lua
spec/resty/http_ng/request_spec.lua
spec/resty/http_ng_spec.lua
spec/resty/resolver_spec.lua
spec/resty/url_spec.lua
t/003-apicast.t

Configuration environments (staging/production) using new API.
----- 
- it needs to connect to a socket, so probably test-nginx ?
- resty can import parts of the nginx configuration, for example to start a server

get config from the v2 api

---

apicast/src/configuration_store.lua
t/003-apicast.t

do not warn if the same service id defines the same host
this happens when configuration is being reloaded for example
> host api-2-3scale-staging.os.3sca.net for service 2 already defined by service 2

[configuration] fix duplicate host warning

---

apicast/bin/apicast

print following message to stderr before exiting when no openresty binary is found:
> ERROR: Could not find openresty executable in your PATH.
> Make sure you have one of: openresty-debug openresty nginx

[bin] fail with error message when openresty is not found

---

CHANGELOG.md
apicast/src/apicast.lua
apicast/src/configuration.lua
apicast/src/configuration_loader/file.lua
apicast/src/configuration_loader/remote_v1.lua
apicast/src/configuration_loader/remote_v2.lua
apicast/src/configuration_store.lua
apicast/src/module.lua
apicast/src/provider.lua
apicast/src/resty/env.lua
apicast/src/threescale_utils.lua
apicast/src/user_agent.lua
apicast/src/util.lua
spec/configuration_spec.lua
spec/resty/env_spec.lua
spec/spec_helper.lua
spec/user_agent_spec.lua

wraps current environment and caches calls to os.getenv
it is useful in tests to stub env and reset it on every test

[resty-env] introduce global environment object

---

apicast/conf.d/echo.conf
apicast/src/provider.lua
examples/configuration/echo.json

* on debug level, just look for `[echo]` in the log
* `echo.json` example, that sends backend to echo api too
* provider can handle invalid configuration (missing backend_version for example)
```shell
bin/apicast -c examples/configuration/echo.json -v -v -v 2>&1 | grep '\[echo\]' -A 5
```
```shell
curl "http://localhost:8080/video?user_key=foobar"
```
```
2017/01/18 15:54:27 [debug] 38689#0: *9 [lua] log_by_lua(echo.conf:6):2: [echo]:
GET /transactions/authrep.xml?=&service_id=1234&usage[hits]=1&user_key=foobar HTTP/1.1
Host: echo
User-Agent: APIcast/3.0.0-pre (OSX; x64; env:unknown) APIcast/3.0.0-pre
X-3scale-User-Agent: APIcast/3.0.0-pre+unknown
```

[echo] echo api prints requests to the debug log

---

Makefile

sometimes it would return `connection refused`
because the gateway haven't started yet

[make] wait for gateway to start when testing

---

apicast/src/resty/balancer.lua
spec/resty/balancer_spec.lua

so you can select peer without setting the balancer

[balancer] extract select_peer method

---

CHANGELOG.md
apicast/.s2i/bin/assemble
apicast/bin/entrypoint
apicast/http.d/resolver.conf
apicast/src/configuration_loader/remote_v1.lua
apicast/src/resty/http_ng/backend/async_resty.lua
apicast/src/resty/http_ng/backend/resty.lua
apicast/src/resty/resolver/http.lua
apicast/src/threescale_utils.lua
spec/resty/resolver/http_spec.lua

closes #236
depends on https://github.com/3scale/s2i-openresty/pull/16
This totally removes nginx `resolver` directive and fully relies on our internal DNS resolver.
Setting `RESOLVER`  env variable still works. Default servers are auto detected from `/etc/resolv.conf` on boot. Works everywhere (native/docker/openshift).
/cc @mayorova @mpguerra 
/cc @davidor this might be something XC will need on OpenShift to properly resolve redis via a Service.

use resty-resolver everywhere

---

CHANGELOG.md
apicast/src/resty/resolver/dns.lua

allocating dns resolver will cause opening a socket
flamegraphs: https://gist.github.com/mikz/22c650100409fb172dc543596c49a309

[resty.resolver] do not allocate dns socket unless used

---

apicast/src/apicast.lua
apicast/src/configuration_store.lua
apicast/src/proxy.lua
spec/configuration_store_spec.lua
t/003-apicast.t
t/004-apicast-path-routing.t

Refactoring and fixes:
- fixes #254 
- extract `set_backend_upstream` to a separate function
- distinguish `find_by_id` and `find_by_host` functions in configuration store and `find_service_strict` (treating both under the name 'host' is quite confusing)
- skip searching for the service in the post_action, and get it directly from the configuration by id (in APICAST_PATH_ROUTING_ENABLED mode iterating over all rules in `find_service_cascade` was useless)
- pass service as parameters to reduce getting value from `ngx.ctx`
Based on `performance-optimizations` branch to avoid future conflicts.

Fix path routing and refactoring

---

apicast/src/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

don't return error status when some services fail, because
they don't have to have working configuration
fixes https://issues.jboss.org/browse/THREESCALE-63

[remote_v2] return configuration for all available services

---

.env
apicast/bin/apicast
apicast/conf/nginx.conf
apicast/http.d/upstream.conf

* keep more connections opened
* allow configuring workers via env variable
we were able to pus through up to 5k requests per second

performance tuning

---

CHANGELOG.md
apicast/src/proxy.lua
t/003-apicast.t

even when host value is not provided

[backend] extract correct host from the backend endpoint

---

.travis.yml
CHANGELOG.md
Makefile
apicast/conf/nginx.conf
apicast/src/configuration_store.lua
apicast/src/proxy.lua
spec/configuration_store_spec.lua
spec/module_spec.lua

* prevent memory leaks with long running instances
* offers TTL
The important change here is when new configuration is loaded it overrides all existing configuration for those hosts. 
When path routing is not enabled nothing really happens as there can be just one service for each host.
But when path routing is enabled and first you load two services for host 'a' and next time just one service for host 'a' it removes the first service. Which is more correct.

[config] use LRU cache for configuration store

---

Dangerfile
doc/configuration.md
doc/management-api.md

Management API is for debugging only and should be marked as such.
https://issues.jboss.org/browse/THREESCALE-71

[doc] management api is for debugging only

---

CHANGELOG.md
apicast/src/configuration_loader/remote_v2.lua

This reverts commit 7281c82f48079d1a1759ba0295c2de9c609220a6.
Because our http client is not thread safe yet.
So accessing it from several threads will result in undefined behaviour.
This is limitation of underlying lua-resty-http.

Revert "[config] parallelize access to the v2 api"

---

apicast/src/configuration_store.lua
apicast/src/proxy.lua
spec/configuration_store_spec.lua
spec/proxy_spec.lua

when cache was set to 0 the configuration 
would be cached forever, because stale records were used
so don't consider stale config as being configured and reload
fixes https://issues.jboss.org/browse/THREESCALE-76

fix not reloading configuration

---

doc/parameters.md

This allows to  link the details of a specific parameter in other documentation pages (or to share it with people).

[doc] Use headers for the parameter names for an easier reference

---

CHANGELOG.md
apicast/src/backend_client.lua
apicast/src/proxy.lua
apicast/src/resty/http_ng.lua
apicast/src/resty/http_ng/backend/resty.lua
doc/config.ld
spec/backend_client_spec.lua

* using http_ng
* unit tested
* authrep + oauth authrep
* extracted from 414d313
* needed for https://github.com/3scale/apicast/pull/283 and https://github.com/3scale/apicast/pull/290
```lua
local backend_client = require('backend_client')
...
local service = ...
local backend = backend_client:new(service)
local res = backend:authrep({ user_key = 'foo' }, { ['usage[hits]'] = 1 })
```

[backend] introduce backend client

---

.gitattributes

so changelogs are easier rebased
https://github.com/olivierlacan/keep-a-changelog/issues/56
https://github.com/isaacs/github/issues/487
Not supported by GitHub merge interface but at least locally

[git] allow merge=union on the changelog file

---

CHANGELOG.md
apicast/src/configuration_loader/remote_v2.lua
doc/parameters.md
spec/configuration_loader/remote_v2_spec.lua

by setting `APICAST_SERVICE_${ID}_CONFIGURATION_VERSION` environment
variable to some version it is going to be used to lock to that version
depends on https://github.com/3scale/apicast/pull/292
no ideas how to document this, ideas ? @vramosp @3scale/support @jcechace ?

[configuration] allow locking service configuration version

---

examples/oauth2/README.md
examples/oauth2/auth-server/auth-server.rb
examples/oauth2/client/client.rb
examples/oauth2/client/views/root.erb

Fixes the `error: state does not match` error reported by @kevprice83 here: https://github.com/3scale/apicast/issues/282#issuecomment-286250869
To be honest, I am not sure how it was working before...
Also, allows to specify the full URI of the APIcast gateway.

Fix OAuth client example

---

CHANGELOG.md
apicast/src/proxy.lua
t/009-apicast-caching.t

I realized that in OAuth mode the auth caching was not working (not sure if it never worked, the bug or was introduced at some point.
Also, I've decided to remove the duplication in `authrep` and `oauth_authrep`, as only the internal location should be different for them. This can probably be improved further, by using the co-socket http library instead of internal locations.

Fix OAuth auth caching

---

CHANGELOG.md
apicast/src/configuration_loader.lua
apicast/src/configuration_loader/remote_v2.lua
t/012-configuration-loading-boot-with-config.t

fixes https://issues.jboss.org/browse/THREESCALE-80
* print reason why configuration could not be downloaded
* print more debugging information
example log:
```
2017/03/16 08:08:15 [error] 30795#0: [lua] configuration_loader.lua:80: init(): boot could not get configuration (exit 1)
2017/03/16 08:08:16 [warn] 30816#0: *2 [lua] remote_v2.lua:58: call(): failed to get list of services: invalid status, context: ngx.timer
./src/configuration_loader.lua:25: missing configuration
2017/03/16 08:08:15 [emerg] 30795#0: [lua] configuration_loader.lua:101: init(): failed to load configuration, exiting
```

[configuration] print better error messages on loading

---

examples/custom-module/verbose.lua

I was  trying to extend the default apicast module by using [this example](https://github.com/3scale/apicast/blob/master/examples/custom-module/verbose.lua), but we ran into some issues. I think this merge request should fix the example, but I'am not much of an lua expert.
The `module.lua` file loads the `apicast` or the overriden module, but calls the `new()` method when it is available. When the new method is not overridden it just returns the `apicast` module and not the module override.
The new code works for us.

Fix the custom module example

---

CHANGELOG.md
apicast/src/resty/resolver/dns_client.lua

lets delegate this work to a dns resolver like dnsmasq
it was broken and sometimes would return a string "killed" instead of
table with answers that would count as valid answer

[resolver] remove parallel dns query

---

CHANGELOG.md
apicast/src/configuration_loader.lua
spec/configuration_loader_spec.lua
t/013-configuration-loading-lazy.t

when configuration failed to download exception
prevented the clock to be released and next request
would fail loading the configuration

[configuration] fix locking of configuration loader

---

.env
CHANGELOG.md
apicast/src/apicast.lua
apicast/src/proxy.lua
t/003-apicast.t
t/005-apicast-oauth.t

redone https://github.com/3scale/apicast/pull/302
extracted from https://github.com/3scale/apicast/pull/302

[proxy] fix accessing undefined variable

---

CHANGELOG.md
apicast/bin/entrypoint

because openshift when reloading services reloads the dns
which will take more time to respond and dnsmasq using the other dns
server
which is public and returns invalid SOA for local domains
caching it for 30 seconds

[dns] do not cache non existent records in dnsmasq

---

CHANGELOG.md
apicast/src/configuration_loader.lua
apicast/src/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

so custom web service can be used to deliver the configuration
closes https://github.com/3scale/apicast/issues/228
if you set `THREESCALE_PORTAL_ENDPOINT` for example to `http://example.com/some/path` it is going to try to load configuration from `http://example.com/some/path/${THREESCALE_DEPLOYMENT_ENV}.json?host=${request_host}`.
If nothing is found it is going to try continue as usual.

[remote_v2] ability to load configuration from custom path

---

CHANGELOG.md
apicast/src/resty/resolver.lua
t/014-resolver.t

closes https://github.com/3scale/apicast/issues/321
we need to use all nameservers because we can't trust dnsmasq
as it returns the first answer even though it is not the same class
this was changed in https://github.com/3scale/apicast/pull/260
/cc @mayorova we have to use all resolvers in addition to the RESOLVER again

[dns] use both RESOLVER and resolver.conf

---

rockspec

to prevent silently upgrading it in tests and failing on new checks

[luacheck] lock luacheck version

---

CHANGELOG.md
apicast/src/configuration_store.lua
apicast/src/proxy.lua
spec/configuration_store_spec.lua
spec/proxy_spec.lua

this solves case when service changes a host
the old host would still be available with old configuration
even when new service configuration does not have it at all

[configuration] don't return stale configuration when new one is available

---

CHANGELOG.md
apicast/src/apicast.lua

```
TEST_NGINX_CHECK_LEAK=1 prove t/009-apicast-caching.t
t/009-apicast-caching.t .. TEST 6: multi service configuration
LeakTest: [4340 4352 4352 4360 4360 4368 4376 4376 4376 4404 4404 4424 4440 4444 4444 4444 4448 4448 4448 4468 4468 4468 4488 4524 4524 4536 4536 4536 4536 4540 4548 4548 4548 4568 4568 4568 4600 4600 4600 4600 4628 4628 4628 4632 4636 4636 4636 4636 4644 4644 4644 4644 4660 4660 4660 4672 4676 4676 4676 4704 4704 4704 4704 4720 4720 4768 4768 4768 4768 4776 4776 4812 4812 4812 4812 4824 4824 4824 4824 4824 4824 4824 4824 4848 4848 4848 4848 4848 4880 4880 4880 4880 4880 4880 4880 4880 4888 4888 4888 4888]
LeakTest: k=5.8
t/009-apicast-caching.t .. 1/? TEST 7: call to backend is cached
LeakTest: [4328 4360 4376 4392 4396 4400 4400 4440 4452 4456 4456 4480 4480 4484 4512 …
```

fix memory leak in post action

---

CHANGELOG.md
apicast/src/configuration_store.lua
spec/configuration_store_spec.lua

because nginx does it too and `ngx.var.host` is lowercase
fixes https://issues.jboss.org/browse/THREESCALE-82

[configuration] normalize service hosts to lowercase

---

CHANGELOG.md
apicast/src/oauth/keycloak.lua
spec/keycloak_spec.lua

[keycloak] Accept client credentials for token endpoint in Authorization header

---

CHANGELOG.md
apicast/src/apicast.lua
apicast/src/proxy.lua
doc/config.ld
spec/apicast_spec.lua
spec/proxy_spec.lua

* post_action should be called only after access phase
* oauth has own router so it does not need post_action
fixes https://github.com/3scale/apicast/issues/299#issuecomment-289743876

don't call post action for oauth routes

---

CHANGELOG.md
apicast/src/oauth/keycloak.lua
apicast/src/proxy.lua
spec/keycloak_spec.lua
spec/ngx_helper.lua
spec/proxy_spec.lua

In theory the expiry is checked already when validating the token and the call should be rejected before it even gets to the point where we are checking the auth response cache.
However for sake of correctness, JWT cached_key should be stored with ttl
To do: 
Closes #309

Store JWT in Auth cache with ttl

---

CHANGELOG.md
apicast/src/resty/balancer/round_robin.lua
t/016-balancer.t

using LRU cache with max entries to limit number of counters it is kept in memory
```
/016-balancer.t .. TEST 1: round robin does not leak memory
WARNING: method GET not supported for ab when taking a request body
LeakTest: [5768 5964 5964 6192 6224 6224 6500 6500 6500 6760 6788 6788 6928 7088 7088 7088 7532 8300 8300 8300 8300 8300 8856 9672 10084 10084 10084 10084 10084 10584 10584 10584 10584 10584 10776 11112 11112 11112 11112 11112 11460 11668 11668 11668 11668 11668 11872 12256 12256 12256 12256 12256 12256 12732 12872 12872 13128 14664 14664 14664 14664 14664 14664 14664 14664 15168 15968 16740 17500 18088 18164 18164 18164 18164 18164 18164 18164 18164 18164 18164 18460 19080 19144 19144 19144 19144 19144 19144 19144 19144 19144 19144 19144 19636 20164 20164 20164 20164 20164 …
```

[balancer] fix memory leak in round-robin balancer

---

Makefile
examples/custom-module/verbose.lua

This PR adds the examples directory to luacheck.
Merging this will probably break build though as there is a warning in custom-module/verbose.lua
```
Checking examples/custom-module/verbose.lua       1 warning
examples/custom-module/verbose.lua:4:7: unused variable mt
```

Add examples folder to luacheck

---

CHANGELOG.md
apicast/http.d/init.conf
apicast/src/module.lua

Closes #347 (only partially)
This helps, but still in some cases the error is confusing and doesn't really point to the module where the problem is. Instead it says something like:
```
[warn] 63285#0: [lua] module.lua:20: prequire(): cannot read apicast: Is a directory, stack traceback:
```
So, if there is a better way, please feel free to close this PR, or change the commit. Otherwise, maybe it's better than nothing.

Show more info on module load errors

---

CHANGELOG.md
apicast/src/resty/http_ng/backend/async_resty.lua
apicast/src/resty/http_ng/backend/resty.lua
apicast/src/resty/http_ng/response.lua
spec/resty/http_ng/backend/async_resty_spec.lua
spec/resty/http_ng/backend/resty_spec.lua
spec/resty/http_ng/response_spec.lua

they should always have access to the request object
no matter what error it is

[http] fix creating error responses

---

CHANGELOG.md
apicast/src/resty/http_ng.lua
apicast/src/resty/http_ng/backend/async_resty.lua
apicast/src/resty/http_ng/backend/cache.lua
apicast/src/resty/http_ng/backend/ngx.lua
apicast/src/resty/http_ng/backend/resty.lua
apicast/src/resty/http_ng/backend/test.lua
apicast/src/resty/http_ng/cache_store.lua
apicast/src/resty/http_ng/headers.lua
apicast/src/resty/http_ng/request.lua
apicast/src/resty/http_ng/response.lua
spec/fake_backend_helper.lua
spec/keycloak_spec.lua
spec/resty/http_ng/backend/async_resty_spec.lua
spec/resty/http_ng/backend/cache_spec.lua
spec/resty/http_ng/backend/ngx_spec.lua
spec/resty/http_ng/backend/resty_spec.lua
spec/resty/http_ng/backend/test_spec.lua
spec/resty/http_ng/cache_store_spec.lua
spec/resty/http_ng/headers_spec.lua
spec/resty/http_ng/request_spec.lua
spec/resty/http_ng/response_spec.lua

Using `Cache-Control: private` the http client 
should be able to cache responses and use the cache
on repeated calls
Good read: https://tools.ietf.org/html/rfc7234
You can use it like:
```lua
local cache_store = require('resty.http_ng.cache_store')
local resty_backend = require('resty.http_ng.backend.resty')
local cache_backend = require('resty.http_ng.backend.cache')
-- cache_backend.new(resty_backend) would use default cache store, but you can customise its size
local backend = cache_backend.new(resty_backend, { cache_store = cache_store.new(100) })
local http_client = http_ng.new({ backend = backend })
```

Add HTTP Cache support to http_ng

---

CHANGELOG.md
apicast/apicast-0.1-0.rockspec

https://github.com/pintsized/lua-resty-http/releases/tag/v0.10
https://github.com/SkyLothar/lua-resty-jwt/releases/tag/v0.1.10
/cc @3scale/productization updating rock dependencies to the latest version before next release

[luarocks] update lua-resty-http and lua-resty-jwt

---

CHANGELOG.md
apicast/src/balancer.lua
examples/custom-module/README.md
examples/custom-module/blacklist.lua
examples/custom-module/verbose.lua
rockspec
spec/examples/custom-module/blacklist_spec.lua

closes https://github.com/3scale/apicast/issues/308
* improve documentation in the example
* provide whole module (blacklist.lua)
* test that example module
and polish a bit balancer interface, so we can easily modify it from modules

describe module inheritance

---

apicast/libexec/run

so libexec helpers can have arguments

[libexec] allow forwarding arguments to libexec/run

---

CHANGELOG.md
apicast/src/oauth/apicast_oauth/authorize.lua
apicast/src/oauth/apicast_oauth/get_token.lua
apicast/src/threescale_utils.lua
t/005-apicast-oauth.t

3scale Service Management API would return 200 when app_key paramater
was empty for legacy purposes. That was not expected by the
gateway which was sending empty key for verification.
This was fixed on 3scale Service Management API and empty app_key
parameter will now return 409.
However, gateway should not rely jsut on 3scale Service Management,
so it performs own validation of the client secret during Access Token
generation.

[CVE-2017-7512] reject empty client secret

---

apicast/src/configuration.lua
apicast/src/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

because it is deserialized from json it can be `ngx.null`

[remote_v2] do not try to load oidc when issuer is null

---

.env
CHANGELOG.md
apicast/src/backend/cache_handler.lua
apicast/src/proxy.lua
doc/parameters.md
openshift/apicast-template.yml
spec/backend/cache_handler_spec.lua
spec/proxy_spec.lua
t/001-management.t
t/003-apicast.t
t/007-apicast-upstream-balancer.t
t/009-apicast-caching.t
t/018-module-loading.t
t/020-backend-cache-handler.t

Extract how cache is treated based on the backend response into a module.
It allows extension by adding custom handlers like:
```lua
local cache_handler = require('backend.cache_handler')
function cache_handler.handlers.custom(cache, cached_key, response, ttl)
cache:add(...)
return true or false
end
```
* strict is the original handler
- it removes cached key on any non successful response
* resilient is the new handler 
- stores response in cache only when it was not a server error
It also allows overriding `proxy.shared_cache` method to create custom cache instance for all proxies.
That can be useful when replacing local shared memory cache with something like redis.

Backend authorization cache handlers

---

.github/CONTRIBUTING.md

Not sure what was up with those hashtags before but the "Guideline Summary" did not get displayed correct as a headline in github.

Fixing Fixing headline formatting.

---

CHANGELOG.md
apicast/src/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

OpenShift template defaults to empty value.
That results in not loading any configurations when using the OpenShift template.

[remote_v2] ignore empty APICAST_SERVICES

---

CHANGELOG.md
apicast/src/configuration.lua
apicast/src/configuration/service.lua
apicast/src/oauth/oidc.lua
spec/configuration/service_spec.lua
t/019-apicast-oidc.t

Also use new field `authentication_method` to determine OIDC Service instead of by loading the configuration
That means you'll get authentication parameters missing or invalid when OIDC configuration could not be loaded instead of an error.

[oidc] don't crash when config is missing

---

CHANGELOG.md
apicast/bin/apicast
apicast/src/configuration_loader/remote_v2.lua
doc/parameters.md

Default to production environment on V2 API
Sets `THREESCALE_DEPLOYMENT_ENV` to `production` by default.
You can set it to empty value to disable this and use V1 API.

[remote_v1] disable v1 API by default

---

CHANGELOG.md
apicast/conf.d/apicast.conf

main apicast entrypoint can be now customized
with snippets of nginx configuration
the path is `apicast.d/location.d/*.conf`
fixes #399

[location.d] new extension block for location

---

CHANGELOG.md
apicast/src/configuration/service.lua
apicast/src/proxy.lua
spec/ngx_helper.lua
spec/proxy_spec.lua
t/003-apicast.t

fixes https://github.com/3scale/apicast/issues/395

handle partial credentials

---

CHANGELOG.md
apicast/http.d/core.conf

fixes https://github.com/3scale/apicast/issues/380
APIcast will now send unlimited body size from the client to the server.

[ngx] disable client_max_body_size

---

examples/cors/Dockerfile

This example uses the productised container image.

Example Dockerfile for apicast_cors.lua

---

CHANGELOG.md
apicast/src/module.lua

print loading errors only when it could not be found

[module] do not print warnings if module was loaded

---

CHANGELOG.md
apicast/src/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

resty-url happily concatenates nil which makes the http client crash

[remote_v2] don't crash when endpoint is missing

---

.busted
.luacheckrc
CHANGELOG.md
bin/busted
examples/cors/spec/cors_spec.lua

* it is in Perl instead of Shell
* it is aware of current working directory
* can run tests in different folders
* can load code in different folders
example:
```shell
bin/busted -C examples/cors
```
or from within different directory:
```shell
../../bin/busted
```

[bin] improve busted runner

---

CHANGELOG.md
apicast/src/resty/resolver.lua
spec/resty/resolver_spec.lua

resolver already has default empty search scope
so returning it in the parsed resolv.conf
would result in being used twice - duplicating queries

[resty.resolver] fix double empty search scope

---

CHANGELOG.md
apicast/.s2i/bin/run

improves performance as it does not send queries to upstream dns servers
that have invalid scope

[dnsmasq] don't forward domainless queries

---

apicast/src/threescale_utils.lua

A typo in the code meant the Redis port number could not be extracted from `REDIS_URL` fixes #374

fixes typo to extract Redis port from REDIS_URL

---

.circleci/config.yml
CHANGELOG.md
Makefile

upgrade openresty

---

Makefile

This PR fixes some target dependencies in the Makefile. Both `bash` and `dev` depend on `apicast-source` and `builder-image` to work.

Fix dev and bash target dependencies in Makefile

---

apicast/src/configuration_store.lua
spec/configuration_store_spec.lua

OIDC configuration can be null, that does not work like nil

[THREESCALE-360] fix loading configuration with null values

---

Dockerfile-development
Makefile
docker-compose-devel.yml
script/test

This PR adds a Dockerfile based on the builder image that installs all the dependencies required to run both the busted and the Test::Nginx tests.
The docker-compose file mounts a volume so the project source code is available in the image and sync'ed  with the local apicast directory. This way we can develop locally using our preferred environment and still be able to run the tests inside the docker container.
This PR also adds a helper bash script to run the tests.

Add dockerized development environment

---

CHANGELOG.md
apicast/src/oauth/apicast_oauth/get_token.lua
t/005-apicast-oauth.t

In the native OAuth flow, when storing access token in 3scale backend fails, currently a `200` status code is returned. It doesn't seem to be the desired behavior, as there's the following line:
```
ngx.exit(stored.status)
```
It also provokes the following warning message:
```
*1 attempt to set status 400 via ngx.exit after sending out the response status 200
```
This PR fixes it, and returns to the client the status code that was returned by the 3scale backend on token store attempt.

Set correct status code of the error on token store fail

---

CHANGELOG.md
apicast/conf.d/apicast.conf
t/005-apicast-oauth.t

Keeping the request headers may be causing the issue with passing an incorrect `Content-Type` to the 3scale backend when storing the access token (`POST https://su1.3scale.net/services/<SERVICE_ID>/oauth_access_tokens.xml`).
The only valid content types for this endpoint are:
- `application/x-www-form-urlencoded`
- empty header (backend with then handle it as `application/x-www-form-urlencoded` implicitly)

Don't pass the request headers to 3scale backend for native OAuth flow

---

CHANGELOG.md
apicast/conf.d/apicast.conf
t/005-apicast-oauth.t

Cherry-picked https://github.com/3scale/apicast/pull/433 to 3.1-stable

Don't pass the request headers to 3scale backend in native OAuth flow

---

CHANGELOG.md
apicast/src/configuration.lua
t/010-apicast-mapping-rules.t

Fixes #163 
Suppose we have this mapping rule: `POST /test?key={value}`.
Before this change, `curl -XPOST "http://localhost:8080/test?key=hello" -d "another=parameter"` did not match, but `curl -XPOST "http://localhost:8080/test" -d "key=hello&another=parameter"` did.
That's because in POST requests, body params were taken into account, but URI params were not. This PR changes that inconsistent behavior. Now both body & URI params are checked.
Please take a look at my comment here : https://github.com/3scale/apicast/compare/fix-mapping-rules-matching-post?expand=1#diff-5b5add30019fd642b1fd7ef108ef978eR75 and let me know if you would do it differently.

Fix inconsistent mapping rules matching in POST requests

---

CHANGELOG.md
apicast/src/management.lua
t/001-management.t

Both the ready and the live endpoints were returning 'text/plain', but the actual content is JSON.
Fixes https://issues.jboss.org/browse/THREESCALE-377

[THREESCALE-377] Fix ready and live endpoints content types

---

.circleci/config.yml
Makefile

* using lockfile ensures the same dependencies everywhere
* can be cached because uses one tree for all dependencies
* automatically installs rover by makefile
Please note that [lua-rover](https://github.com/3scale/lua-rover) is in alpha state. It might be horribly broken. Some features are not there yet.
Depends on https://github.com/3scale/s2i-openresty/pull/37

install dependencies by lua-rover

---

apicast/src/oauth/apicast_oauth/authorize.lua

Minor code cleanup.
The code in the 'else' branch in call() was never executed, but it was duplicated in check_client_credentials(), which is confusing.

oauth/authorize: delete duplicated code in check_credentials()

---

CHANGELOG.md
apicast/src/oauth/apicast_oauth/get_token.lua
doc/parameters.md
openshift/apicast-template.yml
t/005-apicast-oauth.t

Make oauth tokens TTL configurable

---

Dockerfile-development

The 'master' version (`s2i-openresty-centos7::1.11.2.5-2`) breaks the development environment. It's related to luarocks permissions. Let's use the previous one to keep working until I adapt the Dockerfile and scripts to the new one, and maybe start using lua-rover too.

Pin base image version in the Dockerfile for development

---

examples/custom-module/usage_limits_error.lua

This PR provides an example of how to return a different error message to the client, when the call is not authorized, because usage limits are exceeded for the application.
Basically, it's adaptation of this [CodeHub snippet](https://support.3scale.net/codehub/custom-error-codes) to new APIcast.
It can be used as a workaround until https://github.com/3scale/apicast/issues/368 is closed.

[example] Add example for custom error for exceeded usage limits

---

t/003-apicast.t
t/014-apicast-async-reporting.t

* add missing upstream definitions
* increase wait timeout so we actually get real error in the console
* increase dns ttl so it does not expire before second run

fix failing master build

---

apicast/src/configuration_store.lua
spec/configuration_store_spec.lua

This PR adds some tests for the configuration_store module. It also fixes a couple of the existing tests.

Add missing unit tests for configuration_store

---

Makefile

Fixes 
```
[12:07:18]  <michal>	ERROR: An error occurred: could not download file ("/opt/app" -> "/var/folders/4j/8_8n41pn79x__h1005mb3jnm0000gn/T/s2i533282500/upload/runtimeArtifacts/s2i-runtime-artifact969452182") from container 7f2e601c0abc2a270d4ebbc834739ea39d89638a0b007db08ec88a5b5c70b8d8: Error response from daemon: {"message":"Could not find the file /opt/app in container 7f2e601c0abc2a270d4ebbc834739ea39d89638a0b007db08ec88a5b5c70b8d8"}
```
when running `make runtime-image` when stale image is already in docker.

[s2i] always pull runtime image

---

apicast/conf.d/apicast.conf
apicast/http.d/upstream.conf
apicast/src/backend/cache_handler.lua
apicast/src/backend_client.lua
apicast/src/oauth/apicast_oauth/authorize.lua
apicast/src/oauth/apicast_oauth/get_token.lua
apicast/src/proxy.lua
apicast/src/resty/http_ng.lua
apicast/src/resty/http_ng/backend/ngx.lua
apicast/src/resty/http_ng/headers.lua
apicast/src/resty/http_ng/response.lua
spec/backend/cache_handler_spec.lua
spec/backend_client_spec.lua
spec/proxy_spec.lua
spec/resty/http_ng/backend/ngx_spec.lua
t/001-management.t
t/003-apicast.t
t/004-apicast-path-routing.t
t/005-apicast-oauth.t
t/006-apicast-subset-of-services.t
t/008-apicast-request-logs.t
t/009-apicast-caching.t
t/010-apicast-mapping-rules.t
t/019-apicast-oidc.t
t/020-backend-cache-handler.t

* use one endpoint for backend communication
* simplify test suite

use backend http client

---

t/TestAPIcast.pm

It is nice to not have to remember the full env variable. Just setting `DEBUG=1` will run in debug mode with more information.

[t] add DEBUG=1 to enable logging to stderr

---

apicast/bin/apicast
apicast/src/configuration_loader/file.lua
spec/configuration_loader/file_spec.lua

so for example `-c examples/configuration/echo.json` works
the cli changes directory to apicast and then all relative paths would
stop working
looks like this broke by #449

[cli] resolve files local to the current folder

---

.circleci/config.yml
CHANGELOG.md
Vagrantfile

Changelog: https://openresty.org/en/changelog-1013006.html
Fixes https://issues.jboss.org/browse/THREESCALE-362

[THREESCALE-362] upgrade openresty to 1.13.6.1

---

apicast/conf.d/apicast.conf
apicast/http.d/init.conf
apicast/http.d/upstream.conf
apicast/src/apicast.lua
apicast/src/balancer.lua
apicast/src/configuration.lua
apicast/src/configuration_loader.lua
apicast/src/executor.lua
apicast/src/linked_list.lua
apicast/src/management.lua
apicast/src/policy.lua
apicast/src/policy/echo.lua
apicast/src/policy/find_service.lua
apicast/src/policy/load_configuration.lua
apicast/src/policy/local_chain.lua
apicast/src/policy/phase_logger.lua
apicast/src/policy_chain.lua
apicast/src/proxy.lua
examples/configuration/echo.json
spec/apicast_spec.lua
spec/executor_spec.lua
spec/linked_list_spec.lua
spec/policy/find_service_spec.lua
spec/policy/load_configuration_spec.lua
spec/policy_chain_spec.lua
spec/policy_spec.lua
spec/proxy_spec.lua
t/apicast-policy-chains.t

Early prototype of how we could chain policies.
Policies can export data that is stored in read only structure and resolved in order they are defined in.
So values can be overlaid, but not overridden and only the latest one is being used.
This would allow overriding some internal structures being passed between policies.
Context object is passed to each policy phase invocation method. This context object has last layer mutable so policies can pass data.
Policy chain is itself a policy. All phase methods are compatible. So policy chain can contain policy chains.
This is used to split the chain into two: global and local. Global chain is responsible for loading configuration and local can be created based on downloaded configuration. 
- the list of policies enabled globally can be defined …

Policy chain - first version

---

CHANGELOG.md
apicast/src/resty/resolver.lua
t/TestAPIcast.pm
t/resolver.t

* defining an upstream can be used as a shortcut to skip DNS resolution
* if an upstream is defined with the same name then use the peers
extracted from https://github.com/3scale/apicast/pull/474

[resty.resolver] try to resolve upstream peers

---

CHANGELOG.md
apicast/src/backend_client.lua
spec/backend_client_spec.lua
t/apicast-oauth.t
t/apicast.t

When `no_body` is enabled via the `3scale-options-header`, backend does not return a response body. The body normally has lots of detail: metrics, limits, plans, etc. In the normal auth flow, all this information is not required. We only need to check the status code of the response. By enabling the `no_body` option, we will save some work to the 3scale backend and also reduce network traffic.
no_body cannot be enabled in the oauth flow, as there we need to parse the response body.

Enable the 'no_body' option when authorizing against 3scale backend

---

.gitignore
apicast/conf/nginx.conf.liquid
apicast/src/apicast/cli/start.lua
apicast/src/apicast/configuration.lua
docker-compose.yml
t/TestAPIcastBlackbox.pm
t/apicast-blackbox.t

This implements a base test class to provide blackbox testing of APIcast using the Test::Nginx framework.
Blackbox tests should define just JSON config.
They definitely should not hook into nginx configuration by setting or changing variables.
This makes the blackbox tests much more maintainable solution for the future.
Depends on https://github.com/3scale/apicast/pull/478
@3scale/qe this might be poking a bit into your turf, but still has no interaction with rest of the platform. It is meant for just static configuration.

blackbox tests using Test::Nginx 

---

apicast/src/policy/cors.lua
t/apicast-policy-cors.t

Closes #484 
This PR simply converts the existing CORS module into a policy without changing its behavior.
I've also added integration tests based on the new `TestAPIcastBlackbox` module.
@mikz  I have some questions about the current behavior of this CORS module. Please check my comments and let me know what you think.

Convert existing CORS module into a policy

---

Dockerfile-development
script/test

This PR simply adapts the paths used by the development Docker to the new structure introduced in https://github.com/3scale/apicast/pull/486

Adapt Docker development env to namespace changes

---

gateway/src/apicast/policy/cors.lua
t/apicast-policy-cors.t

This PR just adapts the CORS policy and its integration tests to the new paths introduced in https://github.com/3scale/apicast/pull/486

Use new namespacing in CORS to avoid deprecation messages

---

t/apicast-policy-cors.t

This was probably set up for debugging in the past and I forgot to delete it.

Delete 'ONLY' in cors test

---

examples/configuration/echo.json

This is to avoid deprecation messages:
`loader.lua:40: DEPRECATION: file renamed - change: require("apicast")
to: require("apicast.policy.apicast")`

examples/configuration/echo: use full namespace in the apicast policy

---

gateway/src/apicast/policy/headers.lua
t/apicast-policy-headers.t

Add headers policy

---

CHANGELOG.md
gateway/bin/cli
gateway/http.d/init.conf

It was possible for `luarocks.loader` to break rover scope
and load code from your home directory.
Now only rover dependencies are available after running `rover.setup`.
So all code has to be preloaded before running it.

fix rover loading code

---

CHANGELOG.md
gateway/src/apicast/executor.lua
gateway/src/apicast/policy_chain.lua
spec/executor_spec.lua
spec/policy_chain_spec.lua

It should be possible to load a policy chain and 
add policies to it.
After this chain is added to the executor it should not be modified.
This is going to be a foundation of how to configure policy chain 
by the environment configuration: https://github.com/3scale/apicast/pull/504
See the generated documentation: https://2580-53965666-gh.circle-artifacts.com/0/doc/modules/policy_chain.html

methods for policy chain manipulation

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
gateway/src/apicast/cli/environment.lua
gateway/src/resty/resolver.lua

so cosockets use internal resolver and don't have to
go through APIcast resolver.
Closes https://github.com/3scale/apicast/issues/488

[nginx] define resolver directive in the config

---

CHANGELOG.md
examples/policy_chain/README.md
examples/policy_chain/configuration.lua
gateway/http.d/init.conf
gateway/src/apicast/cli/environment.lua
gateway/src/apicast/policy/echo.lua

closes https://github.com/3scale/apicast/issues/481
It is possible to return a table with field `policy_chain` that is going to be used as the policy chain instead of the default one.
Example:
```lua
local policy_chain = require('apicast.policy_chain').default()
policy_chain:insert(mypolicy)
return {
policy_chain = policy_chain
}
```

ability to configure policy chains globally

---

CHANGELOG.md
gateway/http.d/init.conf
t/configuration-loading-boot-with-config.t

An example of what we would have to do if the init_by_lua_block
would contain some liquid - we would have to use only blackbox tests
and not include the `init.conf` in the Test::Nginx tests

[t] rewrite config loading test using blackbox

---

doc/policies.md

Add document that explains the new policies system

---

.circleci/config.yml
CHANGELOG.md
Makefile
docker-compose.yml
gateway/conf/nginx.conf.liquid
t/TestAPIcast.pm
t/TestAPIcastBlackbox.pm
t/apicast-async-reporting.t
t/apicast-upstream-balancer.t
t/apicast.t
t/configuration-loading-boot-with-config.t
t/management.t

Reduces CircleCI `prove` from 53 to 13s.
Automatically runs prove in parallel when `nproc` is available. And `make prove` will run tests in randomized directories and ports.
To achieve this all tests need to allocate a random port to listen on. That includes the TCP/UDP servers provided by Test::Nginx to stub DNS server.
The environment configuration can now configure echo/management/backend ports:
```lua
return {
port = {
apicast = '8080',
management = '8090',
backend = '8081',
echo = '8081',
},
}
```

[circleci] parallelize Test::Nginx suite

---

CHANGELOG.md
bin/busted
gateway/src/resty/resolver.lua
spec/resty/resolver_spec.lua
t/resolver.t

Fixes https://github.com/3scale/apicast/issues/510
@nmasse-itix do you mind trying it out?

[resty.resolver] support ipv6 resolvers

---

t/apicast-async-reporting.t
t/apicast.t

`--- ssl` is not actual directive,
but running the `random_port` filter will allocate a port

[t] fix clashing tests on port 1953

---

CHANGELOG.md
gateway/bin/apicast

to fix the rover detection on systems that don't have `lua_modules/bin` on the PATH
/cc @mayorova @kevprice83

[cli] detect local rover installation

---

CHANGELOG.md
gateway/bin/apicast

just don't print any error output when trying to detect rover

[bin] don't print warning when which/rover is not available

---

CHANGELOG.md
apicast-scm-1.rockspec
examples/custom-module/README.md
gateway/Makefile

so apicast can be installed from luarocks
broken since #486

[rockspec] fix luarocks rockspec

---

CHANGELOG.md
gateway/src/apicast/cli.lua

because the main APICAST_MODULE is loaded in the CLI
and it could have deprecated requires, we need to initialize the loader
that takes case of the deprecations
```
ERROR: ./src/apicast/policy_chain.lua:47: module apicast.module could not be loaded
./src/apicast/policy_chain.lua:47: in function 'build_default_chain'
./src/apicast/policy/local_chain.lua:20: in main chunk
[C]: in function 'require'
./src/apicast/policy_chain.lua:76: in function 'load'
./src/apicast/policy_chain.lua:47: in function 'default'
./src/apicast/cli/environment.lua:57: in main chunk
[C]: in function 'require'
./src/apicast/cli/command/start.lua:12: in main chunk
```

[cli] load apicast loader

---

CHANGELOG.md
gateway/src/apicast/policy/url_rewriting/policy.lua
gateway/src/apicast/policy/url_rewriting/schema.json
t/apicast-policy-url-rewriting.t

This is a first version of the URL rewriting policy. I'd rather agree on the basics first and add more functionality later.
Currently, this policy works well when placed after the apicast policy in the policy chain. However, it does not when placed before the apicast policy. In that case, the URL would be rewritten, and the matching rules would apply over that rewritten URL. To make that work, we need to make a few changes in the code before. For example, we need to stop relying on `ngx.var.request` when matching mapping rules, because it does not change after rewriting the url with `ngx.req.set_uri`.

Introduce URL rewriting policy

---

CHANGELOG.md
gateway/src/apicast/policy/cors/policy.lua

Introduce extra empty lines so the list shows correctly with one item per line.

Fix ldocs formatting in the CORS policy

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/configuration/service.lua
gateway/src/apicast/policy/find_service/policy.lua
gateway/src/apicast/proxy.lua
spec/configuration/service_spec.lua
spec/policy/find_service/policy_spec.lua
spec/proxy_spec.lua
t/apicast-policy-url-rewriting.t

This PR introduces some changes in the code to stop depending on `ngx.var.request`. That variable is not changed after rewriting a url with `ngx.req.set_uri`, which is what the URL rewriting policy does. This was preventing us from placing the URL rewriting policy before the apicast one in the policy chain.
This was done without breaking compatibility with users that overwrite `Configuration.extract_usage()` and rely on it being called.
This limitation was presented in #529

Make it possible to place url rewriting before apicast in the policy chain

---

.busted
CHANGELOG.md
gateway/bin/apicast
gateway/conf.d/apicast.conf
gateway/conf/nginx.conf.liquid
gateway/http.d/init.conf
gateway/libexec/boot.lua
gateway/src/apicast/loader.lua
gateway/src/apicast/module.lua
gateway/src/apicast/policy_chain.lua
gateway/src/apicast/user_agent.lua
spec/spec_helper.lua

instead of using a package.path

use apicast.loader to load policies

---

CHANGELOG.md
gateway/src/apicast/loader.lua

namespace deprecation message would show even when not necessary as the prefix searcher would always return something (loader or an error message) showing deprecation warnings for files like `apicast.moonscript`.
I don't really know how to trigger it to test it.

[loader] fix invalid deprecation message

---

CHANGELOG.md
gateway/bin/apicast
gateway/src/apicast/cli/template.lua

so when APIcast is executed in different folder it adds local src folder to the load path
and filesystem filter in liquid can resolve files in current folder too

[bin] add local src folder to load path

---

Dockerfile-development

This is needed to install `Test::APIcast`.
Port the change from https://github.com/3scale/apicast/pull/528

Dockerfile-development: install cpan deps with cpanminus

---

CHANGELOG.md
gateway/src/apicast/backend/cache_handler.lua
gateway/src/apicast/proxy.lua
spec/backend/cache_handler_spec.lua
spec/proxy_spec.lua

Extracting the rejection reason and checking if the request has been authorized has nothing to do with the cache. We only need to check the response status and a header. This is why I'd rather not have this in the cache_handler module.
Apart from that, this change will simplify the implementation of the caching policy.

Extract rejection reason in Proxy instead of CacheHandler

---

CHANGELOG.md
gateway/bin/apicast
gateway/conf/nginx.conf.liquid
gateway/src/apicast/cli/environment.lua

* detect where libraries are installed
* correctly set all paths when starting nginx

[bin] fix loading apicast from luarocks

---

CHANGELOG.md
Makefile
Vagrantfile
doc/performance.md
gateway/bin/apicast
gateway/cpanfile
t/apicast-oidc.t

Change Vagrant box from CentOS to Fedora so we can use the latest tooling.
For development it makes sense to use latest profiling tooling like eBPF, perftools, SystemTap, ...
In centos all those tools are quite ancient because of the 3.11 kernel.
* support for running/testing with different openresty binaries
* install cpan dependencies inside vagrant
* run redis inside vagrant
* respect APICAST_DIR
* performance tune nginx config
* link all tools from openresty systemtap toolkit

[vagrant] use fedora 26

---

doc/parameters.md

fixes typos and old links to 3scale support site.
/cc @3scale/documentation

fixes typos

---

CHANGELOG.md
Vagrantfile
doc/performance.md
gateway/conf.d/apicast.conf
gateway/src/apicast/policy/apicast/policy.lua
gateway/src/resty/ctx.lua
t/apicast-policy-chains.t
t/apicast.t
t/resty-ctx.t

By sharing ngx.ctx with the subrequest we are able to 
share the policy chain and execute the post_action phase.
It **should** be safe, but we should focus on trying this during QE process.
```
wrk --connections 10 --threads 10 --duration 60 'http://localhost:8080/?user_key=foo'
Running 1m test @ http://localhost:8080/?user_key=foo
10 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     5.25ms    0.93ms  17.38ms   69.83%
Req/Sec   191.24     16.50   393.00     73.23%
114377 requests in 1.00m, 41.55MB read
Requests/sec:   1903.26
Transfer/sec:    708.06KB
```
```
wrk --connections 10 --threads 10 --duration 60 'http://localhost:8080/?user_key=foo'
Running 1m test @ http://localhost:8080/?user_key=foo
10 threads and 10 connections
Thread Stats   Avg …
```

[policy] trigger post_action phase

---

CHANGELOG.md
gateway/conf.d/backend.conf
gateway/conf.d/echo.conf
gateway/conf/nginx.conf.liquid

* enable PCRE JIT
* decrease timer resolution
```
Running 5m test @ http://localhost:8080/?user_key=foo
10 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    35.62ms   43.91ms   1.17s    96.23%
Req/Sec   330.45    119.79     1.43k    60.45%
978844 requests in 5.00m, 350.02MB read
Requests/sec:   3262.07
Transfer/sec:      1.17MB
```
```
Running 5m test @ http://localhost:8080/?user_key=foo
10 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    30.21ms   28.69ms   1.22s    96.09%
Req/Sec   360.57    111.95     0.94k    60.84%
1071946 requests in 5.00m, 383.31MB read
Requests/sec:   3571.97
Transfer/sec:      1.28MB
```
---
Looks like 10% increase.

[nginx] performance tuning nginx config

---

CHANGELOG.md
gateway/src/apicast/backend/cache_handler.lua
gateway/src/apicast/policy/apicast/policy.lua
gateway/src/apicast/policy/caching/policy.lua
gateway/src/apicast/policy/caching/schema.json
spec/policy/caching/policy_spec.lua
t/apicast-policy-caching.t

First version of the caching policy.
The functionality is almost the same as the behavior that can be achieved using `APICAST_BACKEND_CACHE_HANDLER`. Apart from the two modes supported (strict, resilient), this policy adds the possibility of configure Apicast to not use a cache and make all the calls synchronously.
This does not break compatibility. If this policy is not included, users can still use `APICAST_BACKEND_CACHE_HANDLER`.
This PR duplicates some of the code in `cache_handler.lua`. I think that's fine because we'll get rid of the duplication once we split Apicast into smaller policies.

Cache policy

---

CHANGELOG.md
gateway/libexec/run
gateway/src/apicast/configuration_loader.lua

Improve libexec by:
* Don't change current directory so all relative configuration files can be resolved
* Respect APICAST_DIR
* Use Perl script that is aware of where it is stored on the filesystem
* Respect APICAST_LOG_LEVEL environment

[libexec] improve path resolving

---

CHANGELOG.md
gateway/config/production.lua
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/cli/environment.lua

* use nproc to detect number of cores
- nproc correctly detects limits set by docker
/cc @jmprusi

[cli] detect number of CPU cores

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/src/apicast/executor.lua
gateway/src/apicast/policy/apicast/policy.lua
gateway/src/apicast/policy/echo/policy.lua
gateway/src/apicast/policy/policy.lua
gateway/src/apicast/policy_chain.lua
spec/policy_spec.lua
t/apicast-policy-chains.t
t/apicast.t
t/deprecation-warnings.t

Content phase is for generating actual content. APIcast policy is going to use `ngx.exec` to  do internal redirect to the `@upstream` location which handles fetching the upstream response by post_action.
Policies can hook into this process by implementing own `content` handler that will respond with headers and body. For example some policy could fetch the upstream response by cosocket API instead of using nginx proxy_pass.
```
wrk --connections 10 --threads 10 --duration 60 'http://localhost:8080/?user_key=foo'
Running 1m test @ http://localhost:8080/?user_key=foo
10 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     3.46ms    1.02ms  15.42ms   82.60%
Req/Sec   291.47     31.81   626.00     79.82%
174339 requests in 1.00m, 63.34MB read
Requests/sec: …
```

introduce content phase

---

CHANGELOG.md
gateway/src/apicast/policy/caching/policy.lua
gateway/src/apicast/policy/caching/schema.json
spec/policy/caching/policy_spec.lua
t/apicast-policy-caching.t

This mode caches authorized and denied calls. When backend is unavailable, it will cache an authorization. In practice, this means that when backend is down _any_ request will be authorized unless last call to backend for that request returned 'deny' (status code = 4xx).
Closes #126

Add 'allow' mode in the caching policy

---

CHANGELOG.md
gateway/src/apicast/policy/upstream/policy.lua
gateway/src/apicast/policy/upstream/schema.json
t/apicast-policy-upstream.t

This is a first version of the upstream policy. For now, it only allows to modify the host of a request based on a set of rules that act on its path, but we can add more functionality later.

Add upstream policy

---

CHANGELOG.md
gateway/src/apicast/policy/apicast/policy.lua
gateway/src/apicast/proxy.lua
spec/policy/apicast/policy_spec.lua
spec/proxy_spec.lua

fixes https://github.com/3scale/apicast/issues/495
This allows policy authors to modify `usage` in the rewrite phase as it is being used later in the `access` phase. That can be used to for example report custom metrics matched by the policy.

[proxy] split proxy:call() into rewrite and access phase

---

bin/busted

So busted tests can print debug output from nginx by setting APICAST_LOG_LEVEL.
And so that tests know where is the APIcast source code.
Extracted from #566.

[busted] test runner improvements

---

CHANGELOG.md
gateway/src/apicast/policy/cors/policy.lua

This PR introduces a minor improvement in the CORS policy.
In the case of a preflight request, we were setting the CORS headers twice. This PR fixes that.
Thanks @mayorova for reporting.

policy/cors: stop setting headers twice in preflight reqs

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/mapping_rule.lua

Minor refactoring.
This PR extracts MappingRule from Configuration. There were many local methods in `Configuration` that were related only to mapping rules, so I think this makes sense.
Just to be clear, there are no changes in the implementation nor the test coverage.
I think that some of the code from `Service` should also be in this new module, but let's go step by step.
Let me know what you think @mikz . If you agree I'll add some documentation for the public methods.

Extract MappingRule from Configuration

---

gateway/src/apicast/configuration/service.lua
gateway/src/apicast/mapping_rule.lua
spec/mapping_rule_spec.lua

Refactor.
This PR moves the method that checks a mapping rule againts a request from the `Service` module to the `MappingRule` module. I think it clearly belongs there.
This PR also adds some unit tests for the matching of mapping rules.

Move mapping rule checking to MappingRule and add missing tests

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
t/apicast-mapping-rules.t
t/apicast.t

This PR fixes the tests that expect response debug headers to be set without enabling the debug option via headers.

Fix tests that expect debug output without enabling the option

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/policy_chain.lua
gateway/src/apicast/policy_loader.lua
spec/fixtures/policies/test/1.0.0-0/dependency.lua
spec/fixtures/policies/test/1.0.0-0/policy.lua
spec/fixtures/policies/test/2.0.0-0/dependency.lua
spec/fixtures/policies/test/2.0.0-0/policy.lua
spec/policy_loader_spec.lua

Depends on https://github.com/3scale/apicast/pull/578
Policies will be able to load only own code (in their subpath).
Loading the policy twice results in different policy. 
Different policies (and versions) can have different dependencies.
Very light sandbox is not meant for security, but for ease of use and preventing mistakes. Policies should not be able to access the global environment (except `ngx` variable).
Spec: https://gist.github.com/mikz/ceb8f141de2e8f74206761abda231f70

Sandbox policy loading

---

CHANGELOG.md
gateway/src/apicast/configuration/service.lua
gateway/src/apicast/mapping_rules_matcher.lua
gateway/src/apicast/policy/apicast/policy.lua
gateway/src/apicast/policy/find_service/policy.lua
gateway/src/apicast/proxy.lua
gateway/src/apicast/usage.lua
spec/mapping_rules_matcher_spec.lua
spec/proxy_spec.lua
spec/usage_spec.lua

This PR:
* Extracts a Usage module. This allows us to 'merge' usages hiding the internal data structures.
* Extracts a MappingRulesMatcher. This will allow us to match rules from policies.
These 2 things are needed to implement the SOAP policy (#567)

Extract MappingRulesMatcher and Usage modules

---

CHANGELOG.md
gateway/src/apicast/policy/soap/apicast-policy.json
gateway/src/apicast/policy/soap/init.lua
gateway/src/apicast/policy/soap/soap.lua
gateway/src/apicast/proxy.lua
spec/policy/soap/policy_spec.lua
t/apicast-policy-soap.t

This policy adds support for a very small subset of SOAP.
This policy basically expects a SOAPAction URI in the SOAPAction header or the content-type header.
The SOAPAction header is used in v1.1: https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528, whereas the Content-Type header is used in v1.2: https://www.w3.org/TR/soap12-part2/#ActionFeature
The SOAPAction URI is matched against the mapping rules defined in the configuration of the policy and the usage resulting from that is authorized and reported against 3scale's backend.

SOAP policy

---

CHANGELOG.md
doc/parameters.md
doc/policies.md
examples/policies/README.md
examples/policies/example.json
examples/policies/ngx-example/1.0.0/apicast-policy.json
examples/policies/ngx-example/1.0.0/init.lua
examples/policies/ngx-example/1.0.0/ngx_example.lua
gateway/bin/apicast
gateway/conf.d/apicast.conf
gateway/conf/nginx.conf.liquid
gateway/http.d/init.conf
gateway/src/apicast/backend_client.lua
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/policy_loader.lua
gateway/src/apicast/proxy.lua
spec/policy_loader_spec.lua
t/apicast-policy-upstream.t

Allow configuring policy load paths from the CLI.
That makes easier testing and development.

[cli] allow changing policy load path

---

CHANGELOG.md
gateway/bin/apicast

* so the first resty instance is started with proper log level

[bin] honour APICAST_LOG_LEVEL env

---

gateway/bin/apicast

looks like s2i-openresty installs luarocks to a different path

[bin] fix bin/apicast builtin policy path detection

---

.circleci/config.yml

should result in faster builds
https://github.com/3scale/s2i-openresty/releases/tag/1.13.6.1-rover6

[circleci] update s2i-openresty

---

examples/policies/ngx-example/1.0.0/apicast-policy.json

Minor fix. The version of the schema did not match the version in the directory of the policy.

Fix version in json schema of example policy

---

gateway/conf/nginx.conf.liquid
gateway/cpanfile

Updates Test::Apicast to v0.07 http://search.cpan.org/~mcichra/Test-APIcast-0.07/
This allows us to test the management API using `Test::APIcast::Blackbox`.

Update Test::APIcast to v0.07

---

CHANGELOG.md
Makefile
doc/parameters.md
docker-compose.yml
gateway/conf.d/echo.conf
gateway/config/development.lua
gateway/config/production.lua
gateway/config/sandbox.lua
gateway/config/staging.lua
gateway/cpanfile
gateway/http.d/init.conf
gateway/libexec/run
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/cli/environment.lua
gateway/src/apicast/configuration_loader.lua
t/configuration-loading-boot-with-config.t

* `THREESCALE_DEPLOYMENT_ENV` controls the 3scale proxy configuration
channel (staging/production) and can be passed as `-3 --channel` from the CLI
* `APICAST_ENVIRONMENT` controls the APIcast settings (caching, ...) and can be passed by `-e --environment` from the CLI
* `APICAST_LOADED_ENVIRONMENTS` can control always loaded APIcast environments (internal use only)
* update Test-APIcast to include https://github.com/3scale/Test-APIcast/pull/3
* `production` is still the default configuration channel, that loads the `production` environment configuration which configures the configuration loader to "boot". In short this makes APIcast to require `THREESCALE_PORTAL_ENDPOINT` or `--configuration` when started without any other params. That makes `bin/apicast` to not start because it is …

[cli] decouple apicast environment and 3scale configuration channel

---

gateway/Makefile
gateway/libexec/run

Also libexec should use only absolute directories because it runs nginx in different workdir.

[libexec] fix missing libexec when installed by luarocks

---

gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/policy_loader.lua

* policy load paths passed from the cli would not be recognized when
loading environment configuration
* policy loader now exposes functions instead of strings, so they are
refreshed
* cli now sets the policy load path to environment before loading
configurations
Given a command: `apicast --policy-load-path custom --environment custom.lua`
When `custom.lua` tries to load a policy that is only under the custom path.
Then CLI fails to load it because the policy path would not be set properly yet.
We are missing CLI tests, so this is not really tested.

[cli] properly configure policy load paths

---

CHANGELOG.md
gateway/cpanfile
gateway/src/apicast/management.lua
gateway/src/apicast/policy_manifests_loader.lua
script/get_built_in_policy_manifests.sh
t/fixtures/policies_endpoint_test/policies/example1/1.0.0/apicast-policy.json
t/fixtures/policies_endpoint_test/policies/example1/1.0.0/example1.lua
t/fixtures/policies_endpoint_test/policies/example1/1.0.0/init.lua
t/fixtures/policies_endpoint_test/policies/example2/1.0.0/apicast-policy.json
t/fixtures/policies_endpoint_test/policies/example2/1.0.0/example2.lua
t/fixtures/policies_endpoint_test/policies/example2/1.0.0/init.lua
t/management-policies-endpoint-custom.t
t/management-policies-endpoint.t

This PR introduces an endpoint in the management API to get all the schemas of the policies, both the built-in ones and the ones loaded using the `--policy-load-path` option.
/cc @3scale/system @macejmic the Policy API has now final shape.
This is the output with the policies we have:
```bash
curl "http://172.18.0.3:8090/policies/" | jq
{
"policies": [
{
"description": [
"This policy allows to modify the path of a request. ",
"The operations supported are sub and gsub based on ngx.re.sub and ",
"ngx.re.gsub provided by OpenResty. Please check ",
"https://github.com/openresty/lua-nginx-module for more details on how ",
"to define regular expressions and learn the options supported."
],
"$schema": "http://apicast.io/policy-v1/schema#manifest#",
"name": "URL rewriting policy", …
```

Endpoint to fetch JSON manifests of policies

---

t/apicast-blackbox.t
t/apicast-policy-caching.t
t/apicast-policy-cors.t
t/apicast-policy-headers.t
t/apicast-policy-url-rewriting.t
t/balancer.t
t/configuration-loading-lazy.t
t/deprecation-warnings.t

Test::APIcast runs each test twice by default. Some of the tests were run just once for no reason. This PR makes sure that the default applies for those tests. Also, for the tests that can't run twice, this PR documents the reason.

Run each Test::Nginx test twice by default

---

CHANGELOG.md
gateway/src/apicast/cli/environment.lua
gateway/src/apicast/policy_loader.lua
gateway/src/resty/sandbox.lua

* Extracts sandbox from policy loader to own module.
* Load environment configurations with the same sandbox env as policies.
* Expose `arg` in sandbox.
* Expose also `cli` as an alias to `arg` when loading environment configurations.
So policies can detect if they are being executed on the CLI
and decide to do something different like not loading themselves.
Because some might require shared dict that is not available.

[sandbox] environment policies have the same env as policy loader

---

gateway/src/apicast/configuration_loader/remote_v2.lua

Cloud Hosted deployment has various configurations that have issues and fail to load OIDC.
We have to be able to silence those errors.
This is meant to be internal, so no documentation.

[oidc] configure OIDC log level with APICAST_OIDC_LOG_LEVEL

---

CHANGELOG.md
gateway/src/apicast/policy/apicast/apicast-policy.json

Without a manifest, it will not show up in the policies endpoint.

Add JSON manifest for APIcast policy

---

CHANGELOG.md
gateway/src/apicast/cli/environment.lua

Thanks @jmprusi 
Looks like kubernetes exposes number of available milicores as CPU shares. This value is used only when running on kubernetes to prevent misdetection as CPU shares can be any arbitrary number as it is just relative weight.
From https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run:
> The `spec.containers[].resources.requests.cpu` is converted to its core value, which is potentially fractional, and multiplied by 1024. The greater of this number or 2 is used as the value of the --cpu-shares flag in the docker run command.
BTW default value is 1024:
```shell
$ docker run alpine cat /sys/fs/cgroup/cpu/cpu.shares
1024
```

[cli] detect number of available CPU shares from cgroups

---

CHANGELOG.md
doc/parameters.md
examples/ssl-verification/badssl.json
gateway/Roverfile.lock
gateway/conf.d/apicast.conf
gateway/cpanfile
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/cli/environment.lua
gateway/src/apicast/cli/template.lua
gateway/src/resty/resolver.lua
t/apicast-async-reporting.t
t/apicast-policy-upstream.t
t/apicast-upstream-balancer.t
t/apicast.t
t/management.t
t/mutual-ssl.t

This PR introduces 2 new ENVs (`APICAST_PROXY_HTTPS_CERTIFICATE_KEY ` and `APICAST_PROXY_HTTPS_CERTIFICATE`), they are used to set a client SSL certificate using the `proxy_ssl_certificate` and the `proxy_ssl_certificate_key` NGINX directives.
As a limitation, this certificate needs to be valid for all the services configured.

[THREESCALE-328] Allow to set a client SSL cert for upstream

---

CHANGELOG.md
gateway/conf.d/echo.conf
gateway/conf/nginx.conf.liquid
t/apicast-policy-upstream.t
t/sanity.t

APIcast should not drop any headers and just pass them to upstream. Fixes https://issues.jboss.org/browse/THREESCALE-630.

[THREESCALE-630] passthrough invalid HTTP headers

---

t/apicast-path-routing.t
t/apicast-subset-of-services.t

Minor change.
This PR just replaces the usages of `APICAST_PATH_ROUTING_ENABLED` and `APICAST_SERVICES`
in our tests because they were deprecated in favor of `APICAST_PATH_ROUTING` and `APICAST_SERVICES_LIST`.
Some warnings were printed while running the tests because of this.

Stop using deprecated envs in Test::Nginx tests

---

gateway/cpanfile
t/fixtures/echo.json
t/fixtures/upstream.json
t/sanity.t

Simple way of having fixtures for common blackbox configurations.
depends on https://github.com/3scale/Test-APIcast/pull/5

[t] use configuration fixtures

---

t/apicast-async-reporting.t
t/apicast-blackbox.t
t/apicast-oauth.t
t/apicast-oidc.t
t/apicast-policy-cors.t
t/apicast-policy-headers.t
t/apicast-policy-soap.t
t/apicast-policy-upstream.t
t/apicast-policy-url-rewriting.t
t/apicast.t

luassert version is not only way shorter, but also:
* writes proper error message on failure
* ignores order of elements (that can happen when openresty was compiled differently)
I also wanted to expose it as `assert` by the environment configuration generated by Test::APIcast::Blackbox, but can't due to the sandbox. 
Travis fails to check links because JIRA is down.

[t] cleanup integration tests with luassert

---

spec/ngx_helper.lua
spec/policy/cors/cors_spec.lua
spec/policy/headers/headers_spec.lua
spec/proxy_spec.lua

This PR modifies the `after_each` in the busted helpers to make sure that we start with a clean ngx state on every test.

Reset ngx state on every test

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
spec/configuration_spec.lua
t/apicast-policy-chains.t

> src/apicast/configuration.lua:62: attempt to get length of local 'policies' (a userdata value)

[configuration] fix error when loading empty policy chain

---

gateway/Roverfile.lock

* scm-1 was marked as development again so we can use normal versioning
* fixes a failure to install dependencies because there is no liquid scm-1

[rover] update liquid version

---

README.md
doc/why.md

The website has been down for days and our builds are failing in Travis because of the linter that checks for broken links. Point to the GitHub repo instead.

Fix busted lib broken links

---

CHANGELOG.md
doc/policies.md
gateway/Roverfile.lock
gateway/apicast-scm-1.rockspec
gateway/conf/nginx.conf.liquid
gateway/config/development.lua
gateway/src/apicast/executor.lua
gateway/src/apicast/policy.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/prometheus.lua
spec/policy_spec.lua
spec/prometheus_spec.lua

* introduce metrics phase to export metrics
* executor prints collects the response from prometheus
* metrics can be also published from any other phase or timer
See for policy changes and metrics examples:
https://github.com/3scale/apicast-cloud-hosted/pull/5

[prometheus] exporter prototype

---

Makefile

run `.t` files from `t` and `examples` folders
useful for example policies like https://github.com/3scale/apicast/pull/561

[make] run .t files in examples folder

---

.gitignore

`make dev` causes the creation of `.bash_history` and `.cache/`. No need for them in repo.

Adding .cache dir and .bash_history files to gitignore

---

CHANGELOG.md
examples/policies/token_introspection_configuration.lua
gateway/src/apicast/policy/token_introspection/apicast-policy.json
gateway/src/apicast/policy/token_introspection/init.lua
gateway/src/apicast/policy/token_introspection/token_introspection.lua
spec/policy/token_introspection/token_introspection_spec.lua
t/apicast-policy-token-introspection.t

Hi team,
I created a new policy to enable [RFC7662 OAuth2.0 Token Introspection](https://tools.ietf.org/html/rfc7662).
This PR is a rework of the previous request (https://github.com/3scale/apicast/pull/435) as a policy.
And Also added sample configuration in the `examples/policies` directory.

Add token introspection feature as a policy.

---

CHANGELOG.md
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua
spec/policy/url_rewriting/url_rewriting_spec.lua
t/apicast-policy-url-rewriting.t

This PR fixes a bug in the URL rewriting policy.
The problem was that there was a `commands` attribute specified in the policy manifest, but we did not include it in the configuration used in the busted tests nor the integration tests. The policy ignored this attribute and that's why the tests were passing. This suggests that we need to validate configs against manifests when instantiating policies. I'm working on that and will open a new PR once it's ready.
Ref: https://issues.jboss.org/browse/THREESCALE-731

Fix bug in URL rewriting policy that makes it ignore a field of its own manifest [THREESCALE-731]

---

spec/policy/token_introspection/token_introspection_spec.lua

This PR fixes a minor issue in the specs of the token introspection policy.
The policy config schema does not define a 'client' property, so it cannot be passed in the 'config' param when initializing the policy.
cc @tmogi001

Token instrospection specs: make configuration conform with policy config schema

---

spec/policy/cors/cors_spec.lua
spec/policy/url_rewriting/url_rewriting_spec.lua

This PR fixes a couple of policy configs in the specs that are not valid according to the configuration schema of the policy.
I found those errors using this WIP branch: https://github.com/3scale/apicast/tree/validate-policy-configs

Make sure all the policy configs used in specs are valid

---

CHANGELOG.md
Makefile
gateway/src/resty/resolver.lua
spec/resty/resolver_spec.lua
t/resolver.t

Corrects parsing `search local.domain #foobar` in #630

Fix resolv.conf search parsing

---

CHANGELOG.md
gateway/Roverfile
gateway/Roverfile.lock
gateway/src/apicast/policy/caching/apicast-policy.json
gateway/src/apicast/policy/caching/caching.lua
gateway/src/apicast/policy/cors/cors.lua
gateway/src/apicast/policy/echo/apicast-policy.json
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/headers/headers.lua
gateway/src/apicast/policy/token_introspection/token_introspection.lua
gateway/src/apicast/policy/url_rewriting/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua
gateway/src/apicast/policy_config_validator.lua
gateway/src/apicast/policy_loader.lua
spec/policy/caching/caching_spec.lua
spec/policy_config_validator_spec.lua
spec/spec_helper.lua
t/apicast-policy-invalid-config.t
t/fixtures/policies/example_policy/1.0.0/apicast-policy.json
t/fixtures/policies/example_policy/1.0.0/example_policy.lua
t/fixtures/policies/example_policy/1.0.0/init.lua

This PR introduces a way to validate a policy's configuration against the JSON schema defined for its configuration.
This is what I used to detect the problems in our tests fixed in previous PRs: #641 , #644 , #645 
We need to define and agree on a few things before this becomes mergeable. That's why I tagged it as WIP:
* I used `rapidjson` to perform the validation, and it needs cmake. This means that it should be installed on the base image.
* `rapidjson` uses the draft04 version of the JSON schema. I needed to replace the `const`s in our schemas so it works correctly as `const` was introduced in newer versions.
* I needed to instantiate policies using the same name and version used by the policy loaded to find the manifests easily.
* I think this feature should be opt-in via ENV and …

Validation for policy configurations

---

Dockerfile-development
README.md
script/test

The problem was that when mounting the volume, ./lua_modules was used instead of the one generated inside the container.
To solve the issue, lua_modules is moved to a tmp directory when building the container and we make sure to use it when running the tests in `script/test`.

Dockerized dev env: ensure correct dependencies are used

---

doc/parameters.md

The description of the path-based routing was incorrect, as the matching is performed not only by path, but **also** by host.

[doc] clarify how path routing works

---

CHANGELOG.md
examples/policies/ngx-example/1.0.0/apicast-policy.json
gateway/src/apicast/policy/manifest-schema.json
gateway/src/apicast/policy/token_introspection/apicast-policy.json
t/fixtures/policies/example_policy/1.0.0/apicast-policy.json
t/fixtures/policies_endpoint_test/policies/example1/1.0.0/apicast-policy.json
t/fixtures/policies_endpoint_test/policies/example2/1.0.0/apicast-policy.json

This PR makes summary mandatory in the policy manifests.
The reason is that users of the UI might be confused if they see a blank space in the list of policies instead of a summary.

Require summary in policy manifests and add it to the ones that do not have one

---

CHANGELOG.md
gateway/Roverfile.lock
gateway/config/staging.lua
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/configuration_loader.lua
spec/configuration_loader_spec.lua
t/configuration-loading-boot-staging.t

APIcast crashes when it starts with:
```
THREESCALE_DEPLOYMENT_ENV: staging
APICAST_CONFIGURATION_LOADER: boot
APICAST_CONFIGURATION_CACHE: ''
```
Error msg:
```
[lua] configuration_loader.lua:139: init(): cache is off, cannot store configuration, exiting
```
This is because by default, the staging deployment env sets `configuration_cache` to 0, which is incompatible with the 'boot' mode. This PR solves the issue by avoiding setting that default.
Ref: https://issues.jboss.org/browse/THREESCALE-756

Allow setting cache loader = boot on staging and never reload the config [THREESCALE-756] 

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua

This is Keycloak specific. It verifies 'typ' included in the token payload only when it's present.
Closes https://github.com/3scale/apicast/issues/643

OIDC: verify typ is Bearer when included

---

CHANGELOG.md
gateway/src/apicast/policy_loader.lua

The validation is enabled only in testing and the validator relies on a rock that is marked as a 'testing' dependency. That means we need to require the validator only when the option is enabled, otherwise, it will
crash because of a missing dependency.

Require 'ljsonschema' only when the validation of schemas is enabled

---

CHANGELOG.md
gateway/src/apicast/policy/caching/apicast-policy.json
gateway/src/apicast/policy/echo/apicast-policy.json
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/apicast-policy.json

This is a change proposed by @ddcesare 
The reason is that the library used in the UI to render policy configs does not show descriptions, but it shows titles.
From an APIcast point of view I don't see a difference, so I think this should be OK.

policy manifests: replace descriptions with titles in OneOfs

---

.circleci/config.yml
Makefile

reuse already published image of the same branch for the incremental build
saves about a minute when the image is reused

[circleci] enable incremental build of the builder image

---

CHANGELOG.md
gateway/src/apicast/policy/cors/apicast-policy.json
gateway/src/apicast/policy/upstream/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/apicast-policy.json

Some policies only work properly when placed before or after the Apicast policy. Others have a different behavior depending on their position with respect to Apicast in the chain.
For the policies affected, this PR adds a clarification in the description of their schemas.
Ref: https://issues.jboss.org/browse/THREESCALE-799

[THREESCALE-799] policy: document in schemas when the order in the chain matters

---

CHANGELOG.md
gateway/src/apicast/policy/local_chain/local_chain.lua
spec/policy/local_chain/local_chain_spec.lua

Fix bug in export() applied to policies in the local chain

---

CHANGELOG.md
gateway/src/apicast/policy/caching/caching.lua
spec/policy/caching/caching_spec.lua
t/apicast-policy-caching.t

Make caching policy work correctly when placed after apicast in the chain

---

examples/policies/rate_limit_configuration.lua
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

This PR improves the rate limit policy according to the comments of [PR #648](https://github.com/3scale/apicast/pull/648).

Improve rate limit policy

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_store.lua
spec/configuration_loader_spec.lua
spec/configuration_store_spec.lua

It's not possible to use `APICAST_CONFIGURATION_LOADER=lazy` and never refresh the configuration. This PR solves the issue by allowing setting negatives values in `APICAST_CONFIGURATION_CACHE`.

Add option to never reload configuration when configuration loader is lazy

---

CHANGELOG.md
gateway/src/apicast/balancer.lua
gateway/src/apicast/policy/token_introspection/token_introspection.lua
gateway/src/resty/balancer.lua
spec/balancer_spec.lua
t/apicast-upstream-balancer.t

An alternative (and a more generic) way to solve the issue with the upstream policy: https://github.com/3scale/apicast/pull/647

[balancer] Don't force 80 to be the default if port is not provided

---

doc/policies.md

This PR adds an example in the policies doc that illustrates how the order of policies in the policy chain can modify their behavior.

doc/policies: add example with order in the chain

---

gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/token_introspection/apicast-policy.json

A minor change proposed by @thomasmaas
This makes the title of the policy look nicer in the UI and more consistent with the rest of policies.

Fix title of the token introspection and the rate limit policies in their manifests

---

spec/spec_helper.lua

Validation of policy config schemas in busted tests was not working correctly because the ENV that controls that was not set correctly.
Even though the validation was not working correctly, there were not any invalid configs. Not sure when this broke.

Fix validation of policy configs in busted tests

---

CHANGELOG.md
gateway/src/apicast/policy/echo/apicast-policy.json
spec/policy/echo/echo_spec.lua

The code was assuming that valid values for `exit` were `request` and `set`. However, valid values according to the schema are `request` and `set`. The latter was changed in the schema by mistake.

Fix incorrect param value in the Echo policy

---

docker-compose-devel.yml
script/test

Busted tests are failing in the dockerized development environment.
The reason is that the unit tests of the rate limit policy use `TEST_NGINX_REDIS_HOST`, which was only set in `script/test` when running the `Test::Nginx` tests.
This PR simply sets that env when running busted tests.

script/test: set redis host when running busted tests

---

.dockerignore
Dockerfile-development
Makefile

```shell
make development OPENRESTY_VERSION=tag
```
* automatically pull latest s2i-openresty version
* few performance enhancements of building the docker image
This seems to be an issue with my local folder, but `git clean -f -x -d` fixed it.

[dev] start development from any s2i-openresty version

---

CHANGELOG.md
gateway/src/apicast/policy/caching/apicast-policy.json

This PR defines a default for the caching mode in the config schema of the caching policy.
This does not change the behavior of the policy. It just documents explicitly the default caching mode so it can be shown in the UI.
Ref: https://issues.jboss.org/browse/THREESCALE-845
/cc @thomasmaas

[THREESCALE-845] ] Caching policy: specify "none" as default mode in schema

---

CHANGELOG.md
doc/policies.md
gateway/src/apicast/policy/upstream/apicast-policy.json
gateway/src/apicast/policy/upstream/upstream.lua
spec/policy/upstream/upstream_spec.lua
t/apicast-policy-upstream.t

This PR solves the same problem that #689 solves but in a different way.
This PR modifies the Upstream policy so the matching of rules is done in the rewrite phase instead of the content one. This allows us to combine this policy with the URL rewriting one. Before this change, the upstream policy ran on the content phase, whereas the URL rewriting one ran on the rewrite phase. This means that the upstream policy always took into account the rewritten path instead of the original one, regardless of the position of the policies in the chain.
I opened a new PR instead of fixing the previous one because I think @nmasse-itix might need it until we merge this.
Ref: https://issues.jboss.org/browse/THREESCALE-852

[THREESCALE-852] Split upstream policy phases so it can match the original path

---

gateway/.s2i/bin/assemble

`master` images expire after 7 days in quay. This PR solves the issue.

.s2i/bin/assemble: do not add expiry time to master images

---

CHANGELOG.md
Makefile
doc/policies.md
examples/scaffold/policy/gateway/src/apicast/policy/{{policy.file}}/apicast-policy.json
examples/scaffold/policy/gateway/src/apicast/policy/{{policy.file}}/init.lua
examples/scaffold/policy/gateway/src/apicast/policy/{{policy.file}}/{{policy.file}}.lua
examples/scaffold/policy/spec/policy/{{policy.name}}/{{policy.name}}_spec.lua
examples/scaffold/policy/t/apicast-policy-{{policy.file}}.t
gateway/bin/apicast
gateway/src/apicast/cli.lua
gateway/src/apicast/cli/command/generate.lua
gateway/src/apicast/cli/command/generate/policy.lua
gateway/src/apicast/cli/command/start.lua

The idea is to replace the need to copy-paste with scaffolding.
```shell
$ bin/apicast generate policy somename -f
source: /Users/mikz/Developer/3scale/apicast/examples/scaffold/policy
destination: /Users/mikz/Developer/3scale/apicast
created: spec
created: spec/policy
created: spec/policy/somename
created: spec/policy/somename/somename_spec.lua
created: t
created: t/apicast-policy-somename.t
created: gateway
created: gateway/src
created: gateway/src/apicast
created: gateway/src/apicast/policy
created: gateway/src/apicast/policy/somename
created: gateway/src/apicast/policy/somename/apicast-policy.json
created: gateway/src/apicast/policy/somename/init.lua
created: gateway/src/apicast/policy/somename/somename.lua
```

[cli] generate command to create scaffolding

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
gateway/src/apicast/backend_client.lua
gateway/src/apicast/errors.lua
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/README.md
gateway/src/apicast/policy/3scale_batcher/apicast-policy.json
gateway/src/apicast/policy/3scale_batcher/auths_cache.lua
gateway/src/apicast/policy/3scale_batcher/init.lua
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
gateway/src/apicast/policy/3scale_batcher/reporter.lua
gateway/src/apicast/policy/3scale_batcher/reports_batch.lua
gateway/src/apicast/policy/3scale_batcher/reports_batcher.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/proxy.lua
spec/backend_client_spec.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/3scale_batcher/auths_cache_spec.lua
spec/policy/3scale_batcher/keys_helper_spec.lua
spec/policy/3scale_batcher/reporter_spec.lua
spec/policy/3scale_batcher/reports_batch_spec.lua
spec/policy/3scale_batcher/reports_batcher_spec.lua
t/apicast-policy-3scale-batcher.t

This PR introduces a new policy. Its goal is to reduce latency and increase throughput by significantly reducing the number of requests made to the 3scale backend. In order to achieve that, this policy caches authorization statuses and batches reports. In order to achieve that, it makes some trade-offs regarding rate-limits accuracy. I've tried to document everything in the README included in this PR.
I've tagged this as WIP because there are some things that need to be fixed. I've documented them in a TODO section included in the first lines of the new policy module. I decided to open the PR because I'd appreciate some early feedback, @mikz 
I need to perform more tests to check that the policy is indeed fast and correct, but my first tests are really promising. The performance of the …

3scale batcher policy

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

The rate limit policy has a valid configuration JSON schema. However, it cannot be rendered by `react-jsonschema-form` the library used in the 3scale UI to build HTML forms from the config schemas. 
This PR solves the issue by adapting the schema. The library cannot render arrays of objects with different types, so I've split them into several arrays that have items of only one type. In particular, the properties causing issues in the UI library were `limiters` and `error_settings`.
This is a breaking change, but not between final versions. If you were using this policy in a previous release candidate or beta, your configuration will become invalid.
Ref: https://github.com/3scale/apicast/issues/695

Adapt rate limit config schema to make it compatible with react-jsonschema-form

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/reports_batcher.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
t/apicast-policy-3scale-batcher.t

This PR fixes a bug in the 3scale batching policy. It didn't assign the batching period according to the given configuration.
While at it, this PR also adds some debugging logs and tests that helped to detect this issue.

3scale batching policy: fix batching period assignment from config

---

spec/backend_client_spec.lua

The tests failed sometimes because of some missing `it` clauses.
This was the error:
```
attempt to index upvalue 'test_backend'
```
These tests were order-dependent. Sometimes they ran before the `before_each` clause because of the missing `it`s.

Fix flaky tests in the backend client

---

CHANGELOG.md
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/headers/headers.lua
gateway/src/apicast/template_string.lua
spec/policy/headers/headers_spec.lua
spec/template_string_spec.lua
t/apicast-policy-headers.t

Headers policy: allow templating using liquid

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
gateway/src/apicast/proxy.lua
spec/oauth/oidc_spec.lua
t/apicast-policy-headers.t

This PR exposes jwt in the policies context in OAuth flows.
This is useful because it allows other policies to access those tokens. For example, the rate-limit policy ( #713 ) could benefit from this.
This PR also adds an integration test that uses OAuth and the headers policy and shows how it can set some headers with information extracted from the decoded jwt.

Expose jwt in the policies context

---

gateway/src/apicast/policy/3scale_batcher/reports_batcher.lua

Minor change. This PR just adds a missing log level error in a `ngx.log()` call. It's important because it's a `ngx.ERR` and we want to see it in the logs when it happens.

policy/3scale_batcher: add missing log error level

---

doc/policies.md

Minor fix. The example JSON in the policies doc contained a trailing comma which is not accepted by the JSON standard.

Fix example JSON config in the policies doc

---

.circleci/config.yml
Makefile
bin/busted.lua
gateway/Roverfile
gateway/Roverfile.lock

Unfortunately it makes busted build about 7x slower. (from 7s to 48s).
There will be more reports when master gets build with coverage, but for now there is a proof it actually measures stuff: https://codecov.io/gh/3scale/apicast/tree/36c56a6868a69020145862f7aa10f14d6ff62c6f/gateway/src/apicast

[ci] report unit test code coverage

---

examples/add-ssl/README.md
examples/add-ssl/apicast.d/ssl.conf

**Motivation**
Following the current instructions in the README results in the following error.
```
nginx: [emerg] BIO_new_file("/tmp/cert/server.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/tmp/cert/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
Also included `-e THREESCALE_DEPLOYMENT_ENV=staging` in example usage as production loads the config via `boot` and will fail as  https://git.io/vXHTA/admin/api/services.json will 404.

Fixing add-SSL example to work with example in README

---

.codecov.yml

Disable comments, so we have "quiet" period when we get the 
code coverage numbers.
Set default branch to master. Codecov thinks it is v2.

[codecov] configure codecov

---

CHANGELOG.md
gateway/src/apicast/policy/url_rewriting/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/query_params.lua
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua
spec/policy/url_rewriting/query_params_spec.lua
spec/policy/url_rewriting/url_rewriting_spec.lua
t/apicast-policy-url-rewriting.t

This PR implements part of #711 
It adds the ability to modify query parameters in the URL rewriting policy.

URL rewriting policy: Allow to modify query parameters

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_referrer/3scale_referrer.lua
gateway/src/apicast/policy/3scale_referrer/apicast-policy.json
gateway/src/apicast/policy/3scale_referrer/init.lua
gateway/src/apicast/proxy.lua
spec/policy/3scale_referrer/3scale_referrer_spec.lua
t/apicast-policy-3scale-referrer.t

Add 3scale referrer policy

---

benchmark/ips.lua
benchmark/regexpify.lua
benchmark/template.lua

```
Warming up --------------------------------------
ffi
708409 i/100ms
syscall
593019 i/100ms
Calculating -------------------------------------
11385724.4 (±1.9%) i/s -   57381129 in   5.041731s
10427682.8 (±1.0%) i/s -   52185672 in   5.005021s
```
It ports awesome https://github.com/evanphx/benchmark-ips to Lua.
The idea is that we have clear benchmarks for some constructs that can show performance difference.
I could see some LuaJIT features like turning off JIT for some functions to see the impact of JIT on performance. 
You can see benchmark results in https://github.com/3scale/apicast/pull/714#discussion_r188866775

lua port of benchmark-ips

---

Dockerfile-development

Improve reproducibility and repeatability on development image not upgrading existing base image packages.
Base image ( quay.io/3scale/s2i-openresty-centos7:1.13.6.1-rover12 ) has installed
```
openresty-openssl-1.0.2k-1.el7.centos.x86_64
```
After
```
yum update
```
installed package was
```
openresty-openssl-1.1.0h-3.el7.centos.x86_64
```
which broke compatibility with used openresty package, specifically when using *jwt* resty module.
This effect may happen again when new packages are available in remote repositories unless upgrading step is avoided.

Do not upgrade base image installed packages on development Dockerfile

---

CHANGELOG.md
gateway/src/apicast/policy/ngx_variable.lua
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

Rate Limit policy: allow templating using liquid

---

CHANGELOG.md
gateway/src/apicast/policy/default_credentials/apicast-policy.json
gateway/src/apicast/policy/default_credentials/default_credentials.lua
gateway/src/apicast/policy/default_credentials/init.lua
gateway/src/apicast/proxy.lua
spec/policy/default_credentials/default_credentials_spec.lua
t/apicast-policy-default-credentials.t

[THREESCALE-586] Default credentials policy

---

doc/parameters.md

Properly document deprecated and experimental features environment variables.
/cc @mayorova @3scale/documentation

[doc] document deprecated environment variables

---

gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/auths_cache.lua
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
gateway/src/apicast/policy/3scale_batcher/reports_batcher.lua
gateway/src/apicast/policy/3scale_batcher/transaction.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/3scale_batcher/auths_cache_spec.lua
spec/policy/3scale_batcher/keys_helper_spec.lua
spec/policy/3scale_batcher/reports_batcher_spec.lua

Refactoring.
In many parts of the code of the policy, these 3 attributes are used together: `service_id`, `credentials`, `usage`. Those 3 are the information that APIcast sends to the 3scale backend to know whether a call should be authorized. This PR creates a new Transaction module that groups those attributes.
This refactoring will make it easier to implement #738

[Refactor] 3scale batching policy: extract Transaction module

---

.circleci/config.yml

The `deploy` task in CircleCI fails in PRs opened from forks. The reason is that this task tries to push docker images to our registry and the docker credentials are not available in PRs from forks.
This PR solves the issue by skipping the `push` instruction when the credentials are not set.

CircleCI: Don't try to push docker images in PRs from forks

---

.circleci/config.yml

codecov failed in https://circleci.com/gh/3scale/apicast/9097
```
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
```

[circleci] allow codecov to fail

---

Brewfile
README.md

Simplify install instructions on macOS by defining everything in Brewfile and suggesting `brew bundle`.
We have homebrew tap with OpenResty+OpenTracing: https://github.com/3scale/homebrew-opentracing

[brew] install OpenResty with OpenTracing support

---

.github/CODEOWNERS

So we don't notify everyone on every PR, but just the core team.

[github] change owner to core team

---

gateway/src/apicast/policy/caching/apicast-policy.json

Since we can see only the title of the caching mode in the Admin Portal and the title makes a little confusion, this PR modifies it.
- the order of the caching mode will match the policy description
- the name of the mode will be included in the title

Caching policy to improve the description of the Caching Mode.

---

.circleci/config.yml
CHANGELOG.md
Makefile
gateway/Roverfile.lock
gateway/src/apicast/management.lua

Upgrade OpenResty to 1.13.6.2. See the changelog: http://openresty.org/en/changelog-1013006.html
Major change is OpenSSL 1.1, so some FFI code needed to be changed: (https://github.com/cdbattags/lua-resty-jwt/pull/4)
using https://github.com/3scale/s2i-openresty/pull/58

OpenResty 1.13.6.2

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
t/apicast-policy-3scale-batcher.t

Make 3scale batching policy compatible with the caching policy

---

CHANGELOG.md
gateway/src/apicast/mapping_rule.lua
spec/mapping_rule_spec.lua

Some valid paths are not supported by the mapping rules matcher:
Mapping rule: `/api/{email}/whatever` is supposed to match `/api/me@email.com/whatever`, but instead APIcast returns `No Mapping Rules Matched`.
I'm not sure if all special characters listed in https://tools.ietf.org/html/rfc3986#section-3.3 should be used though, as it seems that some are not accepted by nginx itself...

Support special characters for mapping rule wildcards in url path

---

CHANGELOG.md
examples/policies/token_introspection_configuration.lua
gateway/src/apicast/policy/token_introspection/apicast-policy.json
gateway/src/apicast/policy/token_introspection/token_introspection.lua
spec/policy/token_introspection/token_introspection_spec.lua
t/apicast-policy-token-introspection.t

Since it is troublesome to define the `client_id` and `client_secret` twice in the `AUTHENTICATION SETTINGS` and in the `POLICIES` of the Admin Portal, this PR adds "use_oidc_issuer_endpoint" property to get client information from `oidc_issuer_endpoint`.

Token Introspection Policy to get client information from "oidc_issuer_endpoint".

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

This PR addresses to Issue #667.

Rate Limit policy to take into account changes in the config

---

spec/policy/url_rewriting/url_rewriting_spec.lua

use stubs that are reset after the test
so the tests can be executed with `--no-auto-insulate`.

[spec] fix leaking url rewriting spec

---

openshift/apicast-template.yml

Also this makes it closer to the [productized template](https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.2.0.GA/apicast-gateway/apicast.yml).

Remove some deprecated parameters and add a few extra

---

gateway/src/resty/limit/count-inc.lua
spec/policy/rate_limit/rate_limit_spec.lua

* count-int wasn't counting with failures
Fixing rather cryptic:
```
...ast/gateway/src/apicast/policy/rate_limit/rate_limit.lua:88: bad argument #1 to '?' (table expected, got nil)
...ast/gateway/src/apicast/policy/rate_limit/rate_limit.lua:88: in function 'build_limiters_and_keys'
```

[rate-limit] fix failure when shdict is missing

---

gateway/src/apicast/loader.lua
spec/spec_helper.lua

Busted uses automatic insulation and clears `_G` and `package.loaded` between test files.
However, `apicast.loader` added itself to `package.searchers` and stayed active including its own upvalues.
So all policies loaded using `apicast.loader` used different packages than everyone else.
The solution is to make `apicast.loader` to clean up after itself when it is garbage collected.

[busted] reload apicast.loader to prevent caching policies between tests

---

CHANGELOG.md
examples/custom-module/blacklist.lua
gateway/src/apicast/executor.lua
gateway/src/apicast/policy/load_configuration/load_configuration.lua
gateway/src/apicast/policy_chain.lua
gateway/src/apicast/policy_loader.lua
gateway/src/resty/sandbox.lua
spec/executor_spec.lua
spec/policy_loader_spec.lua
t/apicast-policy-chains.t

During master process boot all available policies are loaded 
and get their `init` and `init_worker` phases executed.
Increases initial memory use by about 800 kB (which is later shared between workers).

init and init_worker phases called on all policies

---

gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/proxy.lua

Extracted from https://github.com/3scale/apicast/pull/774
Refactors `proxy:post_action` to ease changes in #774. Proxy post_action should receive a context and be called from just one point - the policy.

[proxy] refactor post_post action

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
t/apicast-policy-3scale-referrer.t

The referrer policy does not work correctly when the async reporting threads option is enabled (`APICAST_REPORTING_THREADS > 0`)

Make referrer policy compatible with async reporting threads option

---

CHANGELOG.md
gateway/Roverfile.lock
gateway/apicast-scm-1.rockspec
gateway/src/apicast/executor.lua
gateway/src/resty/concurrent/timer_task.lua
spec/resty/concurrent/timer_task_spec.lua

This PR adds a new module that allows running periodic tasks that can be canceled.

Add TimerTask

---

CHANGELOG.md
gateway/src/resty/concurrent/timer_task.lua
spec/resty/concurrent/timer_task_spec.lua

This PR adds an option to run immediately or wait 'interval' seconds in TimerTask.execute.
When scheduling a recurrent job, we might want to delay the first execution 'interval' seconds instead of running it immediately.
This is going to be used in the batching policy when scheduling reports to backend. In that case, we don't need to report immediately, because when scheduling the task, the set of pending reports will be empty.

Add option to run immediately or wait 'interval' second in TimerTask.execute

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
t/apicast-oidc.t

Due to a bug in credentials juggling APIcast would send raw JWT to 3scale backend instead of just app_id.
That token is of course not understood and the reporting call rejected.
The fix changes how credentials are moved around to reduce risk of future issues.
Fixes [THREESCALE-1080](https://issues.jboss.org/browse/THREESCALE-1080)
@3scale/qe you might want to incorporate some tests that test metrics reporting accuracy to catch this kind of issues.

Fix reporting only 50% of calls to 3scale backend [THREESCALE-1080]

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
t/apicast-oidc.t

Fixes [THREESCALE-1080](https://issues.jboss.org/browse/THREESCALE-1080)
Simplified backport of https://github.com/3scale/apicast/pull/774 for 3.2 release.
This simpler backport does not rely or passing `context` object from `post_action` phase to `proxy` object, but rather just updates `proxy.credentials` after they are transformed by `oauth:transform_credentials` method. https://github.com/3scale/apicast/pull/774 relies on not storing the credentials in proxy at all and rather storing them only in the `context` object. 
But for a purpose of a patch release it is better to make minimal changes and reduce risk of unintended changes of behaviour.

[oidc] fix reporting to backend when using OIDC [THREESCALE-1080]

---

examples/add-ssl/README.md
examples/add-ssl/apicast.d/ssl.conf

Use builtin HTTPS functionality instead of a customization.
/cc @3scale/documentation

[example] update add-ssl example

---

CHANGELOG.md
gateway/src/apicast/gc.lua
spec/gc_spec.lua

In LuaJIT and Lua 5.1, the `__gc` metamethod does not work with tables, it only works with "userdata". This PR introduces a module that implements a workaround to make it work with tables.

Workaround to make __gc work on tables

---

CHANGELOG.md
gateway/src/resty/concurrent/timer_task.lua
spec/resty/concurrent/timer_task_spec.lua

This PR implements several improvements in the `TimerTask` module:
1) Adapts the module to use the new `GC` module introduced in the previous PR #790
2) Fixes a bug that prevents the task from being garbage collected. This is done by avoiding passing `self`.
3) Fixes a bug when calculating the delay when scheduling the next task.

TimerTask improvements

---

.codeclimate.yml

Latest release is now in stable channel.
Luacheck finds 56 new failures. We can fix them over time.

[codeclimate] luacheck was released to the stable channel

---

CHANGELOG.md
docker-compose.benchmark.yml
gateway/src/apicast/configuration_loader.lua
gateway/src/apicast/gc.lua
gateway/src/apicast/policy.lua
gateway/src/apicast/policy/echo/echo.lua
script/s2i
spec/policy_spec.lua

This would allow doing cleanup when policies are reloaded by changed configuration (like shutting down timers).

[policy] run __gc metamethod when policies are garbage collected

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/reporter.lua
gateway/src/resty/concurrent/timer_task.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/3scale_batcher/reporter_spec.lua
spec/resty/concurrent/timer_task_spec.lua
t/apicast-policy-3scale-batcher.t

This PR replaces the usages of `ngx.timer.every` with `TimerTask` instances.
This solves the issue of not being able to cancel timers. Recurrent tasks created using `TimerTask` can be canceled, but we cannot cancel timers created with `ngx.timer.every`. This was causing a bug, Timer would continue running even after a config reload.

Use TimerTask in the 3scale batcher policy

---

bin/busted
gateway/src/apicast/configuration_store.lua
spec/configuration_store_spec.lua
spec/luassert_helper.lua
spec/ngx_helper.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/find_service/find_service_spec.lua
spec/policy/rate_limit/rate_limit_spec.lua
spec/proxy_spec.lua
spec/spec_helper.lua

Stubs and global env modifications would leak in between tests.
This PR introduces several protections against that and fixes running the tests in loop without automatic insulation from busted.
```shell
rover exec bin/busted  --repeat=100 --no-auto-insulate
rover exec bin/busted  --repeat=10 # less repetitions, because busted leaks memory
```

[busted] fix leaking tests

---

spec/policy/keycloak_role_check/keycloak_role_check_spec.lua

When running the tests, 'auth failed' is printed several times. This PR fixes the issue:
```
bash-4.2$ make busted
/usr/local/openresty/luajit/bin/rover exec bin/busted 
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●auth failed●auth failed●auth failed●auth failed●auth failed●auth failedauth failed●auth failed●auth failed●auth fail
ed●●●●●●●●●●●●●●●●●●●◌●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●◌●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●● …
```

stub ngx.print in Keycloack scopes policy specs

---

doc/policies.md

This PR updates the policies doc and clarifies the policies available for each type of installation (SaaS, on-premises).

doc/policies: clarify available policies in each installation type

---

spec/resty/concurrent/timer_pool_executor_spec.lua

sometimes tests would timeout, increasing the timeout to 10 seconds
works

[spec] fix random failure in resty.concurrent spec

---

CHANGELOG.md
gateway/.s2i/bin/assemble

Fixes https://issues.jboss.org/browse/THREESCALE-1138.
OpenShift source builder behaves differently from s2i and has different ENV variables.

[s2i] fix unbound variable on OpenShift 3.9 [THREESCALE-1138] 

---

openshift/apicast-template.yml

We can use other container runtimes, not just Docker.
3scale/3scale-amp-openshift-templates#26
Credits: Marcus Carvalho

[openshift] replace "docker" with "container"

---

CHANGELOG.md
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/conditional/conditional.lua
gateway/src/apicast/policy/conditional/engine.lua
gateway/src/apicast/policy/conditional/init.lua
spec/policy/conditional/conditional_spec.lua
spec/policy/conditional/engine_spec.lua
t/apicast-policy-conditional.t

Part of #744 
This implements the conditional policy as discussed in #744 
The conditional engine is very simple and it's not how the final version will look at all. However, I decided to open this PR in case it helps unblock some of the work going on in [ostia](https://github.com/3scale/ostia). 
@mikz let me know if you'd like to have this first version merged soon. Otherwise, I'll start working on a more complex conditional engine (wip branch here: https://github.com/3scale/apicast/tree/lpeg-grammar-condition-engine)

Conditional policy

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
gateway/config/development.lua
gateway/config/production.lua
gateway/src/apicast/linked_list.lua
spec/linked_list_spec.lua

Setting `timer_resolution` in nginx configuration will result in logging ~7 lines every 100ms (or other timer_resolution interval) in debug log. That makes any debugging impossible.
Disabling this in development is reasonable as it is just a performance  optimization for production environment.

[dev] do not set timer_resolution in development mode

---

openshift/apicast-template.yml

When following the [openshift-guide](https://github.com/3scale/apicast/blob/master/doc/openshift-guide.md), running the `oc new-app` command without specifying a log level causes the apicast pods to crash due to invalid config.

Set LOG_LEVEL param to required

---

CHANGELOG.md
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua

Consider the case of 2 requests being attended at the same time by the same worker. Each request could modify the value that the other sees.
As a general rule, in the case of policies, we should only assign "self._something" in new().

policy/url_rewriting: avoid assigning self.something in rewrite()

---

CHANGELOG.md
gateway/src/apicast/policy/ngx_variable.lua
spec/policy/ngx_variable_spec.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-conditional.t

The goal of this PR is to cover the use case mentioned in https://github.com/3scale/apicast/issues/744#issuecomment-407077679
The objective is to be able to combine the conditional policy with the upstream one and be able to choose an upstream based on a request header. In order to do that, I needed to expose the request headers in the `ngx_variable` module. I also added an integration test that checks that it works as expected.

Expose request headers in Liquid available context

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
t/apicast-policy-3scale-batcher.t

The batcher policy was not working correctly when placed after the APIcast policy in the chain.
This PR fixes the issue.

Allow to place the batcher policy after APIcast policy in the chain

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/apicast-policy.json

This is not just a typo. The validation fails because of this.

rate limit policy: fix exclusiveMininum for 'conn' in schema

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

When I define multipul limits using the same type of limiter, 
```json
"fixed_window_limiters" : [
{ "limit 1" },
{ "limit 2" }
]
```
The following error message is displayed.
````
"2018/07/30 17:52:07 [error] 18007\#18007: *1 lua entry thread aborted: runtime error: ...ast/gateway/src/apicast/policy/rate_limit/rate_limit.lua:168: bad argument \#2 to 'insert' (number expected, got table)"
````
I fixed this by removing `table.unpack`.

[rate-limit] Multi limits using the same type of limiter.

---

.circleci/config.yml

We need to make our build less resource intensive, as it is taking a lot
of time in queue now.

[circleci] temporarily disable jobs that are not used

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua

[rate-limit] Use shdict when redis_url is empty in the same way as redis_url is null.

---

gateway/src/resty/resolver.lua
spec/oauth_spec.lua
spec/policy/rate_limit/rate_limit_spec.lua
spec/policy/rate_limit/redis_shdict_spec.lua
spec/resty/resolver/dns_client_spec.lua
t/apicast-oauth.t
t/apicast-policy-rate-limit.t

AKA airplane mode - when there is no network, there is no `/etc/resolv.conf`
All integration tests can be executed without network. Some busted tests require network, but can be skipped: `rover exec bin/busted --exclude-tags=network`.

do not depend on /etc/resolv.conf

---

CHANGELOG.md
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rate_limit/rate_limit.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

Closes the last item of the TODO list in https://github.com/3scale/apicast/issues/760

Add conditions to rate-limit policy

---

CHANGELOG.md
doc/parameters.md
gateway/conf/proxy.conf
gateway/src/apicast/backend_client.lua
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/policy/upstream/upstream.lua
gateway/src/apicast/proxy.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/http/proxy.lua
gateway/src/resty/http_ng/backend/ngx.lua
spec/policy/upstream/upstream_spec.lua
spec/proxy_spec.lua
spec/upstream_spec.lua
t/http-proxy.t

Fixes https://github.com/3scale/apicast/issues/709
Builds on top of https://github.com/3scale/apicast/pull/835
By configuring standard environment variables `http_proxy`, `HTTP_PROXY`, `no_proxy`, `NO_PROXY`, `http_proxy`, `HTTPS_PROXY` you can instruct APIcast to use those instead of direct connection.
Proxy does not support any authentication yet.

[resty.http_ng] use http/s proxy for backend and upstream connections 

---

CHANGELOG.md
gateway/src/apicast/cli.lua
gateway/src/apicast/cli/command/console.lua

start apicast console and optionally execute a file
```shell
$ bin/apicast console
[1] ngx(timer)>
```
```
Usage: bin/apicast console [-h] [<file>]
Start console
Arguments:
file                  file to execute
Options:
-h, --help            Show this help message and exit.
```

[cli] console command

---

CHANGELOG.md
gateway/src/apicast/policy/liquid_context_debug/apicast-policy.json
gateway/src/apicast/policy/liquid_context_debug/context_content.lua
gateway/src/apicast/policy/liquid_context_debug/init.lua
gateway/src/apicast/policy/liquid_context_debug/liquid_context_debug.lua
gateway/src/apicast/policy/ngx_variable.lua
spec/policy/liquid_context_debug/context_content_spec.lua
spec/policy/liquid_context_debug/liquid_context_debug_spec.lua
spec/policy/ngx_variable_spec.lua
t/apicast-policy-liquid-context-debug.t

Liquid context debugging policy

---

CHANGELOG.md
gateway/src/apicast/cli/command/start.lua

Expand the access/error log paths to absolue paths from the current directory.
Fixes https://issues.jboss.org/browse/THREESCALE-1090

[cli] fix relative access/error log paths [THREESCALE-1090]

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
gateway/src/apicast/policy/logging/apicast-policy.json
gateway/src/apicast/policy/logging/init.lua
gateway/src/apicast/policy/logging/logging.lua
spec/policy/logging/logging_spec.lua
t/apicast-policy-logging.t

Allows enabling/disabling access logs per service, so addresses #712 partially.

Logging policy

---

gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/policy/phase_logger/phase_logger.lua
t/apicast-syslog.t

Part of https://github.com/3scale/apicast/issues/712
Fixes issue introduced by https://github.com/3scale/apicast/pull/857
Log path starting with `syslog:` or `memory:` is not relative path, but
has to be passed to nginx unchanged.
For how to configure syslog see nginx documentation: http://nginx.org/en/docs/syslog.html

[cli] fix logging to syslog

---

gateway/src/resty/http_ng/headers.lua
gateway/src/resty/http_ng/request.lua

Try to apply some smaller and bigger optimizations to improve overral performance of the client.
see profiles: https://gist.github.com/mikz/e8d29fcb60374cff1174930658da694c
```
wrk --connections 10 --threads 10 --duration 60 'http://localhost:8080/?user_key=foo'
Running 1m test @ http://localhost:8080/?user_key=foo
10 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     6.15ms    1.86ms  28.68ms   82.61%
Req/Sec   163.82     22.43   373.00     71.98%
98004 requests in 1.00m, 35.61MB read
Requests/sec:   1630.88
Transfer/sec:    606.72KB
```
```
wrk --connections 10 --threads 10 --duration 60 'http://localhost:8080/?user_key=foo'
Running 1m test @ http://localhost:8080/?user_key=foo
10 threads and 10 connections
Thread Stats   Avg      Stdev     Max …
```

[http_ng] improve performance

---

CHANGELOG.md
gateway/config/production.lua
gateway/config/staging.lua
gateway/http.d/lua_capture_error_log.conf
gateway/src/apicast/backend_client.lua
gateway/src/apicast/metrics/3scale_backend_status.lua
gateway/src/apicast/metrics/updater.lua
gateway/src/apicast/policy/nginx_metrics/init.lua
gateway/src/apicast/policy/nginx_metrics/nginx_metrics.lua
gateway/src/apicast/policy_chain.lua
t/fixtures/configs/without_nginx_metrics.lua
t/prometheus-metrics.t

Closes (partially) #745 
This is an initial version with a reduced number of metrics. For now, it includes:
- 3scale backend response status codes.
- connections (accepted, active, handled, reading, total, waiting, writing).
- nginx errors.
- capacity of every shared dictionary.
- free space of every shared dictionary.
This is an example output:
```
backend_response{status="2xx"} 1
nginx_http_connections{state="accepted"} 3
nginx_http_connections{state="active"} 1
nginx_http_connections{state="handled"} 3
nginx_http_connections{state="reading"} 0
nginx_http_connections{state="total"} 3
nginx_http_connections{state="waiting"} 0
nginx_http_connections{state="writing"} 1
nginx_metric_errors_total 0
openresty_shdict_capacity{dict="api_keys"} 10485760 …
```

Metrics policy

---

CHANGELOG.md
gateway/src/apicast/policy/apicast/apicast-policy.json
gateway/src/apicast/policy/caching/apicast-policy.json
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/default_credentials/apicast-policy.json
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/keycloak_role_check/apicast-policy.json
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rewrite_url_captures/apicast-policy.json

Changes the display name of some policies as per @MarkCheshire 's suggestions.
Notice that this does not break compatibility. It only affects how the name is shown in the UI.
Ref: https://issues.jboss.org/browse/THREESCALE-1232

Change the display name of some policies

---

CHANGELOG.md
gateway/src/apicast/cli/filesystem.lua

When the directory is not accessible, instead of crash like:
```
lua coroutine: runtime error: /opt/app-root/src/src/apicast/cli/filesystem.lua:50: attempt to call a nil value
```
Get a debug log like:
```
/usr/local/share/lua/5.1/lfs.lua:513: cannot open /usr/local/openresty/nginx/fastcgi_temp : Permission denied
```

[cli] do not crash when listing unaccessible directories

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua
t/apicast-oidc.t
t/apicast-policy-headers.t
t/apicast-policy-keycloak-role-check.t
t/apicast-policy-rate-limit.t
t/apicast-policy-token-introspection.t

https://tools.ietf.org/html/rfc7523#section-3
So for example, `nbf` is not required. Neither is `iat`. On the other hand `sub` claim is required now.
Discovered in https://issues.jboss.org/browse/THREESCALE-583?focusedCommentId=13627302&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13627302

[oidc] JWT validation according to the RFC 7523

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/oidc.lua
gateway/src/apicast/configuration_loader/remote_v2.lua
gateway/src/resty/oidc/discovery.lua
spec/configuration_loader/oidc_spec.lua
spec/configuration_loader/remote_v2_spec.lua

So later when the token is verified it can be an exact match.
Before the URL could be different due to some reverse proxies or
credentials embedded in the URL.
/cc @mayorova

[oidc] always get issuer/iss from the OIDC Discovery endpoint

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
spec/proxy_spec.lua
t/apicast-policy-3scale-referrer.t

Take referrer filters into account in the auths cache

---

gateway/src/apicast/policy/token_introspection/token_introspection.lua
t/apicast-policy-token-introspection.t

This is to facilitate troubleshooting when you get a "Authentication failed" with Token Introspection policy enabled.

Add a log message when token introspection finds that the token is not active

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/remote_v2.lua
t/configuration-loading-boot-remote.t

APIcast crashes when loading a config where only some of the services use OIDC.
The reason is that we create an array of OIDC configs that has size=number_of_services. Depending on the number of services and the number of services that use OIDC, we might create a sparse array. cjson raises an error when trying to convert a sparse array. Check
https://www.kyne.com.au/~mark/software/lua-cjson-manual.html#encode_sparse_array
for more details.
This PR solves the issue by assigning elements of that array to false instead of nil to avoid creating sparse arrays.
Ref: https://issues.jboss.org/browse/THREESCALE-1289

Fix error when loading a config with only some services using OIDC

---

gateway/src/apicast/policy/3scale_referrer/apicast-policy.json
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/default_credentials/apicast-policy.json
gateway/src/apicast/policy/logging/apicast-policy.json
gateway/src/apicast/policy/rewrite_url_captures/apicast-policy.json

2 minor changes:
- Make sure all the summaries end with a '.'. Just for consistency in the UI.
- Clarify that the conditional policy cannot be configured in the UI.

Improve policy descriptions

---

CHANGELOG.md
gateway/src/resty/limit/count-inc.lua
spec/policy/rate_limit/rate_limit_spec.lua
spec/resty/limit/count-inc_spec.lua

[count-inc] Add decrement logic to the incoming function

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/metrics.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
t/prometheus-metrics.t

This PR adds a couple of metrics for the 3scale batching policy:
```
batching_policy_auths_cache_hits 2
batching_policy_auths_cache_misses 1
```
Part of #745

Add Prometheus metrics for the 3scale batching policy

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/http_ng/backend/ngx.lua
spec/upstream_spec.lua
t/apicast-blackbox.t
t/apicast-caching.t
t/apicast-path-routing.t
t/apicast-policy-upstream.t
t/http-proxy.t

Route traffic to that path + current url.
Closes https://github.com/3scale/apicast/issues/903

[upstream] support path in the upstream url

---

CHANGELOG.md
gateway/src/apicast/configuration/service.lua
gateway/src/apicast/errors.lua
gateway/src/apicast/oauth/oidc.lua
gateway/src/apicast/policy/oidc_authentication/init.lua
gateway/src/apicast/policy/oidc_authentication/oidc_authentication.lua
gateway/src/apicast/proxy.lua
gateway/src/resty/http_ng.lua
spec/ngx_helper.lua
spec/oauth/oidc_spec.lua
spec/policy/oidc_authentication/oidc_authentication_spec.lua
spec/resty/http_ng_spec.lua
spec/spec_helper.lua
t/apicast-policy-oidc_authentication.t

We would like to use OIDC without 3scale, so we need a standalone OIDC policy for authentication.
Requirement for https://github.com/3scale/ostia/issues/14
/cc @3scale/ostia

Expose OIDC as standalone policy

---

CHANGELOG.md
gateway/src/apicast/metrics/3scale_backend_status.lua
t/prometheus-metrics.t

To clearly distinguish it from the upstream API as suggested in https://github.com/3scale/apicast/issues/745#issuecomment-419365339

metrics: rename backend_response to threescale_backend_response

---

CHANGELOG.md
gateway/src/apicast/metrics/upstream.lua
gateway/src/apicast/policy/nginx_metrics/nginx_metrics.lua
spec/metrics/upstream_spec.lua
t/prometheus-metrics.t

Add Prometheus metrics for the upstream

---

doc/parameters.md

Disabling reloading using negative values was added in https://github.com/3scale/apicast/pull/657
Limitation of >60 was removed here: https://github.com/3scale/apicast/commit/8fce45bbd1a279c000050d70e999e9dd1f7cb946#diff-529f8e34faaeb281c7524f21019e36e3L16

Fix and clarify the description of APICAST_CONFIGURATION_CACHE

---

CHANGELOG.md
gateway/conf.d/apicast.conf
t/mutual-ssl.t

Starting APIcast with `APICAST_PROXY_HTTPS_PASSWORD_FILE` was failing with:
~~~
nginx: [emerg] invalid number of arguments in "proxy_ssl_password_file" directive in /tmp/lua_At34WX:455
~~~
Apparently, it's because of the missing `;` in the end of the directive.
The same for `proxy_ssl_session_reuse`, although I didn't really try it.

Add missing semicolon in proxy SSL settings

---

CHANGELOG.md
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/headers/headers.lua
spec/policy/headers/headers_spec.lua
t/apicast-policy-headers.t

Delete operation in headers policy

---

CHANGELOG.md
gateway/src/apicast/backend_client.lua
gateway/src/apicast/errors.lua
gateway/src/apicast/proxy.lua
spec/backend_client_spec.lua
spec/errors_spec.lua
spec/proxy_spec.lua
t/apicast.t

Part of #335 
This PR introduces a "Retry-After" header in the APIcast response.
When rate-limited by the 3scale backend, APIcast returns the number of seconds that the caller needs to wait before it's authorized again in the "Retry-After" header.

Add "Retry-After" header

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
spec/proxy_spec.lua
t/apicast-policy-caching.t

The behavior of the "allow" mode is a bit counterintuitive.
The issue is that when a request is not cached, APIcast returns an authentication failed error. Subsequent requests are cached and are authorized. We'd expect the policy to accept the non-cached request too.
This PR fixes the issue.
For more information: https://issues.jboss.org/browse/THREESCALE-1396

[THREESCALE-1396] Fix "allow" mode of the caching policy

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/policy/find_service/find_service.lua

This is a supported feature since `3.2.1`

Remove 'experimental' label from path routing

---

CHANGELOG.md
gateway/src/apicast/executor.lua
gateway/src/apicast/policy_chain.lua

This has been done to improve performance by making more code jittable.
The problem is that varags (...) cannot be compiled. The executor and the policy chain do not need varargs anyway because the policies accept just one parameter, the context, in their phases.
I ran some basic tests. Absolute numbers are not important, let's focus on percentages.
Configuration: Default, except for APICAST_WORKERS=1.
I used a minimal configuration that just redirects all the requests to the echo endpoint of a different APIcast running on the same host. internal echo endpoint:
```
{
"services": [
{
"proxy": {
{ "name": "apicast.policy.upstream",
"rules": [{
"regex": "/",
"url": "http://127.0.0.1:8888" (different apicast)
}]
}
}
]
}
}
]
}
```
By making this simple …

perf: replace varargs in hot paths to make the code jittable

---

CHANGELOG.md

To keep master up-to-date with the latest 3.4 changes.
Includes #943 (but keeps 3.4.0-master as the version)

Merge 3.4 stable

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
t/http-proxy.t

When there isn't any query parameters the ngx.var.query_string
variable will be nil, which causes the format statement to add the
lireral string nil at the end of the request path.
This happens for https APIs when settings the http(s)_proxy environment
variable for apicast.

Fix 'nil' being added to path when using proxy

---

CHANGELOG.md
gateway/src/apicast/policy/default_credentials/apicast-policy.json
gateway/src/apicast/policy/default_credentials/default_credentials.lua
gateway/src/apicast/proxy.lua
spec/policy/default_credentials/default_credentials_spec.lua
spec/proxy_spec.lua
t/apicast-policy-default-credentials.t

The default credentials policy was not working correctly because it stored the default credentials in the service instead of the policies context.
Ref: https://issues.jboss.org/browse/THREESCALE-1547

[THREESCALE-1547] Fix default creds policy

---

doc/openshift-guide.md

`oc cluster up` docs have been removed from upstream repo: https://github.com/openshift/origin/pull/21399

Fix broken links in OpenShift doc

---

gateway/src/apicast/version.lua

Everything merged to master from now on will be part of the next release, so we need to change the version.

version: bump to 3.5.0-master

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/keys_helper_spec.lua
t/apicast-policy-3scale-batcher.t

adds ability to report app_id only. Fixes [THREESCALE-1515](https://issues.jboss.org/browse/THREESCALE-1515)

Make 3scale batcher policy compatible with OIDC

---

CHANGELOG.md

CHANGELOG: put batcher fix for OIDC under the correct section

---

t/listen-https.t

Test to verify claims in https://github.com/3scale/apicast/pull/938#issuecomment-444053017.
@nmasse-itix this PR adds a test that verifies path routing still works with HTTPS.

[t] test that path routing works with HTTPS

---

.circleci/config.yml

The profiling task was installing the lua and perl dependencies already installed in previous tasks.

circleci: use already installed deps in the profiling task

---

gateway/src/apicast/policy/cors/apicast-policy.json

I added further specification to the description of the field allow_origin in the CORS policy so that the users are aware that only one origin or '*' are allowed.

fixed description in CORS policy.

---

CHANGELOG.md
gateway/src/apicast/policy/routing/README.md
gateway/src/apicast/policy/routing/apicast-policy.json
gateway/src/apicast/policy/routing/init.lua
gateway/src/apicast/policy/routing/request.lua
gateway/src/apicast/policy/routing/routing.lua
gateway/src/apicast/policy/routing/routing_operation.lua
gateway/src/apicast/policy/routing/rule.lua
gateway/src/apicast/policy/routing/upstream_selector.lua
spec/policy/routing/request_spec.lua
spec/policy/routing/routing_operation_spec.lua
spec/policy/routing/routing_spec.lua
spec/policy/routing/upstream_selector_spec.lua
t/apicast-policy-routing.t

Closes #972 
This PR adds a new policy, routing. It can select an upstream based on the request path, a request header, a request query argument, and a JWT claim.
I added a [README](https://github.com/3scale/apicast/pull/976/files#diff-4b14e371f001593fb9bdbc2891a5ef2c) that explains how the policy works.
Depends on #974 and #975 
Ref: https://issues.jboss.org/browse/THREESCALE-1709

[THREESCALE-1709] Routing policy

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
t/http-proxy.t

This PR fixes a bug that happens when proxying POST requests to an HTTPS upstream when using HTTPS_PROXY.
We were using resty.http's `.get_client_body_reader()`, but it looks like the result of that function is `nil` in this case.
I just changed that call with `ngx.req.get_body_data()`. The 2 tests added in this PR were failing before the change.
Ref: https://issues.jboss.org/browse/THREESCALE-1781

[THREESCALE-1781] Fix bug with proxied POST requests to HTTPS API backend via forward proxy

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/apicast/apicast.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/apicast/apicast_spec.lua
t/apicast-policy-ip-check.t
t/apicast.t
t/fixtures/policies/deny/1.0.0/apicast-policy.json
t/fixtures/policies/deny/1.0.0/deny.lua
t/fixtures/policies/deny/1.0.0/init.lua

This PR fixes a bug that was triggered when combining the APIcast policy with some policies that can deny the request, such as the IP check one.
APIcast can call 3scale backend's authrep in the `access` and the `post_action` phases depending on whether the request is cached or not. The problem is that some policies were calling `ngx.exit(4xx)` to deny a request, and that prevents some phases from running, but it does not skip the post_action one.
In practice, this means that with a policy chain like `ip_check + apicast`, even when the IP check policy denied the request, post_action in apicast would run, and report to backend in certain cases.
The bug does not affect all the policies that deny a request. In particular, policies that use the `errors` module …

Ensure that the apicast post_action phase runs only if access runs

---

.luacheckrc
CHANGELOG.md
gateway/Roverfile.lock
gateway/conf/nginx.conf.liquid
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/cli/environment.lua
gateway/src/apicast/cli/template.lua
spec/cli/environment_spec.lua
spec/cli/template_spec.lua

Having all APIcast specific configuration in one file included by liquid allows us to replace that file with different server blocks etc. For example that is used by the standalone mode: #926.
Depends on #963.

Extract the main APIcast nginx configuration into own file

---

CHANGELOG.md
gateway/src/apicast/proxy.lua

Added info on the services in the response headers when using X-3scale-debug headers as asked in https://issues.jboss.org/browse/THREESCALE-1849

added service id and service name headers when X-3scale-debug is used

---

CHANGELOG.md
gateway/src/apicast/cli.lua
gateway/src/apicast/cli/command/push_policy.lua
gateway/src/apicast/policy_manifests_loader.lua
gateway/src/apicast/policy_pusher.lua
spec/fixtures/policies/test/1.0.0-0/apicast-policy.json
spec/fixtures/policies/test/2.0.0-0/apicast-policy.json
spec/policy_manifests_loader_spec.lua
spec/policy_pusher_spec.lua

This PR adds a command to push policy schemas to the 3scale admin portal.
I tagged it as WIP because we'll need confirmation from @hallelujah to make sure that the endpoints used and their parameters are correct.

Add "push_policy" command to the CLI

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/policy_pusher.lua
spec/policy_pusher_spec.lua

This PR fixes a couple of issues with the 'push_policy' command introduced in https://github.com/3scale/apicast/pull/986

Fix CLI command to push policy schemas

---

README.md

It broke when we renamed the repo to APIcast.

README: fix Circle CI badge link

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid

Closes [THREESCALE-1989](https://issues.jboss.org/browse/THREESCALE-1989)
Changes
```
< HTTP/1.1 200 OK
< Server: openresty/1.13.6.2
< Date: Mon, 18 Mar 2019 16:26:35 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
```
Into
```
< HTTP/1.1 200 OK
< Server: openresty
< Date: Mon, 18 Mar 2019 16:27:05 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
```

[nginx] do not send openresty version [THREESCALE-1989]

---

gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
gateway/src/apicast/policy/3scale_batcher/reports_batcher.lua
spec/policy/3scale_batcher/keys_helper_spec.lua
spec/policy/3scale_batcher/reports_batcher_spec.lua

Found when investigating https://github.com/3scale/APIcast/pull/1007
If a report has no credentials it should be ignored (for now).

Prevent a crash in 3scale batcher on reports with missing credentials

---

gateway/src/apicast/configuration/service.lua

Simple PR that just renames and documents the `get_auth_params()` method in the `Service` module.
The name of the method was confusing. It implied that it had something to do with the auth params (app_id, app_key, etc.), but it does not. This caused some confusion, see https://issues.jboss.org/browse/THREESCALE-1930 and I think it's not the first time that it happens.

Rename and clarify get_auth_params() method in the Service module

---

doc/policies_list/3.3.0/policies.json
doc/policies_list/3.4.0/policies.json
doc/policies_list/3.5.0/policies.json

With this, [Porta](https://github.com/3scale/porta) will be able to show a different list of policies based on the version of APIcast deployed.

Add list of policies for each version

---

Makefile

Dependencies target was not documented in the `make help`, this commit add
a help message for the target.

[make] Add dependencies helper message.

---

CHANGELOG.md
gateway/src/resty/http/proxy.lua
spec/resty/http/proxy_spec.lua

Fixes https://issues.jboss.org/browse/THREESCALE-2205
By default, the 'connect' method of lua-resty-http, uses the ip and the host as the key to find a connection in the pool of idle connections. Ref: https://github.com/ledgetech/lua-resty-http#connect
That can cause problems in the case of HTTPS requests as mentioned in the issue linked above. For example, when 2 different domains resolve to the same IP, the connection is reused, and it should not be.
The 'connect_proxy' method of the modified module was using correct IDs for the pool, but the 'connect_direct' method was not.

[THREESCALE-2205] Fix incorrect connection reuse

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/configuration/service.lua
spec/configuration_spec.lua
t/apicast-subset-of-services.t

This commit adds the option to filter services based on the endpoint.
This commit expose a new config flag using the env variable
`APICAST_SERVICES_FILTER`, services filter happens on
`configuration.filter_services`.

[config] add support to filter services by endpoint.

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/local_chain/local_chain.lua
spec/policy/local_chain/local_chain_spec.lua
t/apicast-policy-3scale-batcher.t

It was done correctly only for `rewrite()`. In the rest of the phases, the context received was not merged with the one coming from `policy_chain:export()`.
This is the same bug that we fixed in https://github.com/3scale/APIcast/pull/673 . However, we only fixed it for the rewrite phase.
I discovered this while working on [this branch](https://github.com/3scale/APIcast/tree/upstream-config-policy). I needed to export some data to the shared context and access it in the balancer phase and I realized that it was not there.

Local chain: forward correct context in all the request phases

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua

The 3scale batching policy did not appear with the correct name in the logs.

3scale batching policy: fix name in the logs

---

CHANGELOG.md
gateway/src/apicast/balancer.lua
gateway/src/apicast/policy/upstream_connection/apicast-policy.json
gateway/src/apicast/policy/upstream_connection/init.lua
gateway/src/apicast/policy/upstream_connection/upstream_connection.lua
gateway/src/resty/balancer.lua
spec/balancer_spec.lua
spec/policy/upstream_connection/upstream_connection_spec.lua
spec/resty/balancer_spec.lua
t/apicast-policy-upstream-connection.t

This PR adds a new policy, "Upstream Connection".
This policy allows to configure several options for the connections to the upstream. In particular, 3 timeouts:  connect_timeout, send_timeout, and read_timeout.
Ref: https://issues.jboss.org/browse/THREESCALE-2166

[THREESCALE-2166] Add Upstream Connection policy

---

CHANGELOG.md
gateway/src/apicast/policy/ip_check/apicast-policy.json
spec/policy/ip_check/client_ip_spec.lua

Closes #970 and [THREESCALE-1692](https://issues.jboss.org/browse/THREESCALE-1692)

[THREESCALE-1692] Change schema of IP check policy so it renders correctly in the UI

---

CHANGELOG.md

This PR just adds an entry for 3.5.0 in the CHANGELOG.
Notice that the base branch is `3.5-stable`.
Travis fails because the readme points to a tag that will be created after merging.

Release 3.5.0

---

CHANGELOG.md
doc/parameters.md
doc/prometheus-metrics.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/metrics/upstream.lua
gateway/src/apicast/policy/nginx_metrics/nginx_metrics.lua
spec/metrics/upstream_spec.lua
t/prometheus-metrics.t

This commits adds support to have additional information on some metrics[0],
this commit enables users to know the service affected by the metric. 
Due to this can be a problematic for Prometheus[1], to enable this a new ENV
variable(`APICAST_EXTENDED_METRICS`) is defined, so if users that have a few services
they can run the extended metrics without affecting Prometheus stability, if
they thousands of services the recommendation is to have this option disabled. 
In case of the extended_metrics is disabled, all the service labels will use
"all" value and Prometheus performance will not be affected.
The new metrics list looks like this:
```
bash-4.2$ curl http://localhost:9421/metrics -s | grep service
total_response_time_seconds_bucket{service="all",le="00.100"} 91 …
```

Add service label on metrics

---

t/apicast-policy-3scale-batcher.t

In this particular test, the context was not being shared properly between phases. The problem did not show up in this test, but it can cause problems in other tests that rely on having always the correct
context in the log phases for example. Like it happened here: https://github.com/3scale/APIcast/pull/1024#issuecomment-488673351

Fix problem with context sharing between phases in batcher policy test

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua
t/apicast-oidc.t

This commit adds the option to obtain the client_id from a different claim and
does not use the AZP claim if the identity provider does not need that. This
commit adds a new option `oidc_client_id` that can be used as a liquid template
to retrieve any claim from the JWT payload.
Fixes #1008
Fixes THREESCALE-2264

[THREESCALE-2264] Obtain JWT client_id from different claim

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_store.lua
gateway/src/apicast/policy/find_service/find_service.lua
spec/policy/find_service/find_service_spec.lua
t/apicast-path-routing.t

Reference: https://issues.jboss.org/browse/THREESCALE-1150
This PR adds a new env, `APICAST_PATH_ROUTING_ONLY`. When set to true, the gateway will use path-based routing and will not fallback to the default host-based routing, which is what happens when using `APICAST_PATH_ROUTING`.

[THREESCALE-1150] Add option to use only path-based routing

---

CHANGELOG.md
gateway/src/apicast/mapping_rule.lua
gateway/src/apicast/policy/keycloak_role_check/README.md
gateway/src/apicast/policy/keycloak_role_check/apicast-policy.json
gateway/src/apicast/policy/keycloak_role_check/keycloak_role_check.lua
spec/mapping_rule_spec.lua
spec/policy/keycloak_role_check/keycloak_role_check_spec.lua
t/apicast-policy-keycloak-role-check.t

This commits add the `methods` option on the keycloack policy. That
allow users to define a new policy from any jwt claim, resource and
method.
To be backwards compatible 'ANY' method is in place, and if methods are
not defined this global method will be used and all will work as normal.
Example policy:
```
{
"name": "apicast.policy.keycloak_role_check",
"scopes": [
{
"realm_roles": [ { "name": "director" } ],
"resource": "/confidential",
"methods": ["POST"]
}
],
"type": "blacklist"
}
},
{ "name": "apicast.policy.apicast" }
]
```

[THREESCALE-2236] Add methods option on Keycloak policy.

---

gateway/src/apicast/policy/rate_limit/README.md

I received some questions regarding how to configure the rate limit policy for specific use cases and I realized that it supports some options that were not documented in the README of the policy. I tried to write a more complex example that shows some of those things, like conditions.

policy/rate_limit: add more complex example to the README

---

gateway/config/standalone.lua
gateway/cpanfile
gateway/cpanfile.snapshot
gateway/http.d/standalone.conf.liquid
gateway/src/apicast/configuration_loader/data_url.lua
gateway/src/apicast/policy/standalone/configuration.lua
gateway/src/apicast/policy/standalone/standalone.lua
gateway/src/resty/sandbox.lua
gateway/src/resty/yaml.lua
spec/policy/standalone/configuration_spec.lua
spec/resty/yaml_spec.lua
t/apicast-policy-standalone.t

route can refer to an upstream(external) and directly send a response
there without going through a policy chain
it snowballed a bit into a bunch of fixes for standalone mode
required for https://github.com/3scale/ostia/pull/57
```json
{
"global": { "log_level": "debug", "error_log": "stderr", "access_log": "stdout" },
"server": { "listen": [{ "port": 8080, "name": "default", "protocol": "http" }] },
"routes": [
{
"name": "hello",
"match": { "server_port": "default", "uri_path": "/hello" },
"destination": { "upstream": "https://echo-api.3scale.net" }
}
],
"internal": [ ],
"external": [
{ "name": "https://echo-api.3scale.net", "server": "https://echo-api.3scale.net" }
]
}
```

[standalone] support for defining upstreams

---

doc/parameters.md

Fix wrong documentation in #1006 
It is APICAST_HTTPS_VERIFY_DEPTH, not APICAST_PROXY_HTTPS_VERIFY_DEPTH
/cc @jsmolar

[docs] fix APICAST_HTTPS_VERIFY_DEPTH documentation

---

CHANGELOG.md
gateway/Roverfile.lock
gateway/src/apicast/policy/apicast/apicast.lua
t/apicast-policy-upstream.t

If the proxy API backend is in uppercase it'll not work correctly and
Apicast exists with an execpetion [0]. This commit transform api_backend
always to lowercase string, so the system will not break even if
receives a uppercase string.
[0] Exception
```
2019/05/21 05:59:30 [error] 1037#1037: *3 lua entry thread aborted: runtime error: /home/centos/gateway/src/apicast/policy/apicast/apicast.lua:101: missing upstream
coroutine 0:
[C]: in function 'assert'
/home/centos/gateway/src/apicast/policy/apicast/apicast.lua:101: in function </home/centos/gateway/src/apicast/policy/apicast/apicast.lua:100>
/home/centos/gateway/src/apicast/policy_chain.lua:190: in function </home/centos/gateway/src/apicast/policy_chain.lua:187>
/home/centos/gateway/src/apicast/policy_chain.lua:190: in …
```

[THREESCALE-2540] Fix issues with uppercase upstreams.

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/README.md
gateway/src/apicast/policy/rate_limit/apicast-policy.json
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-rate-limit.t

Fixes [THREESCALE-2590](https://issues.jboss.org/browse/THREESCALE-2590)
Apart from that, I fixed a couple of minor things in the test files that I needed to modify to implement the patch.

[THREESCALE-2590] Add matches operation to the Rate Limit policy

---

Makefile

When starting from a clean repo clone, the `lua_modules` target fails sometimes. Adding it to `PHONY` fixes the problem.

Makefile: add lua_modules to PHONY

---

spec/luassert_helper.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua

This commit overwrites luassert stub function to make sure that before
try to mock any function verifies that is not mocked, and if it is,
revert to the original one. This prevents scenarios where multiple stubs
are in one test and are leaked to other test and that scenario is hard
to debug/notice.
I tried to fix this on `luassert.state`, but looks like that the second stub is not always registered and it was a bit flaky, so this, for now, is the best solution that I found. 
Fix https://github.com/3scale/APIcast/issues/1043

[Test] Luassert make sure to revert function if it is already mocked.

---

.circleci/config.yml
CHANGELOG.md
bin/busted.lua
gateway/src/apicast/executor.lua
spec/resty/openssl/bio_spec.lua
t/management.t
t/policies.pl
t/prometheus-metrics.t

Bump Openresty to 1.15.8.1 version

---

t/apicast-policy-rate-limit.t

Due to the openresty upgrade, resty-redis.connect did not resolve the docker
compose connection and these test are failing on development mode.
These changes update the way that integration test connect to redis, so
it uses the default threescale_utils as is used in policy/ratelimit.

[TEST] Fix rate limit integration test.

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
t/apicast-request-logs.t

Fixes [THREESCALE-2340](https://issues.jboss.org/browse/THREESCALE-2340)
This PR makes response codes compatible with reporting threads.
The only problem was that the status code (`ngx.var.status`) was checked in a timer and timers do not have access to ngx.var.*.

[THREESCALE-2340] Make response codes compatible with reporting threads

---

CHANGELOG.md
gateway/src/apicast/configuration_loader.lua
gateway/src/apicast/configuration_loader/remote_v2.lua
gateway/src/resty/oidc/discovery.lua
gateway/src/resty/synchronization.lua
spec/synchronization_spec.lua
t/configuration-loading-lazy.t

This commits add a new function `run` to the synchronization module,
that function ensures that a given function is going to be run in a safe
task and make sure that the release of the lock  always happens, so the
lock is not going to be blocked if something goes wrong.
Fix #1010
Fix THREESCALE-2194

 [THREESCALE-2194] Ensure locks are released on configuration_loader. 

---

doc/parameters.md
t/management-policies-endpoint.t

This PR documents how to enable only the `/policies` endpoint in the management API. I also added a test for it. No code changes are required, this was already supported.

Document and test management API only with policies exposed

---

CHANGELOG.md
gateway/src/apicast/policy/ip_check/client_ip.lua
t/apicast-policy-ip-check.t

This change allows to block traffic when multiple x-forwarder-for are defined
in the same request. Resty creates an array with all duplicated headers, so in
case of a array only the first heaeder will be used.
Also, adds the integration test to make sure that no regression in this case.
Example request to make it fail:
```
curl localhost:8080?user_key=123
-H "X-Forwarded-For: 1.2.3.4" \
-H "Host:one" \
-H "X-Forwarded-For: 1.2.3.44"  \
-v
```
config:
```
{
"services": [
{
"id": 200,
"endpoint": "http://localhost:8080",
"backend_version": "1",
"proxy": {
"service_backend_version": "1",
"hosts": [
"one"
],
"proxy_rules": [
{ "pattern": "/", "http_method": "GET", "metric_system_name": "hits", "delta": 1 }
],
{ "name": …
```

[THREESCALE-2775] [Policy] IP Check uses multiple x-forwarder-for headers.

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
spec/proxy_spec.lua
t/apicast.t

Fixes [THREESCALE-2755](https://issues.jboss.org/browse/THREESCALE-2755)
See the JIRA epic for a more detailed description: [THREESCALE-2752](https://issues.jboss.org/browse/THREESCALE-2752)
This uses the new `3scale-limit-max-value` header returned by apisonator: https://github.com/3scale/apisonator/pull/103

[THREESCALE-2755] Return "auth failed" instead of "limits exceeded" for disabled metrics

---

doc/performance.md
doc/profiling.md

This PR adds a document with general guidelines on how to debug performance issues in APIcast. It also introduces the caching modes available and explains how they can help in increasing performance.
Thanks @mikz for the diagrams!
Ref: https://issues.jboss.org/browse/THREESCALE-2338
@3scale/documentation feel free to add more commits in this PR if that is easier for you than commenting in the PR.

[THREESCALE-2338] Performance documentation

---

gateway/libexec/boot.lua

Clean warning on openresty 1.15.8.1, where some global variables are
set, and a warning message is show during startup outside apicast
packages.

Reset _G table to avoid invalid warning message.

---

doc/parameters.md

This PR modifies the description of the BACKEND_ENDPOINT_OVERRIDE environment variable. 
Fixes the issue [#1059](https://github.com/3scale/APIcast/issues/1059).

Backend enpoint override description update

---

yarn.lock

Due to security warnings in Github repo, bump all dependencies for
markdown-link-check tool
Process to upgrade:
```
localhost.localdomain ➜  APIcast git:(BumpJSdeps) ✗ yarn audit
yarn audit v1.16.0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.13.2 < 1.14.0 || >=1.14.1                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ …
```

Yarn.lock, updgrade dependencies.

---

spec/policy/jwt_claim_check/jwt_claim_check_spec.lua

To avoid printing when running the tests

jwt claim policy specs: stub ngx.say

---

CHANGELOG.md
gateway/src/apicast/version.lua

Note: travis build fails because of the v3.6.0-beta1 tag which will be created after merging.

release: 3.6.0-beta1

---

Makefile
docker-compose-devel-volmount-default.yml
docker-compose-devel-volmount-mac.yml
docker-compose-devel.yml

This PR fixes the development failures reported in  [https://github.com/3scale/apicast/issues/957](#957) using separate docker-compose files for volume configuration and -d option instead of --detach command line option for docker-compose.

fix for make development failures - github issue #957

---

CHANGELOG.md
gateway/src/apicast/policy/ngx_variable.lua

Due to a user request, providing more variables to the Liquid templating
to allow headers policy (As axample) to get remote porrt, server address
and port and the scheme.
Fix #1079

Liquid: extended variables to liquid templating.

---

CHANGELOG.md
Makefile
docker-compose-devel-volmount-default.yml
docker-compose-devel-volmount-mac.yml
docker-compose-devel.yml
gateway/src/apicast/policy/ngx_variable.lua

This PR merges `master` from `3.6-stable`. Notice that the base branch in this PR is `3.6-stable`.
`master` includes a couple of PRs that we'd like to include in the next 3.6.x release: #1067 and #1081

Bring changes in master to 3.6-stable

---

CHANGELOG.md
gateway/src/apicast/version.lua

Notice that the base branch of this PR is `3.6-stable`.
The travis build fails because there's a link in the changelog to a tag that will be created after merging.

release: 3.6.0-rc1

---

script/install/circleci.sh

Missed from commit `7910917d5388ad0c445837bf0b6dec6879bb3dc1` and
Circleci is not testing the profile target with the last openresty
version.

CIRCLE: bump Openresty to 1.15.1 version.

---

spec/resty/http_ng/backend/async_resty_spec.lua

The error message changed because of this commit:
https://github.com/chromium/badssl.com/commit/6806596afaca81090df1965e59f99eae33674d56

Fix verify ssl test in async_resty

---

gateway/src/resty/resolver.lua

A small code cleanup.
I noticed this while debugging some problems in the circleCI profile task.

Simplify tostring() in resty resolver

---

.circleci/config.yml

Disabled until we figure out why on many runs there are only a few requests using luaJIT traces.
Investigation here: #1096

Disable profiling job temporarily

---

spec/resty/http_ng/backend/async_resty_spec.lua

The error message changed because of this commit:
https://github.com/chromium/badssl.com/commit/6806596afaca81090df1965e59f99eae33674d56

Backport: spec/resty/http_ng/backend/async_resty: fix ssl test

---

yarn.lock

Bump lodash to 4.17.15 due to security alert CVE-2019-10744.
Bump all dependencies due to latest stable release.

Yarn: Upgrade dependencies

---

CHANGELOG.md
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/policy/logging/apicast-policy.json
gateway/src/apicast/policy/logging/logging.lua
gateway/src/apicast/policy/logging/readme.md
spec/policy/logging/logging_spec.lua
t/apicast-policy-logging.t

Some users requested different ways to log the access log with more metadata,
different formats or conditional logging based on multiple request values. 
This policy address this, two new variables are now set, where to allow or disallow
to print a custom log message, and another one `extened_access_log` just store
all the information to print that. 
The policy has multiple options, here a few examples:
Custom log format
```
{
"name": "apicast.policy.logging",
"enable_access_logs": false
"custom_logging": "\"{{request}}\" to service {{service.id}} and {{service.name}}",
}
}
```
Only log the entry if the status is 200
```
{
"name": "apicast.policy.logging",
"enable_access_logs": false
"custom_logging": "\"{{request}}\" to service {{service.id}} and …
```

Policy: logging add custom access log options (JSON, Service vars, NGX vars)

---

CHANGELOG.md

Notice that there was an item in the changelog introduced by error. The policy order checker is not in this branch.

release: 3.6.0-rc2

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/http_proxy/Readme.md
gateway/src/apicast/policy/http_proxy/apicast-policy.json
gateway/src/apicast/policy/http_proxy/init.lua
gateway/src/apicast/policy/http_proxy/proxy.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/http/proxy.lua
spec/policy/http_proxy/http_proxy_spec.lua
t/apicast-policy-http-proxy.t

This policy adds the option to set a service to use a http proxy (As is
in use for HTTP_PROXY parameter)
This service will allow Apicast users to send the traffic over a proxy
and do request modifications in 3-party proxies.
Traffic flow:
```
,-.
`-'
/|\
|            ,-------.          ,---------.          ,----------.
/ \           |Apicast|          |HTTPPROXY|          |APIBackend|
User           `---+---'          `----+----'          `----------'
|  GET /resource  |                   |                    |
| --------------->|                   |                    |
|                 |                   |                    |
|                 |  Get /resource    |                    |
|                 |------------------>|                    |
|                 | …
```

Policy: HTTP proxy

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua
t/configuration-loading-when-needed.t

This PR adds the option to add service configurations lazily.
This might be useful for users with many services configured. By default, APIcast loads all the services each time it downloads its configuration from the 3scale admin portal. With a large number of services, this could become problematic.
When this option is enabled, the configurations are loaded lazily. APIcast will only load the ones configured for the host specified in the host header of the request.
The option is not enabled by default. It is enabled using the `APICAST_LOAD_SERVICES_WHEN_NEEDED` env.
The PR also includes a couple of commits that clean up a bit the `remote_v2` module used in this PR and also adds some comments.

Load service configs one by one lazily

---

CHANGELOG.md
gateway/.s2i/bin/run

DNSmasq process was not handled by Apicast at all, dnsmasq process can
die and
will never be up, so dns queries will start to fail.
The reasons to have APICast were:
Openshift cluster provided multiple DNS servers in the resolv.conf:
not anymore, currently is using a Kubernetes service with static IP, so
all connections goes to the same service.
DNS service was block during pod updates, no longer a case, it's
working correctly, added more pods in to a service and do not have the
case.
Cache was not used, no longer needed due to resolver.search_dns is
looking for the full query in the cache before make the dns request to
the server. [0]
[0]
https://github.com/3scale/APIcast/blob/41ad2c2a04054cd05991a65fc807a8105cdb2fd6/gateway/src/resty/resolver.lua#L282-L302
Fix THREESCALE-1555 …

Openshift: delete dnsmasq procces [THREESCALE-1555]

---

CHANGELOG.md
gateway/src/apicast/template_string.lua
t/apicast-policy-headers.t

This commit allows users to use capture in their liquid expressions and
assign variables if they needed.
Due to the available_context return a readonly list, capture function
cannot assign the variable and things start to mess up[0]. Due to allow
users to define variables in liquid is quite bad, a new read-write
linked list is created with an empty table to allow write to a temporal
table.
[0] Exception:
```
2019/08/09 13:51:23 [error] 15620#15620: *9 lua entry thread aborted: runtime error: /home/centos/gateway/src/apicast/linked_list.lua:19: readonly list
coroutine 0:
[C]: in function 'error'
/home/centos/gateway/src/apicast/linked_list.lua:19: in function '__newindex'
./lua_modules/share/lua/5.1/liquid.lua:2512: in function 'define_var' …
```

Liquid: Available context move to readwrite linked list.

---

CHANGELOG.md
doc/parameters.md
gateway/conf.d/apicast.conf
gateway/src/apicast/cli/template.lua
t/opentracing.t

Due to the value of a ENV variable in the apicast.conf is a table,
replace can't be used directly on liquid variables.
This change add a new tostring method in the template to be able to use
string filters on nginx templates.
Added a new method because table need to be used to be able to use
empty conditions.
FIX THREESCALE-1660

Tracing: Fix exception with OPENTRACING_FORWARD_HEADER parameter.

---

docker-compose-devel.yml

At the moment, on the development container EDITOR is set to emacs, that
it's not installed at all.
I heavily use c^x + e to edit commands, and for me, having the EDITOR
variable set, it's a must.

Devel: set EDITOR to vi

---

CHANGELOG.md
doc/parameters.md
gateway/conf.d/apicast.conf
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/cli/environment.lua
t/http-keepalive-timeout.t

Nginx parameter keepalive-timeout cannot be set at all in the gateway.
Due to is not be able to set as a policy, a new ENV variable is now
enabled to define the timeout.

Gateway: Add a option to enable keepalive-timeout

---

CHANGELOG.md
gateway/src/apicast/executor.lua
gateway/src/apicast/policy/ngx_variable.lua
gateway/src/apicast/policy/routing/README.md
gateway/src/apicast/policy/routing/apicast-policy.json
gateway/src/apicast/policy/routing/routing_operation.lua
gateway/src/apicast/policy/routing/rule.lua
spec/policy/routing/routing_operation_spec.lua
t/apicast-policy-routing.t

Hi, 
Multiple commits here: 
1) Added original request information in the executor in the ngx.ctx. 
2) Clean a little bit the ngx_variable, I think that nothing wrong around this one, but please have a look. 
Other commits are to allow liquid match in the routing policy to accomplish @ppatierno feedback. 
Regards

Routing Policy  enhancements

---

CHANGELOG.md
gateway/src/apicast/executor.lua
gateway/src/apicast/policy/logging/logging.lua
gateway/src/apicast/policy/routing/routing_operation.lua
t/apicast-policy-logging.t

This commit add the way to get the target host on logging policy without
getting request headers.
Related to #1082

Logging: Added target host on logging policy.

---

CHANGELOG.md
gateway/src/apicast/policy/routing/README.md
gateway/src/apicast/policy/routing/apicast-policy.json
gateway/src/apicast/policy/routing/rule.lua
gateway/src/apicast/policy/routing/upstream_selector.lua
gateway/src/apicast/upstream.lua
spec/policy/routing/upstream_selector_spec.lua
t/apicast-policy-routing.t

Some users complained about that path on upstream can't be changed and a
global rewrite url will not work due each API backend is different, this
policy will update the request path to the liquid value.

Routing policy: Add a way to replace the path on routing policy

---

CHANGELOG.md
gateway/src/apicast/executor.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/url_helper.lua
t/apicast-policy-routing.t

Due to the changes made in the routing policy to be able to modify
request path the query args was appended, and in this case, unexcaped to
the upstream repo.
This change adds a resty/url_helper function; this code will be moved to
resty-url project in the following weeks.

Routing: Fix query args on replace_path

---

gateway/http.d/apicast.conf.liquid

Some TLS protocols are already deprecated and need to be removed from
NGinx config to avoid their use.

APIcast: Updated list of TLS protocols that are available.

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
gateway/src/resty/http/uri_escape.lua
spec/resty/http/uri_escape_spec.lua
t/apicast-mapping-rules.t
t/apicast-policy-url-rewriting.t

This commit address the issues with the mapping rules that normalizes
the URL and mapping rules are not matching correctly.
Fix #1002
Fix THREESCALE-3468

Mapping Rule: Use unescaped rule

---

CHANGELOG.md
gateway/src/apicast/policy/logging/logging.lua

To be able to log the mapping rule that was hit and the
metrics that were used.

Logging: adds usage statistic on log.

---

CHANGELOG.md
gateway/src/apicast/mapping_rule.lua
gateway/src/apicast/mapping_rules_matcher.lua
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/routing/apicast-policy.json
gateway/src/apicast/policy/routing/routing.lua
gateway/src/apicast/policy/routing/rule.lua
gateway/src/apicast/policy/routing/upstream_selector.lua
gateway/src/apicast/proxy.lua
gateway/src/apicast/upstream.lua
gateway/src/apicast/usage.lua
spec/policy/routing/routing_spec.lua
spec/usage_spec.lua
t/apicast-oauth.t
t/apicast-policy-3scale-batcher-blackbox.t
t/apicast-policy-routing.t
t/apicast-request-logs.t
t/apicast.t
t/configuration-loading-lazy.t
t/configuration-loading-with-oidc.t

Due to the changes in APIAP in 3Scale, a service can have multiple
backends(using routing policy) and multiple mapping rules can be hit and
it creates a bad behaviour around metrics reported to Apisonator.
This commit adds ownership on routing and mapping rules, where a
ownership can be used to filter the mapping rules that you want to
report. Here an example:
Routing policy:
```
path      backend           owner
----------------------------------
/foo/bar  http://1.1.1.1/   t1
/foo      http://2.2.2.2/   t2
```
Mapping rules:
```
path      metric        owner
-----------------------------------
/foo      hits          t2
/foo/bar  barMetric     t1
```
In this case, due to the request is going to /foo/bar the metric that
will be updated will be `barMetric` and it'll use `2.2.2.2` backend, …

Routing: Fix issues with invalid metric update on routing policy.

---

gateway/src/apicast/policy/tls/apicast-policy.json

Update display name for the TLS termination policy to be more
user-friendly.

Policy: TLS termination changed name.

---

gateway/Roverfile.lock

Due to the changes in Lua Rover a problem in the current version of the
argparse has been found, using the rockspec tried to copy doc directory
but it does not exist.
Failed rockspec:
```
$ curl https://luarocks.org/manifests/mpeterv/argparse-0.5.0-1.rockspec
package = "argparse"
version = "0.5.0-1"
source = {
url = "git://github.com/mpeterv/argparse",
tag = "0.5.0"
}
description = {
summary = "A feature-rich command-line argument parser",
detailed = "Argparse supports positional arguments, options, flags, optional arguments, subcommands and more. Argparse automatically generates usage, help and error messages.",
homepage = "https://github.com/mpeterv/argparse",
license = "MIT/X11"
}
dependencies = {
"lua >= 5.1, < 5.4"
}
build = {
type = "builtin",
modules = {
argparse = …
```

Build: Bump argparse version to 0.6.0

---

CHANGELOG.md
gateway/src/apicast/errors.lua
gateway/src/apicast/policy/apicast/apicast.lua
t/apicast-blackbox.t
t/apicast-policy-routing.t

Due to the large use of routing policy, nowadays and upstream maybe is
not defined at all, APIcast returns 200 back and logs a new message
that a upstream is not defined.
Due to the work in THREESCALE-3775, the team decided to return a 404
back to the client to be aware that the upstream is not correct. Is not
a 502 status code due to the gateway is not defined at all and can be
confusing.
Related-to THREESCALE-3775
Related-to https://github.com/3scale/porta/pull/1385

Return 404 to client if no upstream defined.

---

CHANGELOG.md
gateway/src/apicast/policy/load_configuration/load_configuration.lua

When Lazy mode is set and it's using SSL connection, the
configuration_store was not initialized, so the config was not found and
lazy mode can't found the service for the host.
Fix THREESCALE-3713

Configuration: Lazy mode issue with SSL certificate.

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
gateway/src/apicast/upstream.lua
t/apicast-blackbox.t

On read JSON config the null values are not consider nil. Due to the
latest changes on porta related to the null api_backend, APIcast will
raise an exception and things started to fail.
Related-to: https://github.com/3scale/porta/pull/1385
Fix: THREESCALE-3869

Upstream: return error if the value given is cjson.null

---

gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/proxy.lua
gateway/src/apicast/usage.lua
spec/usage_spec.lua

This is a cleanup in the usage format. A few places used the code that
was equal, also format should be method in the usage table and not a
separate function.

Proxy: Format usage

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_loader/remote_v2.lua
gateway/src/resty/oidc/discovery.lua
spec/resty/oidc/discovery_spec.lua
t/configuration-loading-with-oidc.t

This commit fix issues with the flipflop connections to the issuer.
Multiple users have hundred of services with the same issuer, and
multiple requests happen at the same time.
This commit has two pourposes:
- Make the issuer config retrieve a bit faster in the APIcast and do
not make multiple requests to retrieve the same info.
- In case that the issuer has internment issues, avoid that one service
loads correctly, and others do not load at all.
Fix [THREESCALE-3809](https://issues.redhat.com/projects/THREESCALE/issues/THREESCALE-3809)

OIDC: Using caching to retrieve issuer configs.

---

CHANGELOG.md
gateway/src/apicast/policy/find_service/path_based_finder.lua
t/apicast-path-routing.t

If PATH routing was defined, the uri was not escaped correctly so the
mapping rules will not work as expected.
Reported by: Carlo Palmiari <cpalmier@redhat.com>
Fix: THREESCALE-3468
Related-to:112fdfa502483983b462fb82a5e789003ab9f750

PATH-routing: url was not escaped correctly

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/upstream.lua
spec/upstream_spec.lua
t/apicast-policy-http-proxy.t
t/http-proxy.t

If http_proxy is set the host header is always rewritten to the IP. With
this change the http_proxy will be set to the DNS name to avoid issues
with virtual host in the endpoints.

http_proxy: set Host domain correctly

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/apicast-policy.json
gateway/src/apicast/policy/caching/apicast-policy.json
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/cors/apicast-policy.json
gateway/src/apicast/policy/grpc/apicast-policy.json
gateway/src/apicast/policy/headers/apicast-policy.json
gateway/src/apicast/policy/ip_check/apicast-policy.json
gateway/src/apicast/policy/keycloak_role_check/apicast-policy.json
gateway/src/apicast/policy/liquid_context_debug/apicast-policy.json
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rewrite_url_captures/apicast-policy.json
gateway/src/apicast/policy/upstream_connection/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/apicast-policy.json

To have a consistent capitalization over all policies.
Fix THREESCALE-4150

Policies: Normalize policy names.

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/src/apicast/policy/websocket/README.md
gateway/src/apicast/policy/websocket/apicast-policy.json
gateway/src/apicast/policy/websocket/init.lua
gateway/src/apicast/policy/websocket/websocket.lua
gateway/src/apicast/upstream.lua
spec/upstream_spec.lua
t/apicast-policy-websocket.t

This commit adds the option to enable Websocket pass trough to the
upstream API if the original connection is a websocket connection.

Websocket support.

---

gateway/src/apicast/policy/find_service/find_service.lua

This commit adds the log with the service id used in the request.
This will help to know what service is hit, in some cases,  like the
combination of  PATH_ROUTING, LAZY mode, and multiple matched mapping
rules, so identify the service used will be used with this log.

Policy: find_service log service id

---

CHANGELOG.md
gateway/Roverfile.lock

Upgrade liquid-lua to support non alphanumeric variables.
Fix THREESCALE-3968

Roverfile: Upgrade liquid to 0.1.4

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/http.d/init.conf
gateway/src/resty/log/log.lua
t/apicast-log.t

When running APICast with a lot of requests is hard to know what log is
from each HTTP request, and it's hard to grep the logs easily.
This PR, patch ngx.log to use a custom implementation in Lua, that
provides the same info, but it appends a request_id in all log messages
produced by Lua, so it's easy to understand what happens.
This feature has a performance impact, so this is only enabled in
*debug* log level, so users will not be affected at all.
Sadly, some Nginx errors will not change, the HTTP log handler[1] does
not allow any outside interaction, but hopefully, this will help to
debug some complex scenarios like THREESCALE-4078
Example log request:
````
2020/01/17 11:23:11 [debug] 1377#1377: *9 executor.lua:26: rewrite(): executor phase: rewrite, …
```

Logs: Add request_id on debug

---

CHANGELOG.md
gateway/src/apicast/mapping_rule.lua
gateway/src/apicast/policy/soap/soap.lua
spec/mapping_rule_spec.lua
spec/policy/soap/soap_spec.lua

Due to the work make in APIAP, the double slash can happen quite easily,
as described in THREESCALE-3950. With this commit, when a new
mapping_rule is defined, double slash will be simplified to one to be
able to match with ngx.var.uri.
FIX THREESCALE-3950

Mapping rules: Avoid issues with double slash.

---

CHANGELOG.md
gateway/src/apicast/policy/logging/logging.lua
t/apicast-policy-logging.t

This is useful to help users to log custom information in access log
that is part of JWT headers.
FIX THREESCALE-4326

Logging policy: add support to log JWT payload.

---

CHANGELOG.md
gateway/src/apicast/policy/caching/caching.lua
spec/policy/caching/caching_spec.lua

New HTTP-NG coroutines return 0 when can't connect, so the caching
policy fails on the second request used, because the cache status was
updated with the an invalid status
This changes makes sure that the response code is a valid one, so the
caching status will report correctly.
Fix: THREESCALE-4471
Reported-by:Jakub Smadis <jsmadis@redhat.com>

Policy::Caching: issues when can't connect to backend.

---

Makefile

This is a fix to build luaossl with OpenSSL 1.1.1.
Related issue: https://github.com/wahern/luaossl/issues/175

Makefile: set env variable for luaossl

---

CHANGELOG.md
gateway/src/apicast/policy/default_credentials/apicast-policy.json
gateway/src/apicast/policy/http_proxy/apicast-policy.json

Policies: fix typos

---

CHANGELOG.md
gateway/src/apicast/policy/logging/logging.lua

If the logging config is not correct,operations are not defined,the loop
will not work and it'll crash.
Fix #1165
Fix THREESCALE-4605

Policy::Logging: Fix crash on invalid config.

---

CHANGELOG.md
gateway/src/apicast/policy/grpc/grpc.lua

This is a fix for GRPC when routing policy is used, where it uses the
old http1 endpoint.
Sample Config
```
{
"name": "routing",
"version": "builtin",
"enabled": true,
"rules": [
{
"url": "https://home-ip.acalustra.com:8080/",
"owner_id": 3,
"owner_type": "BackendApi",
"condition": {
"operations": [
{
"match": "path",
"op": "matches",
"value": "/default/.*|/default/?"
}
]
},
"replace_path": "{{original_request.path | remove_first: '/default'}}"
}
]
}
},
{
"name": "grpc",
"version": "builtin",
"configuration": {}
},
{
}
]
```
Fix THREESCALE-4684

GRPC: Routing rewrite upstream and GRPC one was not used.

---

CHANGELOG.md
gateway/src/apicast/policy/grpc/grpc.lua

backport a17158a57d76c45aacd67b9c65ae97843caa56ae to 3.8 stable

Backport GRPC changes

---

CHANGELOG.md
gateway/src/apicast/policy/grpc/grpc.lua
gateway/src/apicast/upstream.lua

This commit makes things super simpler in GRPC, and avoid the
miss-configuration that was made previously around upstream&balancers.
Before on GRPC we set the balancer, and all the balancer logic happened
on the policy itself, instead of using the apicast.upstream and
apicast.balancer.
With this change, the location is changed on the upstream.lua, so it
does not matter if was set in the apicast.policy, or in another policy,
in this case the routing policy.
This finally fix THREESCALE-4684

GRPC policy: Fix routing upstream issue.

---

CHANGELOG.md
gateway/src/apicast/policy/grpc/grpc.lua
gateway/src/apicast/upstream.lua

This commit makes things super simpler in GRPC, and avoid the
miss-configuration that was made previously around upstream&balancers.
Before on GRPC we set the balancer, and all the balancer logic happened
on the policy itself, instead of using the apicast.upstream and
apicast.balancer.
With this change, the location is changed on the upstream.lua, so it
does not matter if was set in the apicast.policy, or in another policy,
in this case the routing policy.
This finally fix THREESCALE-4684

[3.8] GRPC policy: Fix routing upstream issue.

---

CHANGELOG.md
Makefile
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/policy/rate_limit_headers/Readme.md
gateway/src/apicast/policy/rate_limit_headers/apicast-policy.json
gateway/src/apicast/policy/rate_limit_headers/cache.lua
gateway/src/apicast/policy/rate_limit_headers/cache_entry.lua
gateway/src/apicast/policy/rate_limit_headers/countdown_counter.lua
gateway/src/apicast/policy/rate_limit_headers/init.lua
gateway/src/apicast/policy/rate_limit_headers/rate_limit_headers.lua
gateway/src/apicast/proxy.lua
gateway/src/apicast/usage.lua
gateway/src/resty/counter.lua
spec/policy/3scale_batcher/3scale_batcher_spec.lua
spec/policy/rate_limit_headers/cache_entry_spec.lua
spec/policy/rate_limit_headers/cache_spec.lua
spec/policy/rate_limit_headers/countdown_counter_spec.lua
spec/proxy_spec.lua
spec/resty/counter_spec.lua
spec/usage_spec.lua
t/apicast-policy-rate_limit_headers.t

This PR adds a policy that enables rate-limits headers per service. 
All changes explained in the commit messages.

Rate Limit headers

---

gateway/src/apicast/policy/oauth_mtls/apicast-policy.json
gateway/src/apicast/policy/oauth_mtls/oauth_mtls.lua

OAuth 2.0 Mutual-TLS Client Authentication became RFC ([RFC8705](https://tools.ietf.org/html/rfc8705)).
So I updated the comment in the policy.
Also, JWS became RFC ([RFC7515](https://tools.ietf.org/html/rfc7515)).
However, I confirmed the specs relating to this policy were not changed.
So I changed only comments.

update oauth mtls policy comment

---

CHANGELOG.md
doc/parameters.md
gateway/conf.d/apicast.conf
gateway/conf/nginx.conf.liquid
gateway/src/apicast/policy/content_caching/Readme.md
gateway/src/apicast/policy/content_caching/apicast-policy.json
gateway/src/apicast/policy/content_caching/content_caching.lua
gateway/src/apicast/policy/content_caching/init.lua
gateway/src/apicast/policy/content_caching/rule.lua
spec/policy/content_caching/content_caching_spec.lua
spec/policy/content_caching/rule_spec.lua
t/apicast-policy-content-caching.t

This policy enables content caching in Nginx based on the request information and some new env variables added into the process.
This policy heavily uses proxy_cache directives, where we can enable/disable based on the policy.
Around response status codes, and headers, some details have been shared on Jira issues[0]
[0] https://issues.redhat.com/browse/THREESCALE-4064?focusedCommentId=13981036&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13981036
Fix THREESCALE-4064
Fix THREESCALE-2894
Fix THREESCALE-487

Initial content caching policy

---

CHANGELOG.md
gateway/Roverfile.lock

Bump liquid to 0.1.5

---

gateway/Roverfile.lock

Fix issues regarding wrong version of Prometheus Lua dependency.
Related to: https://github.com/knyar/nginx-lua-prometheus/pull/84

Luarocks: Fix Prometheus version

---

.circleci/config.yml
CHANGELOG.md
doc/parameters.md
gateway/Roverfile
gateway/Roverfile.lock
gateway/src/apicast/policy/content_caching/content_caching.lua
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/upstream_mtls/Readme.md
gateway/src/apicast/policy/upstream_mtls/apicast-policy.json
gateway/src/apicast/policy/upstream_mtls/init.lua
gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua
spec/policy/content_caching/content_caching_spec.lua
spec/policy/rate_limit/rate_limit_spec.lua
t/apicast-policy-upstream_mtls.t

By default, at the moment if a user wants to use MTLS with the upstream
API, the only way is using `APICAST_PROXY_SSL_CERTIFICATE`, and this
certificate will be used in all services.
With this policy, that includes an Nginx patch, and a new Nginx-module,
different client certificates can be used by service, so one APICast
instance can host more than MTLS connections to different upstreams.

Policy: MTLS upstream policy

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/resty/coroutines.lua
gateway/src/resty/file.lua
spec/resty/file_spec.lua
t/http-proxy.t

When request need to be stored in a temp file, the
ngx.req.get_body_data() will return nil. On some uses cases, users
report that large body is not correctly set. So things are failing on
their end.
This commit will check if the file has been created, read the data from
there and set the body correctly.
Fix THREESCALE-3863

HTTPS Proxy: Fix large body request.

---

CHANGELOG.md
gateway/src/apicast/policy/find_service/path_based_finder.lua
spec/policy/find_service/path_based_finder_spec.lua
t/apicast-path-routing.t

Pathrouting fix

---

CHANGELOG.md
gateway/src/apicast/policy/url_rewriting/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua
spec/policy/url_rewriting/url_rewriting_spec.lua
t/apicast-policy-url-rewriting.t

This resolves #1130 by taking an array of HTTP methods in the config for either the commands or the query_args_command. When the one or HTTP methods are applied in the config the rewrite rule only executes if the request method matches one in the config. If no methods are provided in the config the rewrite command will execute on all request methods.

Rewrite by verb 1130

---

CHANGELOG.md
gateway/src/apicast/policy/ip_check/client_ip.lua
spec/policy/ip_check/client_ip_spec.lua

This commit fix the issue when port is added into the forwarder-for
header and IPCheck will not match correctly.
Fix THREESCALE-5258

Policy: IPCheck validate that port is not used.

---

CHANGELOG.md
gateway/src/apicast/policy/custom_metrics/Readme.md
gateway/src/apicast/policy/custom_metrics/apicast-policy.json
gateway/src/apicast/policy/custom_metrics/custom_metrics.lua
gateway/src/apicast/policy/custom_metrics/init.lua
t/apicast-policy-custom-metrics.t

This policy adds the avalability to add a new metric on the post_action,
so user can report back things like metric upstream headers, status code
or any other information.
FIX THREESCALE-5098

Policy: Add custom metrics

---

t/policies.pl

If t/policies.pl is loaded, the expect_json will always be executed and
it fails, so some test are not running as expected.

PROVE: Fix issue on expect_json

---

CHANGELOG.md
gateway/http.d/shdict.conf
gateway/src/apicast/policy/rate_limit_headers/cache.lua
gateway/src/apicast/policy/rate_limit_headers/cache_entry.lua
gateway/src/apicast/policy/rate_limit_headers/rate_limit_headers.lua
spec/policy/custom_metrics/custom_metrics_spec.lua
spec/policy/rate_limit_headers/cache_entry_spec.lua
spec/policy/rate_limit_headers/cache_spec.lua

When testing rate_limit_headers the number of APICast workers are always set to
1. When the number of workers increased, the lru_cache is not longer effective
due to multiple threads.
Because we only have information about usage statistics on Authrep, and this is
using ngx.shared info, this policy also need to use shared information to be
able to reply without doing the authrep in all sessions.
Fix THREESCALE-3795

Policy: rate_limit_headers fix cache issues.

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/camel/Readme.md
gateway/src/apicast/policy/camel/apicast-policy.json
gateway/src/apicast/policy/camel/camel.lua
gateway/src/apicast/policy/camel/init.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/http/proxy.lua
spec/policy/camel/camel_spec.lua
t/apicast-policy-camel.t

Camel netty proxy was used via http-proxy policy, but on TLS
connections, the CONNECT method[0] is not allowed, so the request needs
to be terminated by camel-proxy and send to the upstream API.
With this change, we duplicate the http-proxy and we set the proxy to
terminate the connection so that will work correctly on camel TLS
connections.
[0] https://www.ietf.org/rfc/rfc2817.txt
Fix THREESCALE-4867

Policy: Camel proxy

---

CHANGELOG.md
doc/prometheus-metrics.md
gateway/src/apicast/policy/content_caching/content_caching.lua
t/apicast-policy-content-caching.t

When a content caching is enabled, a new metric is exposed to be able to
know the status of content caching.

Policy: content caching, add a new Prometheus metric.

---

CHANGELOG.md
gateway/src/apicast/upstream.lua
t/apicast-policy-routing.t

This commit fixes an issue when a special character uses some encoding.
The value to the upstream API if the routing policy was used, is also
encoded, so something like "/foo/test space" should land in APICast as:
`/foo/test%20space/`
And the path to the Upstream API should contain `test%20space`, but
because `ngx.req.set_uri` mark the URL to be encoded again, the URL that
will be received in the Upstream API will be `/test%2520space/`
This commit keeps the URL encoding correctly across all the flow.
Fix THREESCALE-5454

Policy: Routing fix URL encoding.

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit_headers/rate_limit_headers.lua
t/apicast-policy-rate_limit_headers.t

When the backend does not reply with limit headers, APIcast should send
no limit headers at all. This change make sure that the value is not
send at all.
Also, make sure that the value of limit and reset is always positive or
0.
THREESCALE-3795

Policy: rate limit headers does not send invalid value.

---

CHANGELOG.md
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/rate_limit/rate_limit.lua

When the condition is always true, or not valid at all, the number of
operations is not required at all.
Test no needed because is heavily tested without conditions on the
current integration test:
https://github.com/3scale/APIcast/blob/6f46ebde5a0d156a60874f0603c878140a3cf6d2/t/apicast-policy-rate-limit.t#L91
https://github.com/3scale/APIcast/blob/6f46ebde5a0d156a60874f0603c878140a3cf6d2/t/apicast-policy-rate-limit.t#L226
https://github.com/3scale/APIcast/blob/6f46ebde5a0d156a60874f0603c878140a3cf6d2/t/apicast-policy-rate-limit.t#L297
Fixes THREESCALE-5435

Policy:RateLimit: Fix issues with jsonschema

---

CHANGELOG.md
doc/parameters.md
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/policy/ip_check/apicast-policy.json
gateway/src/apicast/policy/ip_check/client_ip.lua
spec/policy/ip_check/client_ip_spec.lua
spec/policy/ip_check/ip_check_spec.lua
t/proxy-protocol.t

Closes #1194.
This is the same as PR https://github.com/3scale/APIcast/pull/1195 but with integration test.

Proxy Protocol support

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_store.lua
t/configuration-store-cache-limit.t

By default, 1000 services were enough, currently a lot of new users are hitting
thousands of services in a single APICast instance. This commit adds a option
to have a bigger cache size if the user desired that.
Fix THREESCALE-5308

Config: increase cache limits on demand.

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/http.d/apicast.conf.liquid
t/opentracing.t

When using opentracing, the http.host label, is the upstream Host. If a
user wants to track down the opentracing config with the original
host/header is not possible at all.
This commit adds a new tag on opentracing called original_request_uri.
Fix THREESCALE-5669

Opentracing: Added new tag

---

CHANGELOG.md
gateway/src/apicast/policy/caching/caching.lua
spec/policy/caching/caching_spec.lua

If caching is disabled, the key should be removed just in case some keys
are in the container from older configuration versions.
Fix THREESCALE-4464

Policy: caching fix issues when disabled.

---

CHANGELOG.md
gateway/src/apicast/policy/caching/apicast-policy.json
spec/policy/caching/caching_spec.lua

This change is to be consistent with other policies, where nothing is
set to default, but the value should be required.
Fix THREESCALE-1514:

Caching: JSONSCHEMA disable default value and required a value.

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/configuration_loader/oidc.lua
spec/configuration_loader/oidc_spec.lua
spec/configuration_spec.lua
t/apicast-subset-of-services.t

The oidc-service mapping is not based on a key, so each time that a
service is deleted, the mapping to the given service is broken.
With this change, the OIDC config is stored with the service id, so in
case that some services are removed, it'll keep it correctly mapped.
FIX THREESCALE-6042
Missing unit test

SERVICES_FILTER: Fix issues with oidc.

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
t/prometheus-metrics.t

I'm running some benchmarks with a large number of products, services, metrics, etc. and 1MB for the dictionaries used by the batching policy is not enough. I've seen the free space go to 0 using Prometheus.
For the particular use case that I'm trying ~12MB seems to be the minimum space required. I've defined 20 to have some margin.

Increase size of dictionaries used by the batching policy

---

CHANGELOG.md
gateway/src/apicast/policy/camel/camel.lua
gateway/src/apicast/upstream.lua
t/apicast-policy-camel.t

When routing policy is involved(default in APIAP) and Camel is enabled,
the upstream is no longer the context.get_upstream() so the changes made
to the upstream are not longer applied.
Fix THREESCALE-5891

Fix issues with Routing policy and camel

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/keys_helper_spec.lua

When the metric has a non-alphanumeric name, it'll be not reported
correctly by APIcast.
Fix THREESCALE-4913

3scale-batcher: Fix issues with non alphanumeric metrics.

---

CHANGELOG.md
gateway/src/resty/resolver.lua
spec/resty/resolver_spec.lua

When adding a dot to the end of the domain, the search string from
resolv.conf should not be added, because the domain is absolute.
Adding this, will save a few DNS request to the DNS server because no
cluster.local, etc.. will be added to the Qname.
More info in relation to this:
https://superuser.com/a/1468139
Fix THREESCALE-4752

Resolver: using Fully qualified names.

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
spec/configuration_spec.lua

When the OIDC config is false, an empty object is not added in the array, so
the services does not match, and OIDC validation failed.
FIX: THREESCALE-6313

OIDC: Fix issues with filtering services

---

CHANGELOG.md
gateway/src/apicast/cli/command/start.lua
gateway/src/apicast/cli/template.lua

A user reported that when a lot of services in K8s environment started
with apicast name, APICast cannot started because of the body size of
the template.
Because the body limit is set to nil, but liquid template set to 100000
[0] and started to fail in there.
The main reason to print all ENV variables on the nginx.conf, is because
the following code [1]
[0] https://github.com/3scale/liquid-lua/blob/a7f4119e96054f08df1fb8dce2be3469eb7ffb5f/lib/liquid.lua#L2675-L2686
[1] https://github.com/3scale/APIcast/blob/fba67b02200a4df231546145296927dea816c33f/gateway/http.d/init.conf#L46-L58
Fix THREESCALE-6315

CLI: increase body size on template render.

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

When remote_v2 config is in use, the APICAST_SERVICES_FILTER_BY_URL
parameter was not in use. The main reason was because  the IDs are
filtered out, but the host is not available on api/services.json.
This is a issue when multiple services are in place, and all of them
request info to openid connect, where things are getting super slow, but
in this case, the request to
admin/api/services/${serice id}/proxy/configs/staging/latest.json need to be done
to be able to filter it out.
FIX THREESCALE-6139

APICAST_SERVICES_FILTER_BY_URL fix when remote_v2 is in use

---

CHANGELOG.md
gateway/src/apicast/policy/jwt_claim_check/jwt_claim_check.lua
gateway/src/apicast/policy/load_configuration/load_configuration.lua
spec/policy/jwt_claim_check/jwt_claim_check_spec.lua
spec/policy/load_configuration/load_configuration_spec.lua
t/apicast-policy-jwt-claim-check.t

When using routing policy in APIAP, the path is always set to /. Becuase
routing policy is always the first, the jwt_claim_check started to fail,
because ngx.var.uri is always /.
This created a shared method, get_uri, and if routing policy was in use,
it'll use the new path.
FIX THREESCALE-6410

Policies: export get_uri method on context

---

CHANGELOG.md
gateway/src/apicast/policy/cors/apicast-policy.json
gateway/src/apicast/policy/cors/cors.lua
spec/policy/cors/cors_spec.lua
t/apicast-policy-cors.t

As per the [issue 1246](https://github.com/3scale/APIcast/issues/1246) this PR add Access-Control-Max-Age parameter to the CORS Policy

Add Access-Control-Max-Age to cors policy

---

CHANGELOG.md
doc/parameters.md
gateway/config/production.lua
gateway/http.d/apicast.conf.liquid
t/apicast-policy-logging.t

This commit add a new way to write access log, based on chunks, so
access log writes only happens when a buffer is full and this improves the
performance by reducing the number of system calls.

Add APICAST_ACCESS_LOG_BUFFER option

---

CHANGELOG.md
gateway/conf/nginx.conf.liquid
gateway/http.d/shdict.conf
t/prometheus-metrics.t

Fix: https://issues.redhat.com/browse/THREESCALE-6570

Performance improvements

---

CHANGELOG.md
gateway/src/apicast/policy/rewrite_url_captures/apicast-policy.json
gateway/src/apicast/policy/rewrite_url_captures/named_args_matcher.lua
gateway/src/apicast/policy/rewrite_url_captures/rewrite_url_captures.lua
spec/policy/rewrite_url_captures/named_args_matcher_spec.lua
spec/policy/rewrite_url_captures/rewrite_url_captures_spec.lua
t/apicast-policy-rewrite-url-captures.t

Adds a list of methods to the transformation. Checks the request method against the method configured in the policy just as it is done in the URL rewrite policy.
Fixes: THREESCALE-6270

adds method matching check to rewrite url captures policy

---

CHANGELOG.md
gateway/src/apicast/policy/cors/apicast-policy.json
gateway/src/apicast/policy/cors/cors.lua
t/apicast-policy-cors.t

This will check if the allow_origins is a valid regexp, and if it is,
will match with the Origin header value, it'll set the
Access-Control-Allow-Origin header to the Origin value.
Examples:
```
Config             | Origin Request Header Value  | Access-Control-Allow-Origin header
(api|web).test.com | http://web.test.com          | http://web.test.com
(api|web).test.com | http://api.test.com          | http://api.test.com
(api|web).test.com | http://staging.test.com      | Not header set
http://test.com    | http://api.test.com          | http://test.com
*                  | http://api.test.com          | *
blank              | http://api.test.com          | http://api.test.com
```
Fix: THREESCALE-6569

CORS: Enable multiple Origins value based on regexp.

---

CHANGELOG.md
gateway/src/apicast/policy/maintenance_mode/README.md
gateway/src/apicast/policy/maintenance_mode/apicast-policy.json
gateway/src/apicast/policy/maintenance_mode/maintenance_mode.lua
gateway/src/apicast/policy/upstream/upstream.lua
spec/policy/maintenance_mode/maintenance_mode_spec.lua
t/apicast-policy-maintenance-mode.t

- Adds the ability to select a list of upstrams (backends) to apply maintenance mode to + key/value liquid enabled operations.
- Updates a variable in the liquid context when the Upstream Policy changes the Upstream.

THREESCALE-6552 - RFE

---

gateway/src/apicast/policy/camel/Readme.md

`https_proxy` and `http_proxy` config examples should use `http` and not `https`.

fix camel proxy policy config example, minor copy edits

---

CHANGELOG.md
gateway/src/apicast/policy/routing/upstream_selector.lua
spec/policy/routing/upstream_selector_spec.lua
t/apicast-policy-routing.t

This makes hostname_rewrite work even when the routing policy is in the policy chain.

THREESCALE-6723 fix hostname_rewrite incompatible with routing policy

---

CHANGELOG.md
gateway/src/resty/http_ng/request.lua
spec/resty/http_ng/request_spec.lua

This strips the default port and use the correct host header value when
using http-ng
```
URL                          Host Header
--------------------------------------------------------------
http://foo.com               foo.com
http://foo.com:80            foo.com
http://foo.com:80/test       foo.com
http://foo.com:8080/test     foo.com:8080
https://foo.com/             foo.com
https://foo.com:8043/        foo.com:8043
https://foo.com:8043/test    foo.com:8043
```
Fix THREESCALE-2235

http-ng: fix HOST header

---

docker-compose-devel-volmount-default.yml
script/traces/Readme.md
script/traces/leaked.st

BPFtrace is a great tool to debug how APICast behave, this commit add
a few scripts that will help debugging weird behaviours.

BPFTrace: Add initial trace scripts

---

CHANGELOG.md
gateway/src/resty/oidc/discovery.lua
spec/resty/oidc/discovery_spec.lua

When JWK response was not application/json content_type, the keys cannot
be parsed and OIDC flow failed.
With this fix, if the application is returning `jwk-set+json`, something
valid that was not parsed as we should.[0]
[0] https://tools.ietf.org/html/rfc7517#section-8.5.1
Fix: THREESCALE-6913

OIDC: Fix discovery content-type issues

---

CHANGELOG.md
gateway/src/apicast/policy/payload_limits/payload_limit.lua
t/apicast-policy-payload_limits.t

When content length was bigger than the limit, the content length
value was not changed at all, and clients keep reading until got the
full length.
Fix https://issues.redhat.com/browse/THREESCALE-6736

Policy: Payload limits fix on content-length

---

CHANGELOG.md
gateway/src/apicast/usage.lua
spec/usage_spec.lua

Usage keys are based on ngx.encode_args, BUT due to the Luajit update
the data is not always the same, so the following usage metatable:
```
{
metric_a=1,
metric_b=1,
}
```
can be `metric_a=1&metric_b=1` or `metric_b=1&metric_a=1`, so the cached
key is not the same, and auth call will happen a few more times when it
shouldn't.
The way that I followed is the same as Openresty, and the escape_uri
should always be a string due to the usage method.
Fix THREESCALE-7122

Usage: fix issues on encoding 

---

CHANGELOG.md
gateway/src/apicast/policy/ip_check/ip_check.lua
spec/policy/ip_check/ip_check_spec.lua
t/apicast-policy-ip-check.t

Right now, when the IP cannot be retrieved on the IPCheck policy, the
request is accepted, but we cannot ensure the origin, so we should deny
always by default, and if the verdict is allowed, continue with the
request.
Fix THREESCALE-7076
Fix THREESCALE-7075

Policy: IpCheck default deny.

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/src/apicast/policy/content_caching/content_caching.lua
t/apicast-policy-content-caching.t

When using content_cache and proxy_no_cache, some directives are still
in place, and was causing issues to a few users regarding HEAD request,
etc..
This commit disabled the proxy_cache globally based on cache_zone
variable.
FIX THREESCALE-7016

Policy: Content Caching disable totally

---

CHANGELOG.md
gateway/Roverfile.lock
gateway/http.d/init.conf
gateway/src/apicast/cli/filesystem.lua
gateway/src/resty/yaml.lua

Delete warning message on 3party libraries

---

CHANGELOG.md
gateway/src/resty/resolver.lua
gateway/src/resty/resolver/dns_client.lua

The 1.19.3 Openresty version fixed how context is shared between the
ssl_certificate phase and others. Right now, if a dns_client is started
on ssl_cert, at other phases, the UDP socket is closed.
This is a fix at our end, but the fix will happen on Openresty upstream.
On staging env and Lazy config, on ssl_phase it'll retrieve the config
from an HTTP endpoint, and this will create a new dns_client instance
that cannot be used at all. It didn't hit the production env because a
timer retrieves the config.
Openresty config
```
master_process off;
worker_processes  1;
daemon off;
error_log /dev/stdout debug;
events {
accept_mutex off;
worker_connections 5000;
}
http {
server {
access_log  off;
listen 8043 ssl http2;
ssl_certificate certs/test.com.crt;
ssl_certificate_key certs/test.com.key; …
```

Openresty update: Fix issues with ssl_cert context

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/http.d/apicast.conf.liquid
t/apicast-log.t

When using ngx.var.host the access_logs are not logging the target host.
With this change, by default we log the host that was hit in the
upstream.
Fix THREESCALE-6193

Logs: Fix host on access logs

---

CHANGELOG.md
gateway/src/apicast/proxy.lua
spec/proxy_spec.lua

Since API as a product, api_backend is no longer a required parameter of
the config. Due to the change, a warning message was in place on each
request due to invalid upstream.
With this change, in case of no api_backend, a nil object is returned
and no error message at all.
Fix THREESCALE-5225

Logs: disable invalid warning when no api_backend

---

CHANGELOG.md
gateway/src/apicast/policy/nginx_filters/Readme.md
gateway/src/apicast/policy/nginx_filters/apicast-policy.json
gateway/src/apicast/policy/nginx_filters/init.lua
gateway/src/apicast/policy/nginx_filters/nginx_filters.lua
t/apicast-policy-nginx_filters.t

Nginx, by default, checks/validates some request headers. This policy
allows the user to skips these checks and sends them to the upstream
servers.
FIX THREESCALE-6704

Policy: Nginx header filter

---

CHANGELOG.md
gateway/src/apicast/configuration.lua
gateway/src/apicast/policy/on_failed/Readme.md
gateway/src/apicast/policy/on_failed/apicast-policy.json
gateway/src/apicast/policy/on_failed/init.lua
gateway/src/apicast/policy/on_failed/on_failed.lua
gateway/src/apicast/policy_chain.lua
spec/policy_chain_spec.lua
t/apicast-policy-on_failed.t
t/fixtures/policies/example_policy/1.0.0/example_policy.lua

Some users complained that if a policy fails, the request didn't
terminate. This problem is strategic for some users because it can raise
a security flaw if a policy is not executed correctly(jwt_claim_check
policy as an example)
This pull request adds some "pcalls" on policy_chain, where the error is
checked and, if the context has a callback function defined, is called.
Fix THREESCALE-6705

Policy: add on_failed policy

---

.circleci/config.yml
CHANGELOG.md

When using master branch, the quay.io images are reference as master.
The operator team wants to have the name as latest, so all components
can have the same naming.
FIX https://issues.redhat.com/browse/THREESCALE-7251

CIRCLECI: push containers with latest tag when build master git branch

---

CHANGELOG.md
gateway/src/apicast/policy/payload_limits/apicast-policy.json

Right now, with the additionalproperties enabled, it shows multiple keys
that does not make sense at all.
Fix THREESCALE-6965

Fix: Payload limit policy, fix jsonschema

---

.circleci/config.yml
CHANGELOG.md
t/apicast-policy-upstream_mtls.t

When using invalid host, the ngx_ssl_host was not used, so the verify
was working when it shouldn't.
This PR is part of THREESCALE-768

TEST: Fix Uptream MTLs policy integration test

---

CHANGELOG.md
gateway/src/apicast/policy/routing/rule.lua
t/apicast-policy-routing.t

When operations is empty was working as expected, but when it was nil,
raises an excpetion and routing policy was not working as expected.
FIX https://issues.redhat.com/browse/THREESCALE-6415

FIX: routing policy catch-all condition

---

CHANGELOG.md
gateway/src/apicast/upstream.lua
t/apicast-policy-routing.t

When using encoding, some characters got encoded a few times, so the
upstream request was not correct.
Is impossible to get it 100% perfect, because some chars (`?/#`) are
hard to get it right when using ngx.var.uri, but we need to use
ngx.var.uri.
After discussing it with support/product, this is the best way to handle
it.
Reported by sillumin@redhat.com
Fix: https://issues.redhat.com/browse/THREESCALE-5117

Routing: Fix encoding.

---

CHANGELOG.md
gateway/src/apicast/upstream.lua
spec/upstream_spec.lua
t/apicast-policy-maintenance-mode.t

If the tmp_path is empty on upstream:append_path, we should add the
trailing slash, as resty_url:join is doing.
Fix https://issues.redhat.com/browse/THREESCALE-7146
Reported-by: sillumin@redhat.com

Upstream: Do not append a trailing / on the end.

---

t/apicast-policy-payload_limits.t

Some test were failing, and maybe is because busy CI worker node and
things are slower, increasing timeout to avoid this kind of issues.

Fix: Add bigger timeout on integration test

---

gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua

Negated the if condition in set_ca_cert so the log is displayed went the valid trusted CA store is not set.

Flip if condition in upstream_mtls

---

CHANGELOG.md
gateway/src/apicast/policy/caching/caching.lua
gateway/src/apicast/proxy.lua

When caching is disabled with none, the cache key can be in there, and a
race condition can be happend with this.
To test this:
1) Strict caching mode
2) Made a request, 200 OK cache.set("$KEY", 200)
3) Update config to none
4) apicast/proxy:authorize -> cache.get($KEY) is 200
5) request go to the API
6) Authrep, cache for $KEY is deleted.
Next request will return 403.
Fixed behaviour:
1) Strict caching mode
2) Made a request, 200 OK cache.set("$KEY", 200)
3) Update config to none
4) apicast/proxy:authorize -> cache.get($KEY) is 200
5) cache_is_disabled = true -> execute backend call.
5) request go to the API, and fails
6) Authrep, cache for $KEY is deleted.
Fix THREESCALE-4464

Caching: Fix race

---

CHANGELOG.md
gateway/src/apicast/policy/nginx_filters/apicast-policy.json

Add a minimum number of items in the policy to avoid empty list.
Fix https://issues.redhat.com/browse/THREESCALE-7349

Policy: Nginx filters fix jsonschema

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/oidc.lua
t/apicast-subset-of-services.t
t/configuration-loading-when-needed.t
t/management.t

By default, APICast stores all services in an array of Service Objects, also,
another array with the OIDC objects, something like this:
```
{
"services": [
{
"id": 1,
"issuer": "http://foo.com",
"auth_type": "oidc",
...
},
{
"id": 2,
"auth_type": "provider_key"
...
},
{
"id": 3,
"issuer": "http://bar.com",
"auth_type": "oidc",
...
}
],
"oidc": [
{
"issuer": "http://foo.com",
...
},
false,
{
"issuer": "http://bar.com",
...
}
]
}
```
The mapping, on APICast config is like this:
```
service[0] using oidc[0]
service[1] using oidc[1]
service[2] using oidc[2]
```
When we filter using `APICAST_SERVICE_LIST`, it filters based on the array, so
it'll transform to this:
export APICAST_SERVICE_LIST=3
```
{
"services": [
{
"id": 3,
"issuer": "http://bar.com",
"auth_type": "oidc",
...
}
],
"oidc": [ …
```

OIDC: Fix issues with subset of services.

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua

This is a second patch, and it's related to PR #1304.
When using remotev2 loader, the config.oidc is created in there, and
there is also a caching mechanism for OIDC[0], so we need to append the
service_id and send a valid table in case of non OIDC setup.
Because this oidc is cached, we also do a deepcopy, to avoid to use
always the same reference, so the config.oidc[i].service_id is always
different and we didn't get a invalid filtering.
This is only failing when using APICAST_SERVICE_LIST
[0] Commit: 720cd99f5dcbd2e11e3b3f07d5ee5888865740d7
Related to: THREESCALE-6042

OIDC: fix issue on remote v2.

---

CHANGELOG.md
gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua
t/apicast-policy-upstream_mtls.t

Before, if not CA cert was set, we don't set the verify at all, but this
is a bad behaviour because:
- CA certs can be the global ones.
- Verify is true, so should fail.
Now, if not CA proxy will return a 502 back to the user.
Fix THREESCALE-7508

Policy: upstream MTLS fix on verify.

---

.circleci/config.yml

When moving to the `latest` tag, `-builder` suffix was not added to the
image tag, some images got overwritten incorrectly.

CircleCI: Fix typo

---

.circleci/config.yml
CHANGELOG.md
gateway/http.d/apicast.conf.liquid

THREESCALE-7906
Under some error circumstances (like 414 Request-URI Too Large) the  access log were generated in a phase previous to having defined the access_log_enabled and the extended_access_logs_enabled.
This causes a warning to arise, but most importanty, prevented that acces to be logged.
We use the workarround of declaring the variables as a map with a default value because maps can be used in the http context and therefore will be available and initialized even on the given error case.

THREESCALE-7906

---

CHANGELOG.md
gateway/src/apicast/policy/clear_context/clear_context.lua
gateway/src/apicast/policy/clear_context/init.lua
gateway/src/apicast/policy_chain.lua
spec/policy/clear_context/clear_context_spec.lua
t/apicast-path-routing.t
t/apicast-policy-logging.t
t/apicast-policy-oauth-mtls.t
t/apicast-policy-routing.t
t/apicast-policy-tls_validation.t

This PR adds compatibility with [this OpenResty change](https://github.com/openresty/lua-nginx-module/pull/1514/files). 
It takes care of clearing the local context at the beginning of every separate request.
We use the context to determine routing to Products (when APICAST_PATH_ROUTING is enabled) or to Backends (when using APIaaP). Both those routing scenarios can be affected by the bug when connections are reused (see also [KCS1](https://access.redhat.com/solutions/6707511) and [KCS2](https://access.redhat.com/solutions/6749581))

THREESCALE-8000 + THREESCALE-8007 + THREESCALE-8252 (clear context policy)

---

gateway/src/apicast/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua
t/configuration-loading-when-needed.t

> Link to JIRA: https://issues.redhat.com/browse/THREESCALE-6448
The endpoing changes from `/admin/api/services/proxy/configs/:environment` to /admin/api/account/proxy_configs/:environment`.
Update the configuration loader to use the new endpoint and the tests that verify it.
* Run APIcast alongside Porta with the following configuration:
```env
THREESCALE_PORTAL_ENDPOINT=http://secret@provider-admin.3scale.localhost:3000
APICAST_LOAD_SERVICES_WHEN_NEEDED=true
APICAST_CONFIGURATION_CACHE=0
APICAST_CONFIGURATION_LOADER=lazy
```
* Make a request against APIcast and verify that it performs the correct request against the System API to the new endpoint

THREESCALE-6448: Change endpoint to System for services

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua
spec/policy/oidc_authentication/oidc_authentication_spec.lua
t/apicast-oidc.t
t/apicast-policy-3scale-batcher.t
t/apicast-policy-headers.t
t/apicast-policy-jwt-claim-check.t
t/apicast-policy-keycloak-role-check.t
t/apicast-policy-logging.t
t/apicast-policy-oauth-mtls.t
t/apicast-policy-oidc_authentication.t
t/apicast-policy-rate-limit.t
t/apicast-policy-routing.t
t/apicast-policy-token-introspection.t
t/apicast-subset-of-services.t

This PR adds a function to match the algorithm of the public key retrieved from the `jwks_uri` against the `jwt.header.alg` field. Currently we only match the JWT's `alg` against a whitelist which is populated based on the response from the discovery endpoint but this further check is required to ensure we do the verification correctly.
Fixes [THREESCALE-8249](https://issues.redhat.com/browse/THREESCALE-8249)

adds jwk alg matcher

---

docker-compose-devel.yml
spec/policy/rate_limit/rate_limit_spec.lua
spec/resty/http_ng/backend/async_resty_spec.lua
spec/resty/http_ng/backend/resty_spec.lua

There were 3 issues in the local environment that caused unittests to fail:
```
$ make busted
EXTRA_CFLAGS="-DHAVE_EVP_KDF_CTX=1" /usr/local/openresty/luajit/bin/rover install --roverfile=gateway/Roverfile > /dev/null
/usr/local/openresty/luajit/bin/rover exec bin/busted  
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●✱●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●● …
```

Fix local unittests issues

---

CHANGELOG.md
gateway/src/apicast/policy/tls/tls.lua
spec/policy/tls/tls_spec.lua

I had to open a new PR because https://github.com/3scale/APIcast/pull/1328 was already merged.
This fixes the problem mentioned [here](https://github.com/3scale/APIcast/pull/1328#issuecomment-1103114555).

THREESCALE-8000 + THREESCALE-8007 + THREESCALE-8252 (clear context policy part 2)

---

CHANGELOG.md
gateway/src/apicast/policy/nginx_filters/apicast-policy.json

This gives a default `false` value to the `append` property to make it consistent with the "unchecked" value that is visible in system by default for this policy.
It resolves the error `headers[0].append is a required property` that would otherwise show in the UI when the policy configuration is saved.
https://issues.redhat.com/browse/THREESCALE-7349

THREESCALE-7349 - Added default value for the append property

---

.circleci/config.yml
.gitignore
Dockerfile.devel
Makefile
config-5.1.lua
docker-compose-devel-volmount-default.yml
docker-compose-devel-volmount-mac.yml
docker-compose-devel.yml
site_config.lua
spec/resty/openssl/x509_spec.lua

* Remove dependency from openresty base image from https://github.com/3scale/s2i-openresty
* Added `Dockerfile.devel` with the devel image content
* Fixed  `spec/resty/openssl/x509_spec.lua` unittest. Reason:
* invalid certificate error message changed due to upgrade on `openssl-libs` dep:
* from `openssl-libs-1.1.1g-15.el8_3.x86_64` in `centos8` -> `openssl-libs-1.1.1k-6.el8_5.x86_64` in `ubi8`
* Development container had overlapping volume mounts, causing (in linux) to create files with the root owner. The overlapping volume mounts have been removed from docker compose config.
run development image
```
```
Inside the container, download dependencies
```
```
Inside the container, run apicast
```
{
"services": [
{
"proxy": { …
```

Development image upgraded to ubi8

---

t/apicast-async-reporting.t
t/apicast-caching.t
t/apicast-policy-3scale-batcher.t
t/apicast-policy-chains-crash.t
t/apicast-policy-chains.t
t/apicast-policy-rate-limit.t
t/apicast.t
t/configuration-loading-lazy.t

This PR tracks the conversion of some test files from `Test::APIcast` to the `Test::APIcast::Blackbox` framework.
Below the list of test files involved:
- apicast-request-logs.t
- resty-ctx.t
- apicast-policy-rate-limit.t
- apicast.t
- configuration-loading-lazy.t
- configuration-loading-boot-remote.t
- apicast-caching.t
- configuration-loading-boot-without-config.t
- custom-config.t
- apicast-async-reporting.t
- apicast-policy-3scale-batcher.t
- backend.t
- resolver.t
- balancer.t
- apicast-upstream-balancer.t
- management.t
- apicast-policy-chains.t
- apicast-mapping-rules.t
- backend-cache-handler.t
Of the above, the following are blocking https://github.com/3scale/APIcast/pull/1340:

THREESCALE-8453 tests conversion to APIcast::Blackbox

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/http.d/apicast.conf.liquid
t/apicast-log.t

As a follow up to https://github.com/3scale/APIcast/pull/1319, 2 more variables require to be initialized with a default value to avoid generating "uninitialized variables" logs in case a large URI is passed in the request (that causes 414 Request-URI Too Large): $target_host and $post_action_impact

THREESCALE-7906 - initialization of $post_action_impact and $target_host variables as tables

---

Makefile
docker-compose.prove.yml
docker-compose.yml

* `apicast-source` target not needed for cleaning up `clean-containers`
* no need to have a container (running or stopped) to use `docker-compose.yaml` configuration
* makes easier to support `podman`. But currently I am not sure podman can replace docker, I haven't tested. 
* `prove` service from `docker-compose.yaml` removed and created a dedicated `docker-compose.prove.yml`. That configuration is being used in `make prove-docker` command. Used to run integration tests without running the development image (`make development`)
* `clean-containers` makefile target cleans all docker compose environments there could be up and running. 
Run integration tests in docker
```
make prove-docker
```
Clean running  environment(s) 
```
make clean-containers
```
check `apicast_build_0_prove` and …

remove container volume from docker-compose

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
t/http-proxy.t

This is a fix for THREESCALE-8426 where in some situations the client's request path is stripped away from the proxied upstream request.
- Backend with public path = /
- Upstream with https:// scheme and a path in its private URL, like: https://echo-api.3scale.net/some/path
- Https proxy (configured on APIcast for upstream connections)
- Send a request to APIcast with a certain path appended http://public-base-url/foo/bar
- Verify the request was actually sent to https://echo-api.3scale.net/some/path instead of the expected https://echo-api.3scale.net/some/path/foo/bar
The problem is that we set the upstream request's path using `uri.path` (when available) [here](https://github.com/3scale/APIcast/blob/132a91cb1869a4a607db69bfd3bb5ad5f2a03053/gateway/src/apicast/http_proxy.lua#L85). …

THREESCALE-8426 - request path is stripped for proxied https requests

---

CHANGELOG.md
gateway/src/apicast/configuration_loader/remote_v2.lua
spec/configuration_loader/remote_v2_spec.lua
t/configuration-loading-when-needed.t

This PR fixes [THREESCALE-8485](https://issues.redhat.com/browse/THREESCALE-8485) by passing "latest" as the version for the "endpoint_for_services_with_host" (i.e. the endpoint called when the configuration is loaded using [APICAST_LOAD_SERVICES_WHEN_NEEDED](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/administering_the_api_gateway/apicast_environment_variables#load-services-when-needed)).

THREESCALE-8485 fix: passing "latest" version

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua
t/apicast-oidc.t

Fixes [THREESCALE-8601](https://issues.redhat.com/browse/THREESCALE-8601)
Adds logic to allow JWKs which have no alg set, see JIRA for more details and the RFC.

THREESCALE-8601 jwt alg verification allows no alg in jwk object

---

doc/policies_list/3.10.0/policies.json
doc/policies_list/3.11.0/policies.json
doc/policies_list/3.11.1/policies.json
doc/policies_list/3.12.0/policies.json
doc/policies_list/3.6.0/policies.json
doc/policies_list/3.7.0/policies.json
doc/policies_list/3.8.0/policies.json
doc/policies_list/3.9.0/policies.json

Run apicast
```
{
"services": [
{
"proxy": {
"hosts": ["one"],
"proxy_rules": [],
"api_backend": "https://echo-api.3scale.net",
"policy_chain": []
}
}
]
}
EOF
$ docker run -ti --name apicast --rm -v $PWD/config.json:/opt/app/config.json:ro --env THREESCALE_CONFIG_FILE=/opt/app/config.json --env APICAST_LOG_LEVEL=debug --env APICAST_CONFIGURATION_LOADER=lazy --env APICAST_CONFIGURATION_CACHE=0 --env THREESCALE_DEPLOYMENT_ENV=staging --env BACKEND_ENDPOINT_OVERRIDE=http://127.0.0.1:3000 --env APICAST_WORKERS=1 quay.io/3scale/apicast:latest
```
Fetch policies
```
$ APICAST_IP=$(docker inspect apicast | yq e -P '.[0].NetworkSettings.Networks.bridge.IPAddress' -)
$ curl -v -H "Host: one" http://${APICAST_IP}:8090/policies -o policies.latest.json
$ cat …
```

update policy list

---

.circleci/config.yml

Fix error
```
#!/bin/sh -eo pipefail
make test-runtime-image gateway-logs --keep-going
docker-compose down --volumes --remove-orphans
ERROR: SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1131)
make: [Makefile:230: clean-containers] Error 1 (ignored)
docker-compose -f docker-compose.prove.yml down --volumes --remove-orphans
ERROR: SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1131)
make: [Makefile:231: clean-containers] Error 1 (ignored)
docker-compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-default.yml down --volumes --remove-orphans
ERROR: SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1131)
make: [Makefile:232: clean-containers] Error 1 (ignored) …
```

fix ci tests

---

.gitignore
Makefile

Due to `lua_modules` make target invoking `rover lock` command before `translate_git_protocol` (see #1320), commonly used targets like `dependencies` often fail with a `Connection refused` error.
Reported in #1375.

fix: use git https protocol

---

CHANGELOG.md
gateway/src/apicast/oauth/oidc.lua
spec/oauth/oidc_spec.lua
t/apicast-oidc.t

Fixes [THREESCALE-9009](https://issues.redhat.com/browse/THREESCALE-9009) Token generated for a realm associated with a different 3scale Product is able to reach the upstream with no verification performed
When a oidc JWT belonging to realm A is used in a request targeting a 3scale service configured with OIDC authentication with clients configured in realm B, the first conflict APIcast finds is that the referenced public key (in the JWT) does not exist. This PR address this issue adding a check on the JWKey object. 
In the absence of this check, the lua code was working with a `nil` object and raised an error (runtime error: nil pointer dereference) captured only by the [policy chain manager](https://github.com/3scale/APIcast/blob/3scale-2.13.1-GA/gateway/src/apicast/policy_chain.lua#L215 …

THREESCALE-9009 fix OIDC jwt key verification

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
Dockerfile.devel
Makefile
README.md
doc/parameters.md
docker-compose-devel.yml
docker-compose.yml
examples/opentelemetry/apicast-config.json
examples/opentelemetry/otel.toml
examples/opentracing/apicast-config.json
examples/opentracing/jaeger-config.json
gateway/conf.d/apicast.conf
gateway/conf.d/opentelemetry/otel.conf.liquid
gateway/conf.d/opentelemetry/otel.example.toml
gateway/conf/nginx.conf.liquid
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/cli/environment.lua
t/fixtures/otel.toml
t/opentelemetry.t

implements [THREESCALE-7735](https://issues.redhat.com/browse/THREESCALE-7735)
Specifically the subtask [THREESCALE-8865](https://issues.redhat.com/browse/THREESCALE-8865)
Adds OpenTelemetry distributed tracing support to Apicast.
Supported propagation types: [W3C](https://w3c.github.io/trace-context/)
Jaeger has deprecated the jaeger native clients. From [Jaeger doc](https://www.jaegertracing.io/docs/1.42/client-libraries/#deprecating-jaeger-clients)
> For new applications, we recommend using the OpenTelemetry APIs, SDKs, and instrumentation. Since v1.35, the Jaeger backend can receive trace data from the OpenTelemetry SDKs in their native OpenTelemetry Protocol (OTLP).
Jaeger client (based on opentracing) support is still in place, but gets deprecated in favor of the Opentelemetry use. …

THREESCALE-7735 THREESCALE-8865 opentelemetry instrumentation 

---

CHANGELOG.md
doc/parameters.md
gateway/src/apicast/configuration_loader/remote_v2.lua
gateway/src/resty/http_ng/backend/test.lua
spec/configuration_loader/remote_v2_spec.lua
t/apicast-policy-3scale-batcher-blackbox.t
t/configuration-loading-boot-remote.t
t/configuration-loading-filter-services-by-url.t
t/configuration-loading-from-service-list.t
t/configuration-loading-lazy.t
t/configuration-loading-with-oidc.t
t/configuration-loading-with-service-version.t
t/http-proxy.t

Load all services and proxy configuration pages
Fixes https://issues.redhat.com/browse/THREESCALE-8373
* Create more than 500 services in a tenant
* Deploy APIcast using `THREESCALE_PORTAL_ENDPOINT=https://<token>@<provider domain>`
* Send a request to one of last services created
* Observe 200 OK response (also observe APIcast logs indicate that first 500 services were loaded in a first request and the remaining services in a second request)

THREESCALE-8373 Pagination services and proxy config endpoints

---

CHANGELOG.md
gateway/bin/apicast
gateway/bin/apicast_cli.lua

removes the warning message at the start of APIcast POD
like this one:
```
env: '/tmp/FXal6CekIq': Permission denied
```
* start development mode
```
```
* Run APIcast
```
{
"services": [
{
"proxy": {
"hosts": ["one"],
"proxy_rules": [],
"api_backend": "https://echo-api.3scale.net",
"policy_chain": []
}
}
]
}
EOF
APICAST_LOG_LEVEL=warn APICAST_WORKERS=1 THREESCALE_CONFIG_FILE=config.json BACKEND_ENDPOINT_OVERRIDE=http://localhost:8081 ./bin/apicast
```
* Check the error `env: '/tmp/FXal6CekIq': Permission denied` does not exist

THREESCALE-7942 fix apicast bootstrap

---

CHANGELOG.md
gateway/src/apicast/configuration_loader.lua

Fixes https://issues.redhat.com/browse/THREESCALE-9003
**Note**; no test provided. `boot.init` and `boot.init_worker` are hard to test and they are not tested. Manual test required.
* Run development environment
```
```
* Start APIcast in development mode `boot` with a non-zero TTL (i.e. 30s) and 1 worker
```
APICAST_LOG_LEVEL=info APICAST_WORKERS=1 THREESCALE_PORTAL_ENDPOINT=https://ACCESS_TOKEN@3scale-admin.3scale-domain BACKEND_ENDPOINT_OVERRIDE=http://localhost:8081 APICAST_CONFIGURATION_LOADER=boot APICAST_CONFIGURATION_CACHE=30 THREESCALE_DEPLOYMENT_ENV=staging ./bin/apicast
```
* Check logs for the initial configuration being loaded
```
2023/03/24 14:44:41 [info] 48229#48229: [lua] configuration_store.lua:132: store(): added service 1163 …
```

THREESCALE-9003 in boot mode on worker init check configuration expiration

---

CHANGELOG.md
doc/policies_list/3.13.2/policies.json

Run apicast
```
{
"services": [
{
"proxy": {
"hosts": ["one"],
"proxy_rules": [],
"api_backend": "https://echo-api.3scale.net",
"policy_chain": []
}
}
]
}
EOF
$ docker run -ti --name apicast --rm -v $PWD/config.json:/opt/app/config.json:ro --env THREESCALE_CONFIG_FILE=/opt/app/config.json --env APICAST_LOG_LEVEL=debug --env APICAST_CONFIGURATION_LOADER=lazy --env APICAST_CONFIGURATION_CACHE=0 --env THREESCALE_DEPLOYMENT_ENV=staging --env BACKEND_ENDPOINT_OVERRIDE=http://127.0.0.1:3000 --env APICAST_WORKERS=1 quay.io/3scale/apicast:v3.13.2
```
Fetch policies
```
$ APICAST_IP=$(docker inspect apicast | yq e -P '.[0].NetworkSettings.Networks.bridge.IPAddress' -)
$ curl -v -H "Host: one" http://${APICAST_IP}:8090/policies -o policies.latest.json
$ cat …
```

update policy list v3.13.2

---

CHANGELOG.md
doc/policies_list/3.14.0/policies.json
gateway/src/apicast/version.lua

Run apicast
```
{
"services": [
{
"proxy": {
"hosts": ["one"],
"proxy_rules": [],
"api_backend": "https://echo-api.3scale.net",
"policy_chain": []
}
}
]
}
EOF
$ docker run -ti --name apicast --rm -v $PWD/config.json:/opt/app/config.json:ro --env THREESCALE_CONFIG_FILE=/opt/app/config.json --env APICAST_LOG_LEVEL=debug --env APICAST_CONFIGURATION_LOADER=lazy --env APICAST_CONFIGURATION_CACHE=0 --env THREESCALE_DEPLOYMENT_ENV=staging --env BACKEND_ENDPOINT_OVERRIDE=http://127.0.0.1:3000 --env APICAST_WORKERS=1 quay.io/3scale/apicast:latest
```
Fetch policies
```
$ APICAST_IP=$(docker inspect apicast | yq e -P '.[0].NetworkSettings.Networks.bridge.IPAddress' -)
$ curl -v -H "Host: one" http://${APICAST_IP}:8090/policies -o policies.latest.json
$ cat …
```

release 3.14.0

---

CHANGELOG.md
gateway/src/apicast/cli/environment.lua

backport https://github.com/3scale/APIcast/pull/1410

Backport THREESCALE-10167 cpu detection to 2.14

---

.codecov.yml
CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/src/apicast/policy/apicast/apicast.lua
spec/policy/apicast/apicast_spec.lua

Backport https://github.com/3scale/APIcast/pull/1417
Ref https://issues.redhat.com/browse/THREESCALE-10224
https://github.com/advisories/GHSA-qppj-fm5r-hxr3 (HTTP/2 Rapid Reset) fix

Backport 2.12 lua check client abort

---

CHANGELOG.md
dev-environments/grpc/Makefile
dev-environments/grpc/README.md
dev-environments/grpc/apicast-config.json
dev-environments/grpc/docker-compose.yml
gateway/src/apicast/configuration/service.lua
spec/configuration/service_spec.lua
t/apicast-mapping-rules.t
t/apicast-policy-upstream.t

Fixes https://issues.redhat.com/browse/THREESCALE-9976
GRPC leverages the POST HTTP2 method ([GRPC Spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)) . APIcast [reads the body](https://github.com/3scale/APIcast/pull/1419/files#diff-b4a0139162c96d858c01c0872560f495c15fee4e54df8ea52acda64e429c96cfR72) looking for request params for POST based requests using [ngx.req.read_body](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/#ngxreqread_body). However, [ngx.req.read_body](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/#ngxreqread_body) does not support HTTP2 and it blocks the request. The clients receive connection timeout errors.
Added development environment for GRPC scenario
* Build docker image from this git branch
```shell
make …
```

THREESCALE-9976 Fix GRPC

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/http_proxy/Readme.md
gateway/src/resty/http/proxy.lua
t/apicast-policy-camel.t
t/apicast-policy-http-proxy.t
t/fixtures/proxy.lua
t/http-proxy.t

What
Fixes https://issues.redhat.com/browse/THREESCALE-4393
This PR support the use of Basic Auth with forward proxy in the following scenarios:
* `APIcast <> forward HTTP proxy with Basic Auth <> HTTP upstream`
* `APIcast <> forward HTTP proxy with Basic Auth <> HTTPS upstream`
* Add the following line to `examples/forward-proxy/tinyproxy.conf`
```
BasicAuth foo bar
```
* Update `examples/forward-proxy/apicast-config.json` with the following:
```
{                                                             
"services": [                                             
{                                                     
"backend_version": "1",                           
"proxy": {                                        
"hosts": ["one"],                             
"api_backend": …
```

[THREESCALE-4393] Add support to use Basic Authentication with the forward proxy

---

t/resty-ctx.t

resty-ctx.t conversion to APIcast::Blackbox

---

t/backend-cache-handler.t

backend-cache-handler.t conversion to APIcast::Blackbox

---

CHANGELOG.md
gateway/conf.d/apicast.conf
gateway/conf.d/upstream_shared.conf
gateway/src/apicast/policy/request_unbuffered/README.md
gateway/src/apicast/policy/request_unbuffered/apicast-policy.json
gateway/src/apicast/policy/request_unbuffered/init.lua
gateway/src/apicast/policy/request_unbuffered/request_unbuffered.lua
gateway/src/apicast/upstream.lua
spec/upstream_spec.lua
t/apicast-policy-request-unbuffered.t

As part of https://issues.redhat.com/browse/THREESCALE-9542, this PR adds a new buffering policy which enable users to disable request buffering for use cases which call for it (namely, large payloads using HTTP 1.1 chunked encoding).
(Note: currently only support use case with no proxy between APIcast and upstream).
By default that the request buffer is true (which is the same as before). Users can now turn the request buffering off per service.
When request buffering is disabled, nginx will forward request body to upstream ASAP. 
* Expose port 8080 from dev image docker-compose-devel.yml
```                                                                    
version: '2.2'                                                               
services: …
```

[THREESCALE-9542] Part 1: buffering policy

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/request_unbuffered/README.md
gateway/src/apicast/upstream.lua
gateway/src/resty/file.lua
gateway/src/resty/http/request_reader.lua
gateway/src/resty/http/response_writer.lua
t/apicast-policy-camel.t
t/apicast-policy-http-proxy.t
t/http-proxy.t

Fix  https://issues.redhat.com/browse/THREESCALE-9542
This PR adds support to proxy the request with "Transfer-Encoding: chunked" when using with the proxy server.
Please just review the last 2 commits. I will rebase once part 1 merged
* Make runtime-image IMAGE_NAME=apicast-test
```shell
```
* Then run the gateway with the built image
```diff
diff --git a/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json b/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json
index 5227c5aa..24c45338 100644
--- a/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json
+++ b/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json
@@ -44,6 +44,11 @@
"host": "backend"
},
+ …
```

[THREESCALE-9542] Part 2: Add support to proxy request with Transfer-Encoding: chunked

---

gateway/src/apicast/policy/token_introspection/token_introspection.lua
spec/policy/token_introspection/token_introspection_spec.lua
t/apicast-policy-token-introspection.t

Fix https://issues.redhat.com/browse/THREESCALE-10591
From RH-SSO 7.5 [doc](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5/html-single/upgrading_guide/index#non_standard_token_introspection_endpoint_removed)
```
In previous versions, Red Hat Single Sign-On advertised two introspection endpoints: token_introspection_endpoint and introspection_endpoint. 
The latter is the one defined by [RFC-8414](https://datatracker.ietf.org/doc/html/rfc8414#section-2). The former was deprecated and is now removed.
```
The implementation is backward compatible with OIDC configuration services returning deprecated `token_introspection_endpoint`. When both `token_introspection_endpoint` and `introspection_endpoint` fields are in the response of the OIDC configuration service, the …

THREESCALE-10591 token instrospection field removed

---

CHANGELOG.md
dev-environments/keycloak-env/Makefile
dev-environments/keycloak-env/README.md
dev-environments/keycloak-env/apicast-config.json
dev-environments/keycloak-env/docker-compose.yml
gateway/conf.d/backend.conf

New development environment to test integration between APIcast and Keycloak
Based on Keycloak 23.0.4
> Note: The policy chain includes the token introspection policy, but this is not a requirement for testing keycloak integration.
* Build docker image from this git branch
```shell
```
* Run keycloak dev environment
```shell
cd dev-environments/keycloak-env/
make gateway IMAGE_NAME=apicast-test
```
* Keycloak provisioning. Create realm, clients, users
```shell
make keycloak-data
```
Admin web app available at `http://127.0.0.1:9090`, user: `admin`, pass: `adminpass`.
Access to the Keycloak CLI                                  
```sh                                                       
docker compose -p keycloak-env exec keycloak /bin/bash …
```

Dev environment: keycloak integration

---

CHANGELOG.md
gateway/src/apicast/policy/jwt_claim_check/jwt_claim_check.lua
t/apicast-policy-jwt-claim-check.t

Fix [THREESCALE-10308](https://issues.redhat.com/browse/THREESCALE-10308)
The uri was not escaped correctly with JWT claim check policy so the mapping rule will not work as expected.
For example: Mapping rule: `/api/{id}/whatever` is supposed to match `/api/  123/whatever` and perform the JWT token check but due to the special character (space) the request will not match on resource and APIcast  
skips the JWT token check.
* Mapping rule with capture group
Mapping rule:  `/foo{id}/bar`
Request | Direct to APICast | JWT Claim Check policy | PR#1428
-- | -- | -- | --
GET /foo/bar | False | False | False
GET /foo1/bar | True | True | True
GET /foo%201/bar | True | False | True
* Mapping rule with % character
Mapping rule:  `/foo%20/bar`
Request | Direct to APICast | JWT Claim Check policy | …

JWT claim check policy: uri was not escape correctly

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/balancer.lua
gateway/src/resty/http/proxy.lua
gateway/src/resty/resolver/http.lua
spec/http_proxy_spec.lua
spec/resty/http/proxy_spec.lua
t/apicast-policy-camel.t
t/apicast-policy-http-proxy.t
t/apicast-policy-upstream-connection.t

Fixes: https://issues.redhat.com/browse/THREESCALE-10582
Upstream timeouts don't work with Camel Service. Actually upstream connection policy is not working when `https_proxy` is being used (either with env vars or policy).
This PR fixes the integration of upstream connection with any use case for `https_proxy`. 
It was considered adding connection options to the proxy policy and camel policy. Mainly because "Upstream connection" policy is referring to "upstream", which can be confusing when a proxy is being used, as the connection to upstream backend is no longer made by APIcast. Instead, APIcast creates a connection to the proxy. So the Upstream connection opts should, ideally, only apply to connections to backend "upstream". 
We decided to apply upstream connection policy to any …

THREESCALE-10582 fix integration of upstream connection policy with camel policy

---

gateway/src/apicast/policy/token_introspection/token_introspection.lua
spec/policy/token_introspection/token_introspection_spec.lua
t/apicast-policy-token-introspection.t

Backport https://github.com/3scale/APIcast/pull/1438
Ref https://issues.redhat.com/browse/THREESCALE-10591

Backport  2.14 THREESCALE-10591 token introspection deprecated api

---

CHANGELOG.md
doc/parameters.md
gateway/http.d/core.conf
t/large-client-header-buffers.t

Fixes: https://issues.redhat.com/browse/THREESCALE-10164
* Creat a `apicast-config.json` file with the following content
```json
cat <<EOF >apicast-config.json
{
"services": [
{
"id": "1",
"backend_version": "1",
"proxy": {
"hosts": [
"one"
],
"backend": {
"endpoint": "http://127.0.0.1:8081",
"host": "backend"
},
{
}
],
"proxy_rules": [
{
"http_method": "GET",
"pattern": "/",
"metric_system_name": "hits",
"delta": 1,
"parameters": [],
"querystring_parameters": {}
}
]
}
}
]
} 
EOF
```
* Checkout this branch and start dev environment
```
```
* Run apicast locally
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=debug APICAST_WORKER=1 …
```

[THREESCALE-10164] Add support to set large_client_header_buffers directive

---

.luacheckrc
gateway/src/apicast/configuration.lua
gateway/src/apicast/configuration_loader/remote_v2.lua
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/management.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/policy/clear_context/clear_context.lua
gateway/src/apicast/policy/ip_check/ip_check.lua
gateway/src/apicast/policy/maintenance_mode/maintenance_mode.lua
gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua
gateway/src/apicast/policy/url_rewriting/url_rewriting.lua
gateway/src/apicast/usage.lua
gateway/src/resty/http/uri_escape.lua
gateway/src/resty/http_ng/headers.lua
gateway/src/resty/http_ng/request.lua
gateway/src/resty/openssl/x509/store.lua

I run luacheck manually, maybe we should bring codeclimate back

Update luacheck settings and fix issues reported

---

CHANGELOG.md
doc/parameters.md
gateway/conf.d/backend.conf
gateway/conf/nginx.conf.liquid
gateway/http.d/shdict.conf
gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua
gateway/src/apicast/policy/3scale_batcher/README.md

Fixes: https://issues.redhat.com/browse/THREESCALE-9537
3scale batcher policy use a few different shared dict caches
```
lua_shared_dict cached_auths 20m;
lua_shared_dict batched_reports 20m;
lua_shared_dict batched_reports_locks 1m;
```
and `api_keys` if Caching policy included in the chain
```
lua_shared_dict api_keys 30m;
```
First let's run some test to see how much `1m` of shared cache can hold.
```
lua_shared_dict test 1m;
location = /t {
content_by_lua_block{
local rep = string.rep
local dt = ngx.shared.test
local val = rep("v", 15)
local key = rep("k", 32)
local i = 0
while i < 200000 do
local ok, err = dt:safe_add("service_id:_" .. i ..",user_key:".. key ..",metric:hits", i)
if not ok then
break
end
i = i + 1
end
ngx.say(i, " key/value pairs inserted")
}
}
```
The reason to use …

[THREESCALE-9537] Configure batcher policy storage

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/keys_helper_spec.lua

Fix https://issues.redhat.com/browse/THREESCALE-10934
In my opinion there are 2 ways to fix this:
1. Replace the current regrex with the regrex from porta repo.  The allowed key formats are describe in the linked JIRA. I don't like this approach because we always have to make sure that the APIcast regular expression matches the one from the porta. Also, the current code allows `set` keys of any format but restricting the format when `get` is also strange to me.
2. Allow everything except spaces and let porta handle the validation during the authorization call. I think this is a better option but would be happy to discuss further.
* Configure a single Product A with user_key 
```
aGVsbG93b3JsZAo=
```
* Configure batcher policy with the following:
```
{ "name" : …
```

[THREESCALE-10934] [3scale_batcher] Update regex to match key with special chars

---

gateway/src/apicast/cli/template.lua

Re-added the code to disable warning about writing to global variable  that was added in https://github.com/3scale/APIcast/commit/d8bfb0c80a2d68c2b1d8fc6cbb9a5768b31b82f2
* Build runtime-image
```
make runtime-image
```
* Start APIcast
```
docker run --rm -ti --name apicast -p 8080:8080 --env THREESCALE_DEPLOYMENT_ENV=staging --env APICAST_LOG_LEVEL=debug --env APICAST_WORKER=1 --env APICAST_CONFIGURATION_LOADER=lazy --env APICAST_CONFIGURATION_CACHE=0 --env THREESCALE_PORTAL_ENDPOINT=https://example.com  apicast-runtime-image:latest
```
* Check that the following warning is not present in the log
```
~ vim-rust ❯ docker run --rm -ti --name apicast -p 8080:8080 --env THREESCALE_DEPLOYMENT_ENV=staging --env APICAST_LOG_LEVEL=debug --env APICAST_WORKER=1 --env …
```

Disable _G write guard warning

---

gateway/http.d/init.conf
gateway/http.d/shdict.conf
t/prometheus-metrics.t

Remove unused shared dict. May be help to save a few mb of memory 
* Create a apicast-config.json file with the following content
```
cat <<EOF >apicast-config.json
{
"services": [
{
"id": "1",
"backend_version": "1",
"proxy": {
"hosts": [
"one"
],
"backend": {
"endpoint": "http://127.0.0.1:8081",
"host": "backend"
},
{
}
],
"proxy_rules": [
{
"http_method": "GET",
"pattern": "/",
"metric_system_name": "hits",
"delta": 1,
"parameters": [],
"querystring_parameters": {}
}
]
}
}
]
} 
EOF
```
* Checkout this branch and start dev environment
```
```
* Run apicast locally
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=debug APICAST_WORKER=1 …
```

[chore] Remove unused shared dict

---

CHANGELOG.md
gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/keys_helper_spec.lua

A user reported similar error in #1453 but they have `app_id` with special chars instead.  I also think that user with `access_token` will have similar problem
From the portal code, app_id allows the following:
```
Allowed characters: 
A-Z a-z 0-9 ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ # Spaces are not allowed
```
I'm not sure if porta ever validate `access_token` but from the RFC the format is as follow
```
b64token    = 1*( ALPHA / DIGIT /
"-" / "." / "_" / "~" / "+" / "/" ) *"="
credentials = "Bearer" 1*SP b64token
```
* Configure Product A with app_id/app_key both contains special characters. For example
```
app_id: something:special
app_key: coffee_brain_food
```
* Configure batcher policy for both Product A and Product B with the following:
{ "name" : …

[3scale_batcher] Update regrex to match app_id with special characters

---

gateway/src/apicast/policy/3scale_batcher/keys_helper.lua
spec/policy/3scale_batcher/keys_helper_spec.lua

Backport #1457 
[Ref https://issues.redhat.com/browse/THREESCALE-10591](https://issues.redhat.com/browse/THREESCALE-10934)

Backport 2.15 THREESCALE-10934 Batcher policy does not accept the same chars specified in Porta regex for app_id, app_key & user_key

---

gateway/src/apicast/configuration_loader/file.lua
gateway/src/apicast/management.lua
gateway/src/apicast/policy/tls/tls.lua
gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua
gateway/src/apicast/util.lua

A small code clean up. No test is provided

Code cleanup

---

gateway/src/apicast/configuration_loader.lua

Details of the issue as well as local reproducers are documented in https://github.com/3scale/APIcast/issues/1467.
This change ensures that when `boot.init_worker` checks to see whether or not
the configuration needs to be reloaded, it also checks to confirm that the `boot.ttl()`
value set from `APICAST_CONFIGURATION_CACHE` is a positive number, in order to avoid
an immediate and infinite recursive loop of refreshing the configuration.
This should still preserve the initial fix [1] where this regression appears to
have been introduced, as we should never schedule reloading with the configuration settings of:
```
APICAST_CONFIGURATION_LOADER: boot
APICAST_CONFIGURATION_CACHE: -1
```
We should also never have a situation where we'd need to account for `interval = 0`
since we fail out in …

Ensure we don't schedule reloading configuration when reloading is disabled

---

CHANGELOG.md
gateway/src/resty/http/proxy.lua
t/http-proxy.t

Fix https://issues.redhat.com/browse/THREESCALE-11128
With the newer version of lua-resty-http (0.7.1), if a proxy options is not provided when calling the connect() method, it will fall back to using the global proxy settings set by the "set_proxy_option" function (has no effect in previous versions of the library). This then causes unexpected behavior where the direct connection will now go through the proxy server.
* Build a new runtime image
```
```
* Move into dev-environment
```
cd dev-environments/http-proxy-plain-http-upstream
```
* Edit apicast-config.json as follow:
```diff
diff --git a/dev-environments/http-proxy-plain-http-upstream/apicast-config.json b/dev-environments/http-proxy-plain-http-upstream/apicast-config.json
index …
```

Prevent APIcast fallback to global proxy settings for direct connection

---

CHANGELOG.md
gateway/src/resty/http/proxy.lua
t/http-proxy.t

Backport #1478 to manged-services

[THREESCALE-11128] Prevent APIcast fallback to global proxy settings for direct connection

---

CHANGELOG.md
gateway/src/resty/http/proxy.lua
t/http-proxy.t

[THREESCALE 11128] Prevent APIcast fallback to global proxy settings for direct connection

---

gateway/src/apicast/policy/token_introspection/apicast-policy.json
gateway/src/apicast/policy/token_introspection/token_introspection.lua
spec/policy/token_introspection/token_introspection_spec.lua
t/apicast-policy-token-introspection.t

Some time failed with the following error 
```
/opt/app-root/src/gateway/src/apicast/policy_loader.lua:98: Invalid config for policy: failed to validate dependent schema for "auth_type": value should match only one schema, but matches none
```
~~This is due to the use of `oneOf` and seems like a bug. I will need to investigate this further.~~
The original intention was to add support for a single algorithm and then upgrade lua-retsy-jwt afterwards and have a minimal schema structure change. However, the jsonschema validation fails when the emum field only contains a single value so I decided to remove it for now.
~~@eguzki if you know a better way to build `apicast-config.json` or how to solve this problem, please let me know~~
-------
This PR mainly adding 2 new authentication method for …

THREESCALE-11015 - Support client_secret_jwt and private_key_jwt as authentication type for token introspection policy

---

CHANGELOG.md
gateway/src/apicast/policy/token_introspection/README.md

* Add README file for token_introspection policy. Contents are copied from the official docs plus extra bit for new auth methods (private_key_jwt and client_secret_jwt)
* Add missing entries to CHANGELOG file
No verification steps

Add missing docs

---

CHANGELOG.md
gateway/src/apicast/policy/find_service/find_service.lua
gateway/src/apicast/policy/tls/README.md
t/listen-https.t

Fix https://issues.redhat.com/browse/THREESCALE-8486
and 
https://issues.redhat.com/browse/THREESCALE-11036
* Check out this branch
* Build runtime image
```
```
* Modify listen-tls environment as follow
```diff
diff --git a/dev-environments/listen-tls/docker-compose.yml b/dev-environments/listen-tls/docker-compose.yml
index 6d89464f..ce6ea12b 100644
--- a/dev-environments/listen-tls/docker-compose.yml
+++ b/dev-environments/listen-tls/docker-compose.yml
@@ -15,6 +15,7 @@ services:
THREESCALE_CONFIG_FILE: /tmp/config.json
THREESCALE_DEPLOYMENT_ENV: staging
APICAST_CONFIGURATION_LOADER: lazy
+      APICAST_PATH_ROUTING:true
APICAST_WORKERS: 1
APICAST_LOG_LEVEL: debug
APICAST_CONFIGURATION_CACHE: "0"
``` 
* Run local apicast
```
make gateway …
```

[THREESCALE-8486] TLS and path routing

---

CHANGELOG.md
gateway/src/apicast/policy/fapi/README.md
gateway/src/apicast/policy/fapi/apicast-config.json
gateway/src/apicast/policy/fapi/fapi.lua
spec/policy/fapi/fapi_spec.lua
t/apicast-policy-fapi.t

This PR support https://issues.redhat.com/browse/THREESCALE-11019. 
> 
> * shall support the provisions specified in clause 6.2.1 [Financial-grade API Security Profile 1.0 - Part 1: Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html); and
> * shall adhere to the requirements in [MTLS](https://tools.ietf.org/html/rfc8705).
* Build new runtime-image
```
```
* Move into keycloak dev-environment
```
cd dev-environments/keycloak-env
```
```
mkdir certs && cd certs
```
```
openssl genrsa -out rootCA.key 2048
openssl req -batch -new -x509 -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
```
* Generate a private key for the HTTPS keystore. Provide `changeit` as keystore password
```
keytool -genkeypair -keyalg RSA -keysize …
```

[THREESCALE-11019] - FAPI advance profile

---

CHANGELOG.md
doc/parameters.md
gateway/apicast.d/buffers.conf
t/proxy-buffers.t

Fix https://issues.redhat.com/browse/THREESCALE-8410
* `proxy_buffers`: this is the total size of the buffer that Nginx can use to hold the response from upstream. If the size of the response larger then the total size of the proxy_buffers Nginx will write response to disk
* `proxy_buffer_size`: mainly used to hold the response header.
* `proxy_busy_buffer_size`: size of the buffer can be used for delivering the response to clients while it was not fully read from the upstream server. 
* `proxy_buffers`: 
* Default: 8 4k|8k;
* Min: must be at least 2 buffers
* Max: no limit
* `proxy_buffer_size`:
* Min: No limit, can be set to smaller default value (4k|8k) but it's not recommend.
* Max: No limit, but should be no less than the maximum possible size of response HTTP headers 
* Default: one …

[THREESCALE-8410] Add support to set proxy buffer size

---

CHANGELOG.md
gateway/src/apicast/policy/camel/camel.lua
gateway/src/apicast/policy/http_proxy/proxy.lua
gateway/src/apicast/policy/request_unbuffered/request_unbuffered.lua
gateway/src/apicast/policy/retry/retry.lua
gateway/src/apicast/policy/upstream_connection/apicast-policy.json
gateway/src/apicast/policy/upstream_connection/upstream_connection.lua
spec/policy/camel/camel_spec.lua
spec/policy/http_proxy/http_proxy_spec.lua
spec/policy/retry/retry_spec.lua
spec/policy/upstream_connection/upstream_connection_spec.lua
t/apicast-policy-camel.t
t/apicast-policy-http-proxy.t
t/apicast-policy-request-unbuffered.t
t/apicast-policy-retry.t
t/apicast-policy-upstream-connection.t

Fix https://issues.redhat.com/browse/THREESCALE-9320
An interesting side effect of this PR is that it also fixes the following problems
https://issues.redhat.com/browse/THREESCALE-8146
https://issues.redhat.com/browse/THREESCALE-8149
When included in the policy chain, conditional policy will [construct](https://github.com/3scale/APIcast/blob/master/gateway/src/apicast/policy/conditional/conditional.lua#L15) an internal policy chain with a list of policies. 
When APIcast build a shared context,  it will then call [export()](https://github.com/3scale/APIcast/blob/master/gateway/src/apicast/executor.lua#L36) on the chain, including the chain constructed by the conditional policy. This means that any policy that implements export function will be triggered regardless of what the user sets the …

[THREESCALE-9320] Conditional policy evaluating incorrectly: second policy in policy chain that implement export() always triggers

---

Vagrantfile
doc/profiling.md
script/install/centos.sh
script/install/luarocks.sh
script/install/openresty.sh
script/install/utilities.sh

https://issues.redhat.com/browse/THREESCALE-10981
* Install Vagrant https://developer.hashicorp.com/vagrant/docs/installation
* Install QEMU
* Install [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt)
* Start vagrant VM
```
vagrant up --provider=libvirt
``` 
* Test systemtap is installed correctly
```
stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
```
The above command should run without any error.
```bash
Pass 1: parsed user script and 488 library scripts using 303940virt/97700res/17212shr/82296data k
b, in 100usr/20sys/119real ms.
Pass 2: analyzed script: 2 probes, 1 function, 5 embeds, 0 globals using 551508virt/346848res/189
36shr/329864data kb, in 1590usr/180sys/1806real ms.
Pass 3: translated to C into …
```

[THREESCALE-10981] - Update profiling tools

---

CHANGELOG.md
gateway/src/apicast/configuration_loader.lua
gateway/src/apicast/configuration_store.lua
gateway/src/apicast/policy/load_configuration/load_configuration.lua
spec/configuration_loader/remote_v2_spec.lua
spec/configuration_loader_spec.lua
spec/configuration_store_spec.lua

Fix https://issues.redhat.com/browse/THREESCALE-10130
* Install 3scale and create two Product A and B
* Start development environment
```
```
* Start APIcast with `THREESCALE_PORTAL_ENDPOINT=https://<token>@<provider domain>`
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=debug APICAST_WORKER=1 APICAST_CONFIGURATION_LOADER=boot APICAST_CONFIGURATION_CACHE=60 THREESCALE_PORTAL_ENDPOINT=https://token@3scale-admin.example.com ./bin/apicast
```
* Send requests
```
APICAST_IP=$(docker inspect apicast_build_0-development-1 | yq e -P '.[0].NetworkSettings.Networks.apicast_build_0_default.IPAddress' -)
curl -v -k -H "Host: example.productA.com:443" -H "Accept: application/json" http://${APICAST_IP}:8080/user_key=<user_key>
curl -v …
```

[THREESCALE-10130] APIcast using stale configuration for a deleted Product

---

.gitignore
doc/policy_tutorial/POLICY_RUN_LOCALLY.md

THREESCALE-11358
update the apicast config and the curl requests in the policy dev tutorial

THREESCALE-11358 update the apicast config and curl commands for echo-api

---

gateway/src/apicast/configuration.lua
spec/configuration_spec.lua
t/configuration-loading-from-service-list.t

Jira: https://issues.redhat.com/browse/THREESCALE-10894
Verification:
- Install 3scale and create ProductA, ProductB, ProductC, ProductD
- Promote products to stage -> prod
- checkout this branch
- start development env:
```
```
- Start APIcast with the following:
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=warn APICAST_WORKER=1 APICAST_SERVICES_LIST=<REPLACE WITH: ID OF ProductA, ID OF ProductB> APICAST_CONFIGURATION_LOADER=boot APICAST_CONFIGURATION_CACHE=60 THREESCALE_PORTAL_ENDPOINT=https://<REPLACE WITH: admin access token>@<REPLACE WITH: 3scale-admin.your_domain> ./bin/apicast
```
When the APIcast boots up, confirm the logs to be:
```
2024/09/05 10:28:03 [warn] 107000#107000: [lua] configuration.lua:171: filter_services(): Filtered out …
```

THREESCALE-10894 concat filtered services into a single log

---

CHANGELOG.md
doc/parameters.md
gateway/http.d/apicast.conf.liquid
gateway/src/apicast/policy/tls_validation/README.md
gateway/src/apicast/policy/tls_validation/tls_validation.lua
gateway/src/resty/openssl/x509/store.lua
spec/policy/tls_validation/tls_validation_spec.lua
t/apicast-policy-tls_validation.t
t/mutual-ssl.t

Fix: https://issues.redhat.com/browse/THREESCALE-10156
This PR add a new env var called `APICAST_HTTPS_VERIFY_CLIENT` to allow switching client verification mode. Due to there is no supported way to add client cert to the gateway, only two values are supported
* `off`: will not request client certificate
* `optional_no_ca` (default): request client cert but will not validate it against the trust CA
APIcast will now also request client certificates if `APICAST_HTTPS_VERIFY_CLIENT` is set to `off` but only if Client Certificate Authentication policy is in chain. 
| Routing mode | ssl_verify_client | client certificate requested by                                        |
| ------------ | ----------------- | ---------------------------------------------------------------------- |
| host …

[THREESCALE-10156] Configure ssl_verify_client per product

---

CHANGELOG.md
gateway/src/apicast/http_proxy.lua
gateway/src/apicast/policy/apicast/apicast.lua
gateway/src/apicast/policy/upstream_mtls/Readme.md
gateway/src/apicast/policy/upstream_mtls/upstream_mtls.lua
gateway/src/apicast/upstream.lua
gateway/src/resty/http/proxy.lua
gateway/src/resty/tls.lua
spec/policy/apicast/apicast_spec.lua
spec/policy/upstream_mtls/upstream_mtls_spec.lua
t/apicast-policy-http-proxy.t
t/http-proxy.t

Fix https://issues.redhat.com/browse/THREESCALE-5105
Please ignore codecov report. I will move tls.lua to apicast-nginx-module in the future commit.
* Build runtime image
```
```
* Get into the dev-environments
```
cd dev-environments/https-proxy-upstream-tlsv1.3
```
* Update `apicast-config.json` file as follow
```diff
diff --git a/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json b/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json 
index 5227c5aa..09fb1ab9 100644                                                                                                                    
--- a/dev-environments/https-proxy-upstream-tlsv1.3/apicast-config.json …
```

[THREESCALE-5105] Adding support for mtls when using proxy policy

---

CHANGELOG.md
doc/parameters.md
gateway/src/resty/resolver/http.lua

[THREESCALE-11321] Introduce APICAST_LUA_SOCKET_KEEPALIVE_REQUESTS env var

---

CHANGELOG.md
gateway/src/resty/http_authorization.lua
spec/resty/http_authorization_spec.lua
t/apicast.t

Fix [THREESCALE-11435](https://issues.redhat.com/browse/THREESCALE-11435)
* Create apicast-config.json with the following
```
cat <<EOF >apicast-config.json
{
"services": [
{
"backend_version": "2",
"id": "1",
"proxy": {
"credentials_location": "authorization",
"hosts": [
"one"
],
"backend": {
"endpoint": "http://localhost:8081",
"host": "backend"                   
},
{
"name": "routing",
"version": "builtin",
"enabled": true,
"rules": [
{
"url": "https://echo-api.3scale.net:443",
"owner_id": 119084,
"owner_type": "BackendApi",
"condition": {
"operations": [
{
"match": "path",
"op": "matches",
"value": "^(/test/.*|/test/?)"
}
]
},
"replace_path": "{{uri | remove_first: '/test'}}" …
```

[THREESCALE-11435] Check for nil value when decode based64 value

---

Dockerfile.devel

Due to recent work to support luarocks v3, the current dev-build is broken. This PR fix that by installing lua-rover directly from source.
* Run `make dev-build`, the build should complete without error

Fix broken dev-build

---

README.md
dev-environments/camel-proxy/README.md
doc/build.md
doc/why.md

What
Address broken link comment in https://github.com/3scale/APIcast/pull/1507

[doc] Fix broken link 2.15

---

Dockerfile.devel
Makefile

Update to support luarocks v3 and also refactor Dockerfile to install luarocks and lua-rover directly from source.
Runtime image still uses luarocks from rpms (v2). Once we have the PR from Yorgos merged, I will refactor further.

Update to luarocks v3

---

CHANGELOG.md
doc/parameters.md
gateway/src/resty/resolver/http.lua

Merge https://github.com/3scale/APIcast/pull/1496 into 3scale-2.15-stable branch

[THREESCALE-11321] Introduce APICAST_LUA_SOCKET_KEEPALIVE_REQUESTS env var (2.15)

---

.circleci/config.yml
dev-environments/camel-proxy/Makefile
dev-environments/camel-proxy/docker-compose.yml
dev-environments/grpc/docker-compose.yml
dev-environments/grpc/echoserver.Dockerfile
dev-environments/http-proxy-plain-http-upstream/docker-compose.yml
dev-environments/http-proxy-plain-http-upstream/tinyproxy.Dockerfile
dev-environments/https-proxy-upstream-tlsv1.3/docker-compose.yml
dev-environments/https-proxy-upstream-tlsv1.3/tinyproxy.Dockerfile
dev-environments/keycloak-env/docker-compose.yml
dev-environments/listen-tls/docker-compose.yml
dev-environments/opentelemetry-instrumented-gateway/docker-compose.yml
dev-environments/plain-http-upstream/docker-compose.yml
dev-environments/upstream-tlsv1.3/docker-compose.yml
docker-compose-devel.yml
docker-compose.benchmark.yml
docker-compose.prove.yml
docker-compose.yml

Remove dockerhub images from our build
| Image                            | Replace with                                       |
| -------------------------------- | -------------------------------------------------- |
| alpine/socat:1.7.4.4             | quay.io/openshift-logging/alpine-socat:1.8.0.0     |
| kalmhq/echoserver                |     build from source                                               |
| kennethreitz/httpbin<br>         | quay.io/kuadrant/authorino-examples:talker-api     |
| jaegertracing/all-in-one:latest  | quay.io/ducna/jaegertracing/all-in-one:1.60        |
| jboss/keycloak:3.1.0.Final                                 | quay.io/keycloak/keycloak:23.0.                    |
| alpine:3                         |  mirror.gcr.io/library/alpine:3 …

Move base image to registry and remove docker hub images

---

Dockerfile.devel

Update lua-rover to resolve bugs then we can build new dev/ci image

Upgrade lua-rover to v0.2.1

---

.circleci/config.yml
README.md
spec/resty/concurrent/timer_pool_executor_spec.lua

* Fix flaky tests
* Fix invalid link

Fix flaky tests and invalid link

---

Containerfile

Correct the wrong dependencies path
* Fetch submodules
```
git submodule update --recursive 
```
* Edit Makefile as below
```diff
diff --git a/Makefile b/Makefile
index b77767fe..938b3a20 100644
--- a/Makefile
+++ b/Makefile
@@ -150,7 +150,7 @@ prove-docker: ## Test nginx inside docker
runtime-image: IMAGE_NAME ?= apicast-runtime-image:latest
runtime-image: ## Build runtime image
-       $(DOCKER) build -t $(IMAGE_NAME) $(PROJECT_PATH)
+       $(DOCKER) build -t $(IMAGE_NAME) -f Containerfile $(PROJECT_PATH)
push: ## Push image to the registry
docker tag $(IMAGE_NAME) $(REGISTRY)/$(IMAGE_NAME)
```
* Build runtime-image
```
make runtime-image
```
* It should produce an image without error

[build] Correct the dependencies path

---

CHANGELOG.md
gateway/src/apicast/policy/conditional/apicast-policy.json
gateway/src/apicast/policy/content_caching/apicast-policy.json
gateway/src/apicast/policy/custom_metrics/apicast-policy.json
gateway/src/apicast/policy/jwt_claim_check/apicast-policy.json
gateway/src/apicast/policy/keycloak_role_check/apicast-policy.json
gateway/src/apicast/policy/maintenance_mode/apicast-policy.json
gateway/src/apicast/policy/rate_limit/apicast-policy.json
gateway/src/apicast/policy/routing/apicast-policy.json
gateway/src/apicast/policy/tls_validation/apicast-policy.json
gateway/src/apicast/policy/url_rewriting/apicast-policy.json

Fix https://issues.redhat.com/browse/THREESCALE-11610
More details here https://github.com/3scale/porta/pull/3968#discussion_r1920249458
We only need the CI to pass and we good to merge

[THREESCALE-11610] Remove "$id"  from the json schema

---

Dockerfile.devel

Http/2 tests failed in https://github.com/3scale/APIcast/pull/1523 this due to we removed http and luaossl modules when migrating to lua-resty-openssl
* Build a new dev-image
```
make dev-build IMAGE_NAME=apicast-dev
```
* Start development env
```
make development IMAGE=apicast-dev
```
* Run http/2 test
```
make prove PROVE_FILES=./t/apicast-http2.t
```
* All tests should pass

Reinstall http module to dev/ci image

---

CHANGELOG.md
gateway/src/apicast/policy/jwt_claim_check/apicast-policy.json
gateway/src/apicast/policy/jwt_claim_check/jwt_claim_check.lua
gateway/src/apicast/policy/jwt_claim_check/readme.md
spec/policy/jwt_claim_check/jwt_claim_check_spec.lua
t/apicast-policy-jwt-claim-check.t

Fix https://issues.redhat.com/browse/THREESCALE-9510
* Checkout this branch and build a new runtime image
```
```
* Move into dev-environment
```
cd dev-environments/keycloak-env
```
* Edit `apicast-config.json` as follow
```diff
diff --git a/dev-environments/keycloak-env/apicast-config.json b/dev-environments/keycloak-env/apicast-config.json
index 071296cd..62fb24f5 100644
--- a/dev-environments/keycloak-env/apicast-config.json
+++ b/dev-environments/keycloak-env/apicast-config.json
@@ -90,6 +90,20 @@
"auth_type": "use_3scale_oidc_issuer_endpoint"
}
},
+          {
+            "name": "apicast.policy.jwt_claim_check",
+            "configuration": {
+              "rules" : [{
+                  "operations": [
+                    {"op": "==", …
```

[THREESCALE-9510] Allow JWT Claim Check policy access to full request context when evaluate condition

---

CHANGELOG.md
gateway/src/apicast/threescale_utils.lua
spec/policy/rate_limit/rate_limit_spec.lua
spec/policy/rate_limit/redis_shdict_spec.lua
t/apicast-policy-rate-limit.t

Fix https://issues.redhat.com/browse/THREESCALE-11701
Close #1316 
* Checkout this branch and build a new runtime-image
```
```
* Get into dev-environment 
```
cd dev-environments/plain-http-upstream
```
* Edit `apicast-config.json` as follow
```diff
diff --git a/dev-environments/plain-http-upstream/apicast-config.json b/dev-environments/plain-http-upstream/apicast-config.json
index ff944273..b0193ee3 100644                                                                                                 
--- a/dev-environments/plain-http-upstream/apicast-config.json                                                                  
+++ b/dev-environments/plain-http-upstream/apicast-config.json …
```

[THREESCALE-11701] Remove redis connection error message from response body in edge limiting policy

---

CHANGELOG.md
gateway/src/apicast/policy/jwt_parser/README.md
gateway/src/apicast/policy/jwt_parser/apicast-policy.json
gateway/src/apicast/policy/jwt_parser/init.lua
gateway/src/apicast/policy/jwt_parser/jwt_parser.lua
gateway/src/apicast/policy/oidc_authentication/init.lua
spec/policy/jwt_parser/jwt_parser_spec.lua
t/apicast-policy-jwt_parser.t

Fix https://issues.redhat.com/browse/THREESCALE-10708
This is mostly a rename of oidc_authentication policy with an extra bit a logic on top to handle potential conflict with existing service configured with OIDC. 
See https://github.com/3scale/APIcast/pull/904#issuecomment-425832879
1. Check out this branch and build a new runtime-image
```
```
2. Move into dev-environments
```
cd dev-environments/keycloak-env
```
3. Modify `apicast-config.json` as follow
```
diff --git a/dev-environments/keycloak-env/apicast-config.json b/dev-environments/keycloak-env/apicast-config.json 
index 071296cd..d5ca17ca 100644                                                                                    
--- a/dev-environments/keycloak-env/apicast-config.json …
```

[THREESCALE-10708] JWT Parser Policy

---

gateway/src/apicast/policy/rate_limit/apicast-policy.json

Remove the $id field from rate_limit policy, somehow I missed this one in #1525

Remove left over  from rate_limit policy schema

---

CHANGELOG.md
gateway/src/apicast/policy/conditional/README.md
gateway/src/apicast/policy/conditional/conditional.lua
t/apicast-policy-conditional.t

Fix https://issues.redhat.com/browse/THREESCALE-11738
* Build new runtime-image
```
```
* Get into dev-environments
```
cd plain-http-upstream 
```
* Update `apicast-config.json`
```diff
diff --git a/dev-environments/plain-http-upstream/apicast-config.json b/dev-environments/plain-http-upstream/apicast-config.json
index ff944273..147a0d51 100644
--- a/dev-environments/plain-http-upstream/apicast-config.json
+++ b/dev-environments/plain-http-upstream/apicast-config.json
@@ -13,6 +13,38 @@
{
+          },
+          {
+            "name": "conditional",
+            "version": "builtin",
+            "configuration": {
+              "condition": {
+ …
```

THREESCALE-11738 - on_failed policy doesn't work with conditional policy

---

dev-environments/mtls/Makefile
dev-environments/mtls/README.md
dev-environments/mtls/apicast-config.json
dev-environments/mtls/cert/Makefile
dev-environments/mtls/cert/intermediate.cnf
dev-environments/mtls/cert/root-ca.cnf
dev-environments/mtls/docker-compose.yml
dev-environments/mtls/docker-entrypoint.sh
dev-environments/mtls/ocsp.Dockerfile

[dev-environments] Introduce MTLS dev environment

---

gateway/src/resty/http_ng/backend/resty.lua
spec/resty/http_ng/backend/resty_spec.lua
spec/resty/http_ng_spec.lua

Discovered this regression while investigate [THREESCALE-11741](https://issues.redhat.com/browse/THREESCALE-11741)
In PR #1503 we return nil and error in case of an error, however some code paths do not handle the error but instead check the error field of the response object and lead to unexpected behavior (bypass backend-listener authrep call).
The return value of http_ng backends is also inconsistent, some backends return errors while others return response objects with error fields. This leads to some code paths checking for errors (always nil for resty backends) while others check the response object for errors or ignore errors altogether. This needs to be investigated
* Build a new runtime image
```
``` 
* Get into …

Fix regression

---

.github/workflows/link_check.yaml

Update ubuntu image to the latest due to link check test failed with the following error
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```

[CI] Upgrade CI ubuntu image

---

gateway/src/apicast/policy/fapi/apicast-policy.json

Fix https://issues.redhat.com/browse/THREESCALE-11796
* Open `fapi/apicast-policy.json` and copy everything inside the `configuration` including the curly brackets
* Head to https://rjsf-team.github.io/react-jsonschema-form/
* Paste the content to `JSONSchema` text area, you should see the form render on the right hand
* Toggle the checkbox and click submit, you should see a popup with `Form submited`

[fapi] Correct boolean value in the schema
