Dockerfile, README.md, entrypoint.sh
* Added Auto update feature: Looks for changes in the config and deploys it.. 
* Added Signal support: USR1-> reload openresty, USR2-> Forces download of config and redeploy
=> Auto Update

3scale-gateway-openshift-template.yml, Dockerfile, README.md, entrypoint.sh
Initial changes for the 3scale gateway to work on Openshift.
=> Openshift support

3scale-gateway-openshift-template.yml, entrypoint.sh
- Fix some "shellchecks" linting errors
- replace nginx resolver by the docker one (/etc/resolv.conf)
=> Openshift 32 compatibility 

conf.d/apicast.conf, src/configuration.lua, src/provider.lua, t/003-apicast.t
* test caching works
* test backend gets proper parameters
=> [v2] test caching and backend parameters

nginx.conf
Just mount a folder into docker with `*.conf` files.
=> [config] offer customization

README.md
=> [readme] mention development branch

conf.d/management.conf, doc/configuration.md, src/management.lua, src/provider.lua, t/001-management.t
offers:
* liveness probe
* readyness probe
* config dump
It will be accessible on port 8090.
=> [management] basic stub of management API

.dockerignore, Dockerfile, Makefile, apicast-0.1-0.rockspec, conf.d/management.conf, docker-compose.yml, rockspec, script/wait-for, src/management.lua, t/001-management.t
and install them inside the docker image
=> [rocks] split dev and production rocks

.env, Makefile, README.md, docker-compose.yml, entrypoint.sh, src/configuration.lua
* improve readme
* crash when configuration is missing
* example env file
/cc @3scale/support feel free to point out what is missing
=> [docs] improve v2 documentation

.travis.yml, Makefile, docker-compose.yml, travis/install-s2i.sh
=> [s2i] use source to image

nginx.conf
closes https://github.com/3scale/docker-gateway/issues/36
=> [v2] Fix for "lua ssl certificate verify error"

.s2i/bin/assemble, Makefile, docker-compose.yml
and test that we run as random user id
=> [s2i] fix openshift permissions

README.md
just use APItools luarocks formula
and mention use of Test::Nginx
/cc @jcechace
=> [readme] improve readme for osx development

Makefile, conf/nginx.conf, entrypoint.sh
* remove dumb-init
* move nginx.conf to conf directory
=> Config cleanup

.travis.yml, Makefile, docker-compose.yml
let travis to push the built images
=> publish v2 docker images automatically

src/configuration.lua, src/util.lua
which can happen on badly configured openshift (almost all of them)
as they have dns server that is not reachable and nginx bails out when resolving
https://github.com/openshift/origin/issues/3820
=> fallback to curl when internal lua client does not work

README.md
last item before first alpha release
/cc @jmprusi
=> [readme] add openshift instructions

spec/configuration_spec.lua, src/configuration.lua, src/provider.lua, t/003-apicast.t
* do not use empty host override
* extract host from the api backend
=> fix Host header passed to the api backend

spec/configuration_spec.lua, src/configuration.lua, t/003-apicast.t
as you can't send host:port in Host header to the echo api
=> extract port from host

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, conf.d/apicast.conf, examples/configuration/multiservice.json, schema.json, src/provider.lua, t/003-apicast.t
* how to report issues
* how to try custom configs
* test multi service configuration
* example minimal multi service config
* json schema for minimal configuration
=> contributing guidelines

examples/custom-config/README.md, examples/custom-config/echo.conf
so people have reference how to run custom configuration
=> create custom config example

README.md
=> mention v2 is not for production use yet

README.md
fixes https://github.com/3scale/docker-gateway/pull/64#discussion_r78368883
=> reword readme to clarify it is not recommended for production use

doc/why.md
document why `v2`
/cc @vramosp
=> document benefits of v2

src/configuration.lua, src/provider.lua, t/003-apicast.t
* was missing because it was generated by ruby code
=> Fix query params rules

conf/nginx.conf, src/provider.lua, t/004-custom-config.t
* set APICAST_CUSTOM_CONFIG to path to custom config file
and it will be loaded when the server boots
/cc @mayorova
=> allow setting custom config through env variable

.travis.yml, Makefile
* release uses git repo instead of a copy
- that will add labels with git sha to the image
* push done by make
/cc @mayorova
=> [make] release process in makefile

t/001-management.t
that makes our tests to pass without internet connection
found at https://github.com/openresty/lua-resty-websocket/blob/f6634f93c642975e3cd33165f0aef729e9f2fbb4/t/cs.t#L1770-L1790
=> [test] use local dns server instead of external one

.travis.yml, Makefile, docker-compose.yml, t/001-management.t, travis/install-openresty.sh
so we can test that it works the same inside
=> run prove inside build docker

.travis.yml, Makefile, apicast/.s2i/bin/run, apicast/bin/apicast, apicast/entrypoint.sh, apicast/src/configuration.lua, bin/apicast, cpanfile.snapshot
* create log folder
* detect nginx/openresty
* wait for services to accept connections
=> [bin] update apicast binary and use it in docker

.travis.yml
so we don't push to the registry from PRs
=> [travis] don't build docker on pull requests

.travis.yml
=> [travis] fix image push after build

apicast/src/configuration.lua, apicast/src/provider.lua, apicast/src/util.lua, spec/util_spec.lua, t/003-apicast.t
use local variables instead of global
=> micro optimizations

README.md, apicast/src/configuration.lua, doc/management-api.md, doc/why.md, examples/configuration/example-config.json
Thanks to @mikz for the refactor and comments in `configuration.lua`
=> Updated README, added some code comments and refactor

doc/openshift-guide.md
The original [OpenShift guide](https://support.3scale.net/guides/infrastructure/docker-openshift) adapted for the v2 of dockerized gateway by @tnscorcoran
=> OpenShift deployment guide for APIcast v2

apicast/bin/apicast
it is not installed by default on centos7
=> [bin] do not depend on `which`

Makefile, apicast/.s2i/bin/run, apicast/bin/entrypoint, docker-compose.yml
use runtime image provided in https://github.com/3scale/s2i-openresty/pull/10
and let the release image use that
=> s2i runtime image

apicast/conf.d/apicast.conf, apicast/conf/nginx.conf, apicast/http.d/upstream.conf, apicast/src/apicast.lua, apicast/src/module.lua, spec/module_spec.lua
* split to sevelal phases
* introduce module system
* implement apicast as a module itself
=> introduce module system

.luacheckrc, .travis.yml, Makefile, apicast/conf.d/apicast.conf, apicast/src/apicast.lua, apicast/src/authorized_callback.lua, apicast/src/configuration.lua, apicast/src/get_token.lua, apicast/src/management.lua, apicast/src/module.lua, apicast/src/oauth.lua, apicast/src/provider.lua, apicast/src/threescale_utils.lua, apicast/src/util.lua
* `make check`
* fix errors
* part of travis
=> run luacheck

openshift/apicast-template.yml
ability to change log level of the gateway via parameter of the openshift template
=> [openshift] log level as parameter of the template

apicast/src/module.lua, apicast/src/resty/balancer.lua, apicast/src/resty/resolver.lua
* caching modules to prevent calling require
* properly resolve dns address when cache has no address
=> fixes related to caching

apicast/conf/nginx.conf, apicast/src/module.lua, apicast/src/provider.lua, apicast/src/util.lua, openshift/apicast-template.yml
* no duplicated logs
* add path routing to the openshift template
=> tuning openshift

.travis.yml, Makefile
Some changes to the installation steps so tests don't fail. I will add these steps to the existing docs and separate out the installation process to another .md file as Michal has suggested.
=> Install docs

apicast/src/provider.lua
=> simplify get_debug_value() in provider module

apicast/src/module.lua
=> Avoid unnecessary calls to require() in module.lua

apicast/conf.d/apicast.conf
=> remove unused config

.env, apicast/conf.d/apicast.conf, apicast/conf/nginx.conf, apicast/src/apicast.lua, apicast/src/provider.lua, openshift/apicast-template.yml, t/008-apicast-request-logs.t
=> enable request logs

.env, apicast/bin/apicast, apicast/conf/nginx.conf, apicast/src/apicast.lua
set either `AUTO_UPDATE_INTERVAL` or `-i N` when starting APIcast and see it update every N seconds!
No idea how to test this tough.
=> auto update interval

apicast/bin/apicast
mentioned: https://github.com/3scale/apicast/pull/134#issuecomment-260308405
/cc @andrewdavidmackenzie
=> [apicast] warn configuration reload is not for production

openshift/apicast-template.yml
=> Expose APICAST_RELOAD_CONFIG in Openshift template

Makefile, apicast/conf.d/apicast.conf, apicast/src/apicast.lua, apicast/src/module.lua, examples/custom-module/README.md, examples/custom-module/verbose.lua
adding logging as an example
closes #120
=> [example] customizing a module

apicast/conf.d/apicast.conf, apicast/src/get_token.lua, t/005-apicast-oauth.t
=> Oauth fixes

apicast/src/configuration.lua, examples/s2i/README.md, examples/s2i/config.json, examples/s2i/sites.d/echo.conf
example how to bundle customizations using s2i enabled by https://github.com/3scale/s2i-openresty/pull/13
/cc @mayorova
=> [example] s2i bunding customizations

doc/openshift-guide.md
@mayorova hope this is fine. Any tips for the whitespace changes on some of the newlines?
=> improve after dry run through

doc/centos-installation.md, doc/installation.md
Preview [here](https://github.com/3scale/apicast/blob/c65a67cc08d440b40cb236903a02e51b2c37abea/doc/installation.md)
=> Add installation instructions for CentOS

doc/oauth-guide.md
=> Apicast OAuth docs

README.md, apicast/conf/nginx.conf, apicast/src/provider.lua
Remove the comments, because they are either confusing or not needed.
=> Remove comments

Makefile, apicast/src/resty/balancer.lua, apicast/src/resty/resolver.lua, apicast/src/resty/resolver/cache.lua, spec/resty/resolver_spec.lua
some files were not check, so check them and fix them
=> [luacheck] fix make target and violations

Makefile, spec/configuration_spec.lua, spec/resty/resolver/cache_spec.lua
=> [make] fix check target

apicast/libexec/boot, apicast/src/apicast.lua, apicast/src/configuration.lua, apicast/src/configuration_loader.lua, apicast/src/configuration_loader/file.lua, apicast/src/configuration_loader/mock.lua, apicast/src/configuration_loader/remote_v1.lua, apicast/src/configuration_store.lua, apicast/src/management.lua, apicast/src/provider.lua, spec/configuration_loader/file_spec.lua, spec/configuration_loader/mock_spec.lua, spec/configuration_loader/remote_v1_spec.lua, spec/configuration_loader_spec.lua, spec/configuration_spec.lua, spec/configuration_store_spec.lua, spec/provider_spec.lua, t/003-apicast.t, t/004-apicast-path-routing.t, t/005-apicast-oauth.t, t/006-apicast-subset-of-services.t, t/008-apicast-request-logs.t
* extract "loaders" that load config from different sources
* new hashed configuration store for multi-tenant configurations
* cleanup seeding PRNG
=> [configuration] split configuration module

spec/luassert_helper.lua, spec/ngx_helper.lua, spec/spec_helper.lua
* reset `ngx.var` and possibly others in the future
* reset stubs
=> [spec] properly reset test environment

CHANGELOG.md
add a CHANGELOG.md to track notable changes
/cc @3scale/productization
=> [changelog] add a changelog

bin/busted, travis/install-openresty.sh
* bust cache on openresty version change
* patch resty to not resolve ipv6
* prepare bin/busted command for extra parameters
=> travis improvements

apicast/src/configuration_store.lua, apicast/src/provider.lua, t/003-apicast.t
as it can lead to hard to debug errors and using wrong service
=> [config] print warning when multiple services share host

openshift/apicast-template.yml
fixes  https://issues.jboss.org/projects/RHAMP/issues/RHAMP-41
=> [RHAMP-41] ability to set Redis from the OpenShift Template

CHANGELOG.md, apicast/src/apicast.lua, apicast/src/user_agent.lua, spec/user_agent_spec.lua
* bump version to 3.0.0-pre
* adjust changelog
=> release 3.0.0-alpha1

apicast/src/configuration.lua, apicast/src/configuration_loader/remote_v1.lua, apicast/src/configuration_parser.lua, apicast/src/management.lua, apicast/src/provider.lua, spec/configuration_loader/remote_v1_spec.lua, spec/configuration_parser_spec.lua, spec/configuration_spec.lua, spec/fixtures/echo.conf
configuration instantiation and parsing does not have to live together
=> [configuration] extract confguration parser

apicast/src/user_agent.lua, spec/user_agent_spec.lua
do not crash in some error scenarios
=> [user-agent] improve resiliency

CHANGELOG.md, apicast/src/authorize.lua, apicast/src/authorized_callback.lua, t/005-apicast-oauth.t
=> Add state to client_data for returning back to client

t/005-apicast-oauth.t
=> Use Authorization: Bearer xyz header for calls using OAuth

apicast/src/resty/http_ng.lua, spec/resty/http_ng_spec.lua
the extracted Host header would be wrong
/cc @mayorova
=> [http_ng] fix edge case in host extraction

.travis.yml, Makefile, doc/management-api.md, doc/openshift-guide.md, doc/parameters.md, examples/custom-module/README.md
test all links in the documentation as part of the CI build
/cc @3scale/support
=> test documentation links

CHANGELOG.md
forgotten in https://github.com/3scale/apicast/pull/248
=> [changelog] add backend endpoint override

CHANGELOG.md
title says it all, will be marked as v3.0.0-alpha2 after merge
=> [changelog] bump to v3.0.0-alpha2

.travis.yml, Makefile, README.md
* how to build runtime image
* how to test it
* how to push it
/cc @hallelujah
=> [doc] add release documentation

.gitignore, PERFORMANCE.md, Vagrantfile, apicast/bin/apicast, apicast/conf/nginx.conf
* improvements to bin/apicast to control number of workers
* vagrant to provide centos machine loaded with profiling tools
can easily produce flame graphs like in https://github.com/3scale/apicast/pull/251
/cc @3scale/support this can be useful to you when you need to profile something
=> toolkit for performance profiling

CHANGELOG.md
=> [changelog] update changelog

.travis.yml, CHANGELOG.md, Dangerfile, Makefile
Integrate Danger (http://danger.systems) bot to run checks on the PRs.
So far it should check for:
* grammar in markdown
* missing CHANGELOG.md
* spelling in markdown files
* big PRs
Will see how it goes. Contributions welcome!
=> [travis] use danger

CHANGELOG.md, apicast/conf/nginx.conf
port 8081 hosts just fake backend and echo api
so it can be used as a default server
/cc @jmprusi feel free to merge when green
=> [echo] listen as a default server

CHANGELOG.md, apicast/src/configuration_loader/remote_v2.lua
=> [config] parallelize access to the v2 api

CHANGELOG.md, apicast/src/apicast.lua, apicast/src/configuration_loader.lua, apicast/src/management.lua, apicast/src/proxy.lua, spec/configuration_loader_spec.lua, spec/proxy_spec.lua, t/001-management.t, t/003-apicast.t, t/004-apicast-path-routing.t, t/005-apicast-oauth.t, t/006-apicast-subset-of-services.t, t/008-apicast-request-logs.t, t/009-apicast-caching.t, t/010-apicast-mapping-rules.t
no class methods or objects, paves path for per request configuration
=> [proxy] use only instance interface

examples/configuration/README.md
Document how to run inside docker with custom configuration.
=> [example] show how to run echo.json api in docker

CHANGELOG.md, apicast/src/configuration_loader.lua, apicast/src/configuration_store.lua, apicast/src/management.lua, spec/configuration_loader_spec.lua, spec/management_spec.lua, t/001-management.t
when no services are loaded still return ready status
=> [management] return ready status even with no services

CHANGELOG.md
prepare for 3.0.0-beta1 release
=> [release] bump to 3.0.0-beta1

CHANGELOG.md
including changes from https://github.com/3scale/apicast/pull/287
=> [changelog] updated changelog

doc/management-api.md
* describe status api
* mention APICAST_MANAGEMENT_API variable
=> [doc] improve management api documentation

openshift/apicast-template.yml, openshift/portal-secret-template.yml
* closes https://github.com/3scale/apicast/issues/207
* fixes  https://issues.jboss.org/browse/THREESCALE-94 
* removes other unnecessary definitions
* gives names to ports
* ability to export management api
=> cleanup openshift template

doc/parameters.md
Fixing a typo/mis-reference in the parameters doc
=> fixes an incorrect reference to REDIS_URL parameter

examples/rh-sso/README.md
- added some extra commands (creating symlinks) required in RHEL to make this work
- removed the instructions for Docker, as it will not work with the default image (no XML libraries)
=> [examples] RH SSO readme updates

apicast/src/configuration_loader/remote_v2.lua, t/015-configuration-loading-boot-remote.t
fixes a bug introduced in https://github.com/3scale/apicast/pull/323
which prevented apicast in production to boot
=> [remote_v2] fix boot loading configuration

apicast/src/configuration_loader/remote_v2.lua, t/015-configuration-loading-boot-remote.t
the same as https://github.com/3scale/apicast/pull/325
but for lazy loader
=> [remote_v2] test and fix lazy configuaration loader

Dangerfile
not really useful and just creates noise
=> [danger] disable danger-prose

.travis.yml
so we can just tag in git and let travis build the rest
=> [travis] build git tags and also push builder image

examples/s2i/.env, examples/s2i/README.md, examples/s2i/apicast-customization-0.1-1.rockspec
depends on https://github.com/3scale/s2i-openresty/pull/21
depends on https://github.com/3scale/apicast/pull/330
closes https://github.com/3scale/apicast/issues/320
=> [example] improve s2i example with custom rockspec

.codeclimate.yml, .luacheckrc, .travis.yml, Makefile, script/redis.lua
use new http://github.com/mikz/codeclimate-luacheck instead of custom build step
=> replace luacheck with codeclimate

openshift/apicast-template.yml
* remove unnecessary param
* unify redis variables
=> [openshift] update apicast template

README.md, doc/openshift-guide.md
the same as https://github.com/3scale/apicast/pull/352
=> [doc] use the correct name of the OpenShift secret

examples/add-ssl/README.md
The paths were not working anymore with the latest image.
=> [example] Update volume paths for adding SSL

Dangerfile
https://github.com/3scale/apicast/pull/363#issuecomment-300090387
=> [danger] require changelog only when merging to master

.gitignore, CHANGELOG.md, apicast-scm-1.rockspec, apicast/Makefile, apicast/bin/apicast, apicast/bin/apicast-lua
Ability to install APIcast from [luarocks.org](https://luarocks.org/modules/3scale/apicast).
=> Publish APIcast on Luarocks

.circleci/config.yml, .travis.yml, Makefile
danger does not really support circleci v2
=> run danger on travis

CHANGELOG.md, apicast/src/configuration_loader/remote_v2.lua, spec/configuration_loader/remote_v2_spec.lua
no need to load all services just to load them later
=> [remote_v2] limit number of services loaded from the API

CHANGELOG.md, apicast/bin/apicast, apicast/src/configuration_loader.lua
* allow remote configuration URL
* allow loading configuration on boot via a flag
=> [cli] improve configuration handling

.busted, apicast/src/management.lua, apicast/src/resty/resolver.lua, apicast/src/resty/resolver/cache.lua, spec/configuration_loader_spec.lua, spec/proxy_spec.lua, spec/resty/resolver_spec.lua, t/001-management.t
shuffle busted tests, viva la resistance!
=> [busted] shuffle tests

.github/CONTRIBUTING.md, CHANGELOG.md
https://github.com/3scale/apicast/releases/tag/v3.1.0-beta1
=> [changelog] update for 3.1.0-beta1 release

.circleci/config.yml, .travis.yml, README.md, doc/why.md, spec/resty/http_ng/backend/async_resty_spec.lua
push built docker image to quay from circleci
=> [circle] try to build and push docker image

CHANGELOG.md
=> [changelog] update changelog for v3.1.0-beta2

CHANGELOG.md, apicast/src/configuration_loader/remote_v2.lua, spec/configuration_loader/remote_v2_spec.lua
fixes https://github.com/3scale/apicast/issues/398
=> [oidc] don't crash on empty issuer

.circleci/config.yml
automatically build git tags and push builds to quay
=> [circle] build git tags to quay

.circleci/config.yml
https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
https://github.com/3scale/apicast/pull/411 was incomplete
https://circleci.com/workflow-run/dbbd7ec7-7589-4abd-a475-c9ab452db644
=> [circle] build git tags

Brewfile
* defines dependencies
* can be installed by `brew bundle`
=> [brew] add Brewfile

t/003-apicast.t, t/008-apicast-request-logs.t, t/009-apicast-caching.t, t/010-apicast-mapping-rules.t
Small fix. While reviewing the tests I found that the numbering is broken in some test files.
=> Fix tests numbering

.circleci/config.yml
fix broken circleci build on 3.1-stable
@mayorova 3.1-stable on quay should be updating now
=> [circleci] fix missing ldoc

.busted, .circleci/config.yml
* output busted tests as junit
* output Test::Nginx as junit
* upload them as artifacts
* process them on circleci
=> [ci] enable junit

.circleci/config.yml, Makefile, apicast/apicast-0.1-0.rockspec, luarocks.config
workaround for https://github.com/luarocks/luarocks/issues/740
=> use local lua-rover

.circleci/config.yml, docker-compose.benchmark.yml
Run wrk benchmark on CircleCI, so we get some ballpark performance numbers to stop massive performance regression.
=> Run benchmark on CircleCI

.circleci/config.yml, Makefile, docker-compose.benchmark.yml, script/wrk-report.lua
* store CSV report
* benchmark master branch on the same machine for comparison as there can be huge performance difference between machines
* `make benchmark`
=> Improve CircleCI benchmark job

apicast/src/apicast/cli.lua, apicast/src/apicast/cli/start.lua
* with `-m off` flag 
* needed for performance tests
=> [cli] enable controlling nginx master process

Makefile, docker-compose.benchmark.yml
* test successful response before running benchmark
* use retries to get rid of sleep
=> [make] verify benchmark works with curl

apicast/src/configuration.lua, apicast/src/configuration/service.lua, t/apicast.t
=> Treat ngx.req.get_post_args() errors

PERFORMANCE.md, Vagrantfile
* install dependencies with rover
* install wrk
* update performance testing instructions
=> [vagrant] update vagrant box

CHANGELOG.md, apicast/src/configuration_store.lua, spec/configuration_store_spec.lua
Backport changes from 3.1-stable branch to master.
=> merge 3.1-stable to master

.circleci/config.yml, .gitignore, .travis.yml, Makefile, doc/config.ld
* into `doc/lua`
* upload it to CircleCI as an artifact
* do not generate it when nothing changed locally
You can see generated artifacts: https://2478-53965666-gh.circle-artifacts.com/0/doc/index.html
=> [ldoc] generate lua documentation

.github/changelog.yml
https://github.com/apps/probot-changelog
=> [changelog] configure probot-changelog

Makefile, doc/config.ld
* fix make target not updating when deep nested files changed
* break luadoc compat mode for nicer tag syntax
=> improve documentation

Dockerfile-development, script/test
=> Update base image of development Dockerfile to use latest s2i-openresty

CHANGELOG.md, gateway/src/apicast/cli/filesystem.lua, gateway/src/apicast/cli/template.lua
closes #545, fixes https://github.com/stevedonovan/Penlight/issues/265
=> [t] fix hanging test suite

spec/executor_spec.lua
This PR adds some missing tests for `Executor.context()`.
=> Test Executor.context()

CHANGELOG.md, Makefile, gateway/config/development.lua
Changing the ENV inside the container would result in not finding libraries and scripts.
=> [cli] fix development config running inside docker

.circleci/config.yml, Makefile, gateway/src/apicast/policy/caching/schema.json
=> [ci] lint JSON schema

gateway/Roverfile.lock
* after fixing multiple groups of a dependency
https://github.com/3scale/lua-rover/pull/15
=> [rover] update lockfile

gateway/cpanfile, gateway/src/apicast/policy/local_chain/policy.lua, spec/executor_spec.lua, spec/policy_chain_spec.lua, t/apicast-path-routing.t
small test cleanup extracted from https://github.com/3scale/apicast/pull/566
=> cleanup spec and integration tests

.circleci/config.yml
=> [s2i] update s2i-openresty

gateway/src/apicast/loader.lua, gateway/src/apicast/module.lua, gateway/src/apicast/policy/local_chain/local_chain.lua
* allow setting empty APICAST_MODULE
* first try to load renamed policy via policy_loader
=> fix issues failing to load APIcast Cloud Hosted policies

CHANGELOG.md, gateway/src/apicast/version.lua
prepare for v3.2.0-beta1 release
=> [release] prepare v3.2.0-beta1 release

spec/policy/headers/headers_spec.lua
This policy only had integration tests.
=> Add unit tests for the headers policy

gateway/src/apicast/policy/cors/cors.lua, spec/policy/cors/cors_spec.lua, t/apicast-policy-cors.t
- Adds some missing checks in the integration tests for the CORS policy.
- Fixes a minor thing in the CORS policy code.
- Adds unit tests for the CORS policy.
=> Add more tests for the CORS policy

CHANGELOG.md, gateway/src/apicast/policy/apicast/apicast-policy.json, gateway/src/apicast/policy/caching/apicast-policy.json, gateway/src/apicast/policy/cors/apicast-policy.json, gateway/src/apicast/policy/echo/apicast-policy.json, gateway/src/apicast/policy/headers/apicast-policy.json, gateway/src/apicast/policy/manifest-schema.json, gateway/src/apicast/policy/soap/apicast-policy.json, gateway/src/apicast/policy/upstream/apicast-policy.json, gateway/src/apicast/policy/url_rewriting/apicast-policy.json
Closes https://github.com/3scale/apicast/issues/614 
/cc @ddcesare @thomasmaas
=> Add summary to policy manifests

README.md, examples/policies/README.md
Small doco update to include dependency install steps
=> Update README and polices README to include dependency install step

gateway/src/apicast/policy/caching/apicast-policy.json, gateway/src/apicast/policy/caching/caching.lua
This PR changes the description of the number of cache polices, from three to four.
=> Cache policy description

CHANGELOG.md, gateway/src/apicast/version.lua
=> [release] v3.2.0-rc1

.github/CONTRIBUTING.md
and lock it to specific revision
=> [doc] fix broken link

docker-compose-devel.yml, script/test
run the devel container as root
=> [dev] no sudo in script/test

examples/policies/rate_limit_configuration.lua
I cherry-picked this from #697 by @y-tabata
It's something that we need to merge soon to release a new version and I don't have permissions to edit the PR.
Thanks for your contribution @y-tabata
=> Adapt rate limit policy example config to the new config schema

CHANGELOG.md, gateway/src/apicast/version.lua
Updates master branch changelog after https://github.com/3scale/apicast/pull/699
=> Master 3.2 stable

CHANGELOG.md, gateway/.s2i/bin/run
Delegate all validation work to the Lua CLI.
=> [s2i] do not check ENV in run script

gateway/cpanfile
* https://github.com/3scale/Test-APIcast/pull/7
* https://github.com/3scale/Test-APIcast/pull/6
* https://github.com/3scale/Test-APIcast/commit/f5451e4cf1981dc019163011a3abbb5d6ec9739e
* https://github.com/3scale/Test-APIcast/commit/2afe42d02c327efbc357445eb82d40a6398479c3
=> [t] update Test::APIcast

.busted, .circleci/config.yml, .gitignore, .travis.yml, Makefile, bin/busted, gateway/.s2i/bin/assemble, gateway/cpanfile.snapshot, script/prove, script/s2i, spec/ci_reporter.lua
* s2i build caching
* more parallelization
* fixed benchmark target
* show busted tests in log too
* uses carton (again) to cache perl dependencies
=> CI improvements

CHANGELOG.md, gateway/src/apicast/version.lua
Notice that the base branch of this PR is `3.2-stable`.
=> release: 3.2.0

CHANGELOG.md, doc/parameters.md, gateway/conf/nginx.conf.liquid, gateway/src/apicast/cli/command/start.lua
=> Make access_log location configurable

.github/CODEOWNERS
https://help.github.com/articles/about-codeowners/
Hopefully this should notify relevant people when changes are made.
=> [github] set up code owners

.circleci/config.yml
This is just a test of the CircleCI config changes introduced in #705
=> [DON'T MERGE] CircleCI test

doc/policy-development.md
Hello,
This pull request is a Work in Progress for #720. I started with readily available information (links to existing documentation) so that we can start building on it. 
I planned to contribute the other sections in separate pull requests, would it be ok ? 
Any feedback is welcome ! (cc @alanmoran, @andrewdavidmackenzie)
=> Policy Development Documentation

gateway/src/apicast/policy/rate_limit/rate_limit.lua, gateway/src/apicast/policy/rate_limit/redis_shdict.lua, spec/policy/rate_limit/redis_shdict_spec.lua
* extract redis shdict into own module
* start spec for the redis shdict
* implement init_ttl parameter of incr
/cc @y-tabata my plan is to extract this module and have standalone unit tests for it
=> [rate-limit] extract redis shdict

gateway/src/apicast/policy/rate_limit/rate_limit.lua, spec/policy/rate_limit/rate_limit_spec.lua
* use setup / perform / assert blocks separated by whitespace
* use one redis connection
* group similar tests into groups
* every test has to have assert
* prepare shdict mock or extraction
/cc @y-tabata
=> [spec] unify style of rate limit policy test

gateway/src/apicast/policy/rate_limit/rate_limit.lua, spec/luassert_helper.lua, spec/policy/rate_limit/rate_limit_spec.lua
* extract assert.returns_error
* assertions everywhere
It makes it more obvious where are the errors when everything fails.
=> [spec] improve rate limit spec

spec/ngx_helper.lua
If some code like `resty.limit.req` is loaded globaly for the whole test suite,
it will take reference to `ngx.shared` and replacing that table would have no effect.
=> [spec] do not replace ngx.shared entirely

.circleci/config.yml, .gitignore, Makefile, gateway/cpanfile, gateway/cpanfile.snapshot
JUnit reports would be deleted before could be reported to CircleCI.
Also record one log file for all tests and store it as an artifact.
And fix running prove with JUnit reporting locally as well as update cpan lock file when cpanfile changes.
=> Fix recording JUnit and logs on CircleCI

.codeclimate.yml
Luacheck can measure cyclomatic complexity
=> [wip][codeclimate] measure cyclomatic complexity

.circleci/config.yml, Makefile, Vagrantfile, script/install/apicast.sh, script/install/centos.sh, script/install/circleci.sh, script/install/utilities.sh
Create new job that can run stapxx and other OpenResty profiling tools.
Lets create some automated profiling tasks that record artifacts, so we can track how much Lua code is JIT compiled, GC pressure, etc.
=> [circleci] install native apicast for profiling

gateway/src/apicast/proxy.lua, gateway/src/resty/concurrent/event.lua, gateway/src/resty/concurrent/executor.lua, gateway/src/resty/concurrent/future.lua, gateway/src/resty/concurrent/immediate_executor.lua, gateway/src/resty/concurrent/safe_task_executor.lua, gateway/src/resty/concurrent/timer_pool_executor.lua, spec/resty/concurrent/event_spec.lua, spec/resty/concurrent/executor_spec.lua, spec/resty/concurrent/future_spec.lua, spec/resty/concurrent/immediate_executor_spec.lua, spec/resty/concurrent/safe_task_executor_spec.lua, spec/resty/concurrent/timer_pool_executor_spec.lua
Takes design from concurrent-ruby
=> [resty.concurrent] collection of modules for concurrent programming

gateway/src/apicast/policy/rate_limit/README.md
=> Add docs for the rate-limit policy

doc/parameters.md
This was added in https://github.com/3scale/apicast/pull/599
=> Document APICAST_OIDC_LOG_LEVEL env var

Makefile, README.md, script/install/apicast.sh
`dependencies` should install everything
`lua_modules` just lua modules
=> [make] cleanup dependencies targets

CHANGELOG.md, gateway/src/apicast/configuration.lua, gateway/src/apicast/policy_chain.lua, spec/configuration_spec.lua, spec/policy_chain_spec.lua, t/apicast-policy-chains.t
Invalid policies in the chain are ignored.
=> [policy_chain] skip invalid policy configurations

.circleci/config.yml
See the docs and new features: https://github.com/CircleCI-Public/config-preview-sdk
Probably the best feature is that the build will get cancelled on force push.
=> CircleCI 2.1 preview

spec/resty/oidc/discovery_spec.lua
Regression test for [THREESCALE-583](https://issues.jboss.org/browse/THREESCALE-583)
=> [spec] test OIDC Discovery content type with charset

.circleci/config.yml
Use 3 instead of just 1 runner.
=> [circleci] parallelize prove job

.circleci/config.yml, Makefile
* properly split prove test suite 
* do not wait for tests to finish to push container images
* push container images directly from s2i-* jobs
* do not install perl dependencies in build-lua
=> [circleci] improve build times

CHANGELOG.md, gateway/src/apicast/oauth/oidc.lua, spec/oauth/oidc_spec.lua, t/apicast-oidc.t, t/apicast-policy-headers.t, t/apicast-policy-keycloak-role-check.t, t/apicast-policy-rate-limit.t, t/apicast-policy-token-introspection.t
=> Merge JWT validation fix (#864) into 3.3-stable

CHANGELOG.md, gateway/bin/apicast
Bring 3.3-stable changes to master.
Only includes #868
=> Merge 3.3 stable

t/apicast-bin.t
Regression test for https://github.com/3scale/apicast/pull/868
=> [t] test empty APICAST_LOG_LEVEL

gateway/src/resty/resolver.lua, spec/spec_helper.lua
The proxy setting should be automatically reset between test runs.
=> [spec] reset proxy settings between test runs

gateway/src/apicast/configuration.lua, gateway/src/apicast/configuration_loader/remote_v2.lua, gateway/src/apicast/policy/token_introspection/token_introspection.lua, t/apicast-policy-token-introspection.t
OIDC configuration from OIDC Discovery is not the parsed configuration
of the Service.
/cc @mayorova
=> [config] clarify difference between oidc objects by renaming them

doc/policies.md, gateway/src/apicast/policy/liquid_context_debug/apicast-policy.json
=> Clarify order or policies that run on the content phase

CHANGELOG.md, gateway/src/apicast/policy/rate_limit/rate_limit.lua, gateway/src/apicast/template_string.lua, spec/policy/conditional/operation_spec.lua, spec/policy/headers/headers_spec.lua, spec/policy/keycloak_role_check/keycloak_role_check_spec.lua, spec/policy/url_rewriting/url_rewriting_spec.lua, spec/template_string_spec.lua, t/apicast-policy-url-rewriting.t
=> Merge what's exposed by 'ngx_variable' in TemplateString:render()

CHANGELOG.md, gateway/src/apicast/oauth/oidc.lua, gateway/src/apicast/proxy.lua, gateway/src/apicast/util.lua, spec/oauth/oidc_spec.lua, t/apicast-oidc.t
* print error log when OIDC configuration is missing
* print full log when downloading configuration on boot, it could have been trimmed with high log levels like debug
=> Help debugging invalid OIDC configuration

CHANGELOG.md, gateway/src/apicast/policy/liquid_context_debug/apicast-policy.json, gateway/src/apicast/policy/liquid_context_debug/context_content.lua, spec/policy/liquid_context_debug/context_content_spec.lua, t/apicast-policy-liquid-context-debug.t
=> Fix bug when using the liquid debug policy with a config that contains Liquid templates

CHANGELOG.md, gateway/src/apicast/policy_chain.lua, gateway/src/apicast/template_string.lua, spec/policy_chain_spec.lua, spec/template_string_spec.lua, t/apicast-policy-chains.t, t/apicast-policy-invalid-config.t, t/fixtures/policies/error_policy/1.0.0/apicast-policy.json, t/fixtures/policies/error_policy/1.0.0/error_policy.lua, t/fixtures/policies/error_policy/1.0.0/init.lua, t/liquid.t
=> Handle properly configs with invalid Liquid templates

CHANGELOG.md, gateway/Roverfile, gateway/Roverfile.lock, gateway/src/apicast/policy/ip_check/apicast-policy.json, gateway/src/apicast/policy/ip_check/client_ip.lua, gateway/src/apicast/policy/ip_check/init.lua, gateway/src/apicast/policy/ip_check/ip_check.lua, spec/policy/ip_check/client_ip_spec.lua, spec/policy/ip_check/ip_check_spec.lua, t/apicast-policy-ip-check.t
=> IP check policy

CHANGELOG.md, gateway/src/apicast/metrics/upstream.lua, gateway/src/apicast/policy/nginx_metrics/nginx_metrics.lua, t/prometheus-metrics.t
Part of #745 
It's the only metric missing from the list in the issue.
=> Add Prometheus metric for request response times

doc/prometheus-metrics.md
Part of https://github.com/3scale/apicast/issues/745
=> Document exported Prometheus metrics

gateway/src/apicast/policy/conditional/apicast-policy.json
Ask requested by @vramosp in https://issues.jboss.org/browse/THREESCALE-1381
=> [THREESCALE-1381] Label the conditional policy as "Tech preview"

README.md
My objectives with this:
- Make it clear how to get started quickly with Docker.
- Highlight the main features of APIcast
- Put all the docs about more complex topics in their own section so 1) new users/contributors do not feel overwhelmed by a huge README and 2) more experienced users can find links to the more advanced features easily.
- Delete outdated information and also some things that I don't think are important enough to be in the README.
- Try to structure the information better in different sections.
=> README revamp

CHANGELOG.md
Missing deprecation notices of environment variables added to changelog
=> adds env vars deprecation notice to changelog

.circleci/config.yml
* cleanup old images
* remove images before building 
* update s2i
* update s2i-openresty
=> [circleci] cleanup docker images

CHANGELOG.md, gateway/src/apicast/mapping_rule.lua, gateway/src/apicast/mapping_rules_matcher.lua, spec/mapping_rule_spec.lua, spec/mapping_rules_matcher_spec.lua, t/apicast-mapping-rules.t
=> Add ability to stop matching mapping rules when there's a match

CHANGELOG.md, gateway/src/apicast/http_proxy.lua, gateway/src/apicast/policy/routing/README.md, gateway/src/apicast/policy/routing/apicast-policy.json, gateway/src/apicast/policy/routing/rule.lua, gateway/src/apicast/policy/routing/upstream_selector.lua, gateway/src/apicast/proxy.lua, gateway/src/apicast/upstream.lua, spec/policy/routing/upstream_selector_spec.lua, spec/upstream_spec.lua, t/apicast-policy-routing.t
=> Routing policy: allow to modify the Host header

gateway/src/apicast/policy/tls_validation/apicast-policy.json
/cc @vramosp 
the final name shall be `TLS Client Certificate Validation`
=> [tls-validation] rename to TLS Client Certificate Validation

CHANGELOG.md, gateway/src/apicast/backend_client.lua, spec/backend_client_spec.lua, t/apicast-oauth.t, t/apicast-oidc.t
Fixes #989 
Ref: https://issues.jboss.org/browse/THREESCALE-2006
=> OIDC: Set "no_body" option when authorizing against the 3scale backend

CHANGELOG.md, gateway/src/apicast/version.lua
=> Release 3.5.0-rc1

CHANGELOG.md, gateway/src/apicast/policy/keycloak_role_check/apicast-policy.json
Ref https://issues.jboss.org/browse/THREESCALE-1867
=> [THREESCALE-1867] keycloak role check policy : fix inaccurate desc of client field

Makefile, script/prove
- Added BUSTED_ARGS on makefile. 
- Allow to run a single integration test and trigger the ONLY error on CI.
=> Workflow enhacements

gateway/src/resty/ctx.lua, t/apicast-policy-3scale-batcher.t
Small changes required for APIcast to work with latest OpenResty and recent Perl.
Both make prove and busted passes locally.
=> OpenResty 1.15.8.1 and Perl 5.28.1 compatibility

CHANGELOG.md, doc/parameters.md, gateway/conf.d/apicast.conf, gateway/src/apicast/balancer.lua, gateway/src/apicast/cli/environment.lua, gateway/src/apicast/executor.lua, gateway/src/apicast/policy/retry/README.md, gateway/src/apicast/policy/retry/apicast-policy.json, gateway/src/apicast/policy/retry/init.lua, gateway/src/apicast/policy/retry/retry.lua, gateway/src/resty/balancer.lua, spec/executor_spec.lua, spec/policy/retry/retry_spec.lua, spec/resty/balancer_spec.lua, t/apicast-policy-retry.t
Fixes [THREESCALE-1517] (https://issues.jboss.org/browse/THREESCALE-1517)
This PR adds the Retry policy. The PR contains a README that explains how the policy works and how to configure it.
=> [THREESCALE-1517] Retry policy

gateway/cpanfile, gateway/cpanfile.snapshot
=> Test: Bump test apicast to 0.24

CHANGELOG.md, gateway/src/apicast/policy/jwt_claim_check/apicast-policy.json, gateway/src/apicast/policy/jwt_claim_check/init.lua, gateway/src/apicast/policy/jwt_claim_check/jwt_claim_check.lua, gateway/src/apicast/policy/jwt_claim_check/readme.md, spec/policy/jwt_claim_check/jwt_claim_check_spec.lua, t/apicast-policy-jwt-claim-check.t
Hi, 
This PR contains the JWT claim policy, not a big change at all, multiple commits all should be descriptive enough. 
Example policy: 
```
{
"services": [
{
"id": 200,
"endpoint": "http://localhost:8080",
"backend_version": "1",
"backend_version": "oauth",
"proxy": {
"authentication_method": "oidc",
"oidc_issuer_endpoint": "http://192.168.15.103:10000/auth/realms/3scale",
"service_backend_version": "1",
"hosts": [
"one"
],
"proxy_rules": [
{
"pattern": "/",
"http_method": "GET",
"metric_system_name": "hits",
"delta": 1
}
],
{
},
{
"name": "apicast.policy.jwt_claim_check",
"error_message": "Invalid JWT check",
"operations": [
{"op": "==", "match": "acr", "match_type": …
```
=> JWT claim policy

CHANGELOG.md, gateway/src/apicast/policy/jwt_claim_check/apicast-policy.json
Fix various typos.
Added some required fields.
Add description to operations.
=> THREESCALE-3046: Fix policy jsonschema.

CHANGELOG.md, gateway/src/apicast/configuration_loader/data_url.lua, gateway/src/apicast/policy/tls/README.md, gateway/src/apicast/policy/tls/apicast-policy.json, gateway/src/apicast/policy/tls/init.lua, gateway/src/apicast/policy/tls/tls.lua, gateway/src/resty/data_url.lua, gateway/src/resty/mime.lua, spec/configuration_loader/data_url_spec.lua, spec/policy/tls/tls_spec.lua, spec/resty/data_url_spec.lua, spec/resty/mime_spec.lua, t/apicast-policy-tls.t
This PR got some work made by @mikz  around TLS termination in PR https://github.com/3scale/APIcast/pull/1053
=> TLS termination policy

CHANGELOG.md
Fix various typos on Changelog
=> Changelog: Fix typos

CHANGELOG.md
=> Release v3.6.0 stable

CHANGELOG.md, doc/parameters.md
This commit adjust 3.7 Changelog into master
=> Merge 3.7 CHANGELOG to master.

doc/grpc.md
=> Doc: add grpc simple guide

CHANGELOG.md
=> Bump changelog with 3.8 changes

spec/policy/upstream_mtls/upstream_mtls_spec.lua
Unit test was not added in the original PR.
=> Policy: Upstream MTLS add unittesting.

CHANGELOG.md, gateway/src/apicast/policy/url_rewriting/apicast-policy.json, t/prometheus-metrics.t
Fix a few typos in the Jsonchema
FIX THREESCALE-5259
=> Policy: URL rewrite, fix Jsonchema

CHANGELOG.md, gateway/src/apicast/version.lua
=> Release 3.9 CR1

gateway/Roverfile.lock
=> Bump Liquid template engine

CHANGELOG.md, gateway/src/apicast/version.lua
=> v3.9-final

CHANGELOG.md
=> Update master CHANGELOG with 3.9-Changes

CHANGELOG.md, Makefile, doc/parameters.md, travis/config.json
Make it clear to users what URL is used discarded.
Fix THREESCALE-5421
=> Doc: Fix services filter parameter.

CHANGELOG.md, gateway/src/apicast/version.lua
=> Release 3.10.0-alpha1

CHANGELOG.md, gateway/src/apicast/cli/command/start.lua, gateway/src/apicast/cli/template.lua, gateway/src/apicast/configuration.lua, gateway/src/apicast/version.lua, spec/configuration_spec.lua
A small changes for CR1 release.
Version does not contain beta1 because if this is all ok, will be the definitive one. 
Regards
=> Release 3.10-beta1

CHANGELOG.md
=> Bump Changelog for 3.10 release

CHANGELOG.md, gateway/src/apicast/policy/tls/apicast-policy.json
Fix jsonschema title that are not correct
Fix THREESCALE-6390
=> TLS: fix typo on jsonschema

gateway/src/apicast/policy/cors/Readme.md
Added a README  for APICAST CORS Policy that was missing it
=> Added README for APICAST CORS Policy

doc/parameters.md
Depth 1 should mean `Root CA -> Certificate`, Depth 2 should be `Root CA -> Intermediate CA -> Certificate` and so on.
=> Update APICAST_HTTPS_VERIFY_DEPTH description

.circleci/config.yml
=> Bump Openresty version

CHANGELOG.md, gateway/src/apicast/policy/statuscode_overwrite/apicast-policy.json
=> Fix Jsonschema titles for Status code overwrite policy

Makefile, gateway/Roverfile.lock
Enables the date filter on liquid templated
=> Threescale 6594

doc/liquid_conditions.md
=> Doc: Add liquid examples

t/apicast.t
apicast tests converted to Blackbox framework as part of https://github.com/3scale/APIcast/pull/1343
=> t/apicast.t: convert to APIcast::Blackbox

doc/configuration.md, gateway/src/apicast/policy/logging/readme.md
=> Doc: Update some references

t/apicast-request-logs.t
=> apicast-request-logs.t: convert to blackbox

CHANGELOG.md, gateway/src/apicast/version.lua
* CHANGELOG.md: updated
* `gateway/src/apicast/version.lua` set to `latest`. It should be updated accordingly in release branches
=> Latest releases

CHANGELOG.md, gateway/src/apicast/oauth/oidc.lua, spec/oauth/oidc_spec.lua, t/apicast-oidc.t
backport #1389  
Jira issue [THREESCALE-9009](https://issues.redhat.com/browse/THREESCALE-9009)
=> Backport 2.12 THREESCALE-9009 fix OIDC issuer verification

.circleci/config.yml, CHANGELOG.md, gateway/src/apicast/oauth/oidc.lua, gateway/src/apicast/version.lua, spec/oauth/oidc_spec.lua, t/apicast-oidc.t
backport #1389  
Jira issue [THREESCALE-9009](https://issues.redhat.com/browse/THREESCALE-9009)
=> Backport 2.13 threescale 9009 fix OIDC issuer verification

CHANGELOG.md, gateway/src/apicast/cli/environment.lua
backport https://github.com/3scale/APIcast/pull/1410
=> Backport THREESCALE-10167 cpu detection to 2.13

t/apicast-mapping-rules.t
=> apicast-mapping-rules.t conversion to APIcast::Blackbox

dev-environments/http-proxy-plain-http-upstream/Makefile, dev-environments/https-proxy-upstream-tlsv1.3/Makefile, dev-environments/keycloak-env/Makefile, dev-environments/listen-tls/Makefile, dev-environments/opentelemetry-instrumented-gateway/Makefile, dev-environments/plain-http-upstream/Makefile, dev-environments/upstream-tlsv1.3/Makefile
This reverts commit 258b1e988c78d8e9cdae3be271fe4a9e66640ff9.
=> Revert "revert changes not related to camel proxy dev env"

gateway/src/apicast/policy/token_introspection/README.md
Update README file to correct outdated information
=> Update Token Introspection Policy README

.circleci/config.yml, docker-compose-devel.yml
=> Bump CI image to use quay.io/3scale/apicast-ci:openresty-1.21.4-2

gateway/src/apicast/configuration_loader/remote_v2.lua
A small code cleanup and optimization
N/A
=> Code cleanup and optimization for remote_v2

.github/workflows/link_check.yaml, gateway/src/apicast/policy/fapi/apicast-policy.json
=> THREESCALE-11796 - Correct boolean value in the schema

Dockerfile, Dockerfile.devel
Update to latest ubi8 image to fix vulnerabilities reported in our [quay.io](https://quay.io/repository/3scale/apicast?tab=tags)
=> Use latest ubi8 image
